### PR TITLE
storage: List entries from /etc/crypttab that are still locked

### LINKED ISSUE #14697: Locked encrypted filesystems are not included in the list of filesystems
Cockpit version: 229
OS: Debian 10 (Buster)
Page: Storage

Encrypted filesystems are not listed when locked. Only after unlocking they are listed, as shown in below snapshots. To me this seems incorrect as the filesystems exist and the system is aware of them. There is also no other listing where locked encrypted filesystems, other then by browsing all attached disks/partitions to see if there is an encrypted locked file system.

Before unlocking:
Cockpit - Storage - before unlocking

After unlocking:
Cockpit - Storage - after unlocking

After mounting:
Cockpit - Storage - after mounting

### PR DESCRIPTION
**Pull request by mvollmer**
People might want to find them easily in order to unlock them
manually.

Demo: https://www.youtube.com/watch?v=mmFOTQ39ZPk

Fixes #14697

## Release notes

Cockpit now lists those encrypted devices in the overview that are still locked. This makes them easy to find if you want to unlock them manually.

image

### CODE REVIEW

**Comment by mvollmer** [comment]
This needs a test.

**Comment by mvollmer** [comment]
> This needs a test.

Added.

**Comment by andreasn** [comment]
It was a bit tricky for me to read the changes in the code, so do you have some pointers to how to test this easily? If not, I think some screenshots or a quick video also works for me.

**Comment by mvollmer** [comment]
> It was a bit tricky for me to read the changes in the code, so do you have some pointers to how to test this easily? If not, I think some screenshots or a quick video also works for me.

Yes, sorry for dumping this PR on you without explanation: https://www.youtube.com/watch?v=mmFOTQ39ZPk

**Review by andreasn — APPROVED** [review]
Looks good to me!

File: pkg/storaged/crypto-panel.jsx [hunk 1]
```diff
@@ -0,0 +1,86 @@
+/*
+ * This file is part of Cockpit.
+ *
+ * Copyright (C) 2017 Red Hat, Inc.
```
Comment (Gundersanne) [inline pkg/storaged/crypto-panel.jsx:4]: Silly nitpick but 2020. :D

**Review by andreasn — APPROVED** [review]

File: pkg/storaged/crypto-panel.jsx [hunk 2]
```diff
@@ -0,0 +1,86 @@
...
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
+ * Lesser General Public License for more details.
+ *
+ * You should have received a copy of the GNU Lesser General Public License
+ * along with Cockpit; If not, see <http://www.gnu.org/licenses/>.
+ */
+
+import cockpit from "cockpit";
+import React from "react";
+import { cellWidth, SortByDirection } from '@patternfly/react-table';
```
Comment (Gundersanne) [inline pkg/storaged/crypto-panel.jsx:22]: again silly nitpick, but in most other storaged files you import with `"`

**Review by Gundersanne — APPROVED** [review]
lgtm, a style comment which you're free to ignore
