### PR TITLE
base1: add cockpit.assert()

### LINKED ISSUE #20298: consider adding `cockpit.assert()`
Now that we're using typescript, we're going to get into unfortunate situations where we'll have to do type narrowing.

One of the best tools for that is assertions, but since `console.assert()` doesn't actually abort the current control flow, typescript doesn't treat it as a guard.

Node's `assert()` function is different.  It raises an error if the predicate fails, interrupting the calling function.  Typescript has a syntax to support such functions:

```typescript
function assert(predicate: any): asserts predicate {
 ...
}
```

See https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions

See https://github.com/cockpit-project/cockpit-files/pull/365 for a recent example of how this was handled:

```typescript
        if (typeof itemId === "string") {
            ....
        } else {
            console.error("unexpected itemId type", itemId);
        }
```

That doesn't feel great, and I'd prefer not to see it proliferate.  It's also going to cause issues with coverage reporting...

I'd prefer if we could add `cockpit.assert()` as a "hard assert" function, and annotate it accordingly.

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
Add and type-hint a new cockpit.assert() function which throws an error if the given predicate is not true.

Fixes #20298 

followup: add qunit tests.  This requires a bit of `.ts` hackery in our `qunit-test` file, and I don't want to block this feature.

### CODE REVIEW

File: pkg/lib/cockpit.js [hunk 1]
```diff
@@ -4415,6 +4415,12 @@ function factory() {
         return false;
     };
 
+    cockpit.assert = (predicate, message) => {
+        if (!predicate) {
+            throw new Error(`Assertion failed: ${message}`);
```
Comment (martinpitt) [inline pkg/lib/cockpit.js:4420]: I think this should get a `// not-covered: reason` annotation to satisfy coverage?

Comment (martinpitt) [reply pkg/lib/cockpit.js:4420]: ah, you didn't trigger /devel, so it can't complain

**Review by martinpitt — APPROVED** [review]
... but, if it's blocking your work, go ahead

File: pkg/lib/cockpit.js (hunk 1 above)
Comment (allisonkarlitskaya) [reply pkg/lib/cockpit.js:4420]: I actually intend to cover this line when I get the tests working...

**Comment by allisonkarlitskaya** [comment]
> ... but, if it's blocking your work, go ahead

It's not blocking my work, but we wanted it for https://github.com/cockpit-project/cockpit-files/pull/365
