### PR TITLE
machines: Split DeleteResourceSource component to avoid nesting statefull modals inside table rows

### LINKED ISSUE #13860: TestMachinesDBus.testDetachDisk flake: dialog auto-closes sometimes
[test/verify/check-machines-dbus TestMachinesDBus.testDetachDisk](https://logs.cockpit-project.org/logs/pull-13844-20200407-073757-98820c25-debian-testing/log.html#86-2) fails fairly often when trying to detach the "vdc" device. It seems the confirmation dialog opens and immediately auto-closes again.

In the past we fixed that with adding `preventDefault()`, like in commit 1570bf3624dcbb835b. Something similar seems to happen here again.

### PR DESCRIPTION
**Pull request by KKoukiou**
PF4 React Table component sometimes recreates the components inside Table rows,
and then showModal will revert to false, causing the dialog to close.

By keeping the state outside of the Table components we can rely
on the dialog staying open.

Note: Commit 20963cb addressed a similar issue with different approach.
In our case that approach is not adequate because we need to keep
information about more state properties than just the visibility of the
modal.

Fixes #13860

### CODE REVIEW

File: pkg/machines/components/vmDisksTab.jsx [hunk 1]
```diff
@@ -186,12 +191,15 @@ class VmDisksTab extends React.Component {
...
         return (
-            <ListingTable variant='compact'
-                actions={actions}
-                emptyCaption={_("No disks defined for this VM")}
-                aria-label={`VM ${vm.name} Disks`}
-                columns={columnTitles}
-                rows={rows} />
+            <>
+                {this.state.deleteDialogProps && <DeleteResourceModal {...this.state.deleteDialogProps} />}
+                <ListingTable variant='compact'
```
Comment (martinpitt) [inline pkg/machines/components/vmDisksTab.jsx:196]: This makes perfect sense now.

File: pkg/machines/components/networks/network.jsx [hunk 2]
```diff
@@ -157,12 +164,11 @@ class NetworkActions extends React.Component {
...
                 </Button>
                 }
-                <DeleteResource objectType="Network"
-                    objectId={id}
-                    objectName={network.name}
-                    deleteHandler={() => deleteHandler(network)}
-                    overlayText={_("Non-persistent network cannot be deleted. It ceases to exists when it's deactivated.")}
-                    disabled={!network.persistent} />
+                {this.state.deleteDialogProps && <DeleteResourceModal {...this.state.deleteDialogProps} />}
+                <DeleteResourceButton objectId={id}
```
Comment (martinpitt) [inline pkg/machines/components/networks/network.jsx:168]: However, I don't understand how this is supposed to help -- the whole `<NetworkActions>` is still part of a `<ListingRow>`, so if the list gets re-rendered, then both the dialog and the button will be re-created?

**Comment by martinpitt** [comment]
And indeed it [still happens](https://logs.cockpit-project.org/logs/pull-13876-20200408-180233-8263bf4c-debian-testing/log.html#86) :sob:

File: pkg/machines/components/networks/network.jsx (hunk 2 above)
Comment (KKoukiou) [reply pkg/machines/components/networks/network.jsx:168]: It's not making any difference. It's still part of they row in this specific file. But this Listing is the PF3 implementation which has not issues with this so I thought I could just let it there for now. I can move it now if you prefer. The other two dialogs were using PF4 lists which really caused an issue.

**Comment by KKoukiou** [comment]
> And indeed it [still happens](https://logs.cockpit-project.org/logs/pull-13876-20200408-180233-8263bf4c-debian-testing/log.html#86) sob

This is not machines tests. I changed the dialog only in Vm disks, Vm disk and libvirt Virtual Networks dialogs.

File: pkg/machines/components/networks/network.jsx (hunk 2 above)
Comment (martinpitt) [reply pkg/machines/components/networks/network.jsx:168]: Given that the test still failed once with the exact same symptom, I suppose the PF3 list has the same issue?

**Comment by martinpitt** [comment]
FTR, if you want to land it as-is without the Fixes #, I'm fine with that. It's a good change, and maybe helps with making the race less apparent, just is not sufficient yet.
