### PR TITLE
apps, systemd/services: Use single source of truth for page location

### LINKED ISSUE #18465: Services: Clean up URL/filter state handling
[TestPages.testBasic](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18422-20230307-120556-7e7cb6b6-centos-8-stream-pybridge/log.html#302-2) failure is pretty much the last Services page related flake. Once again this is filter/URL options state handling confusing/race condition. This is unrelated to #18422 (where this isssue is broken out from), but now we have a debug log.

We start at the Services page detail:

> debug: XXX ServicesPageBody render path ["test.service"] rendering service details for test.service
> log: XXX cockpit.location.get; window.location.hash "#/test.service" unchanged last_loc

Then the test switches to the /network page:

> -> ph_go("/network")
> <- {'type': 'undefined'}
> log: XXX cockpit.location.get; window.location.hash "#/test.service" unchanged last_loc
> log: XXX cockpit.location.get; window.location.hash "" creating new last_loc
> <- {'type': 'undefined'}

Then switches back to Services:

> -> ph_go("/system/services")
> log: XXX cockpit.location.get; window.location.hash "" unchanged last_loc
> log: XXX cockpit.location.get; window.location.hash "#/" creating new last_loc
> <- {'type': 'undefined'}

... and at that point forgot its previous location. Apparently we expect pages to remember their state/URL options internally, as opposed to treating the URL (aka cockpit.location) as *the* single source of truth. @mvollmer so I suppose that is the reason why we have this duplication of state and URL change listeners?

_Originally posted by @martinpitt in https://github.com/cockpit-project/cockpit/issues/18422#issuecomment-1458223393_

### PR DESCRIPTION
**Pull request by martinpitt**
The current iframe path/options for ServicesPageBody is currently coming
from two different sources: `cockpit.location` and properties passed
from the parent ServicesPage element, which tracks it as React state. As
the latter is "laggy" and sometimes disagrees with cockpit.location,
this led to inconsistent states: the page sometimes "forgot" its current
location when an asynchronous state update overwrote a recently happened
cockpit.location update.

Avoid this race by consistently using cockpit.location for everything.
Keep usePageLocation() only for triggering renders when the options
change, but ignore its state.

Fixes #18465

---

This also fixes the same inconsistency on the apps page, but the other way round: As we don't have to deal with multiple nested components there, and sub-elements (like Service filters) changing the location, it's much simpler to just always use the React state.

This fixes the current top flake:

image

### CODE REVIEW

File: pkg/systemd/services.jsx [hunk 1]
```diff
@@ -880,22 +881,24 @@ const ServicesPage = () => {
...
+    usePageLocation();
 
+    const options = cockpit.location.options;
     const activeTab = options.type || 'service';
     const owner = options.owner || 'system';
     const setOwner = (owner) => cockpit.location.go(cockpit.location.path, { ...cockpit.location.options, owner });
 
     if (owner !== 'system' && owner !== 'user') {
-        console.warn("not a valid location: " + path);
+        console.warn("not a valid location: " + JSON.stringify(cockpit.location));
```
Comment (cockpituous) [inline pkg/systemd/services.jsx:893]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18690-20230423-064143-36147809-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

**Comment by martinpitt** [comment]
Yay, check-pages worked 3x even on [rhel-8-9](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18690-20230423-064143-36147809-rhel-8-9/log.html).

**Review by KKoukiou — APPROVED** [review]

**Comment by mvollmer** [comment]
I would like it better if Services would use the data from usePageLocation consistently, and would never use cockpit.location. Why did you do it one way for Apps, and the other way for Services?

**Comment by martinpitt** [comment]
@mvollmer Remember commit fe6bf330e4144af192802a525 ? There you changed *away* from the React state. We both debugged this a lot in PR #18422. Perhaps we can pass down the react state everywhere, but the delayed-ness of that state gave us no end of trouble.

**Comment by martinpitt** [comment]
@mvollmer See the PR description for a reason -- in most cases I think we should use the usePageLocation() react state (and most pages do). Just the Services page is very nested and distributed, with components dealing with events on their own. So achieving consistency this way seemed easier, as most places already use cockpit.location.

**Comment by mvollmer** [comment]
> @mvollmer Remember commit [fe6bf33](https://github.com/cockpit-project/cockpit/commit/fe6bf330e4144af192802a52576fb8f356172830) ? There you changed _away_ from the React state. We both debugged this a lot in PR #18422. Perhaps we can pass down the react state everywhere, but the delayed-ness of that state gave us no end of trouble.

Yes, very true!

**Review by mvollmer — APPROVED** [review]
