### PR TITLE
networking: fix page crash when wg properties go missing

### LINKED ISSUE #19384: networking: TypeError on missing allowed-ips with manually imported WireGuard files
### Explain what happens

1. Updated to Cockpit 301
2. Try to load Network page -> endless spinner
3. A Wireguard configuration has been in place

### Version of Cockpit

301

### Where is the problem in Cockpit?

Networking

### Server operating system

Debian

### Server operating system version

_No response_

### What browsers are you using?

Firefox

### System log

_No response_

### PR DESCRIPTION
**Pull request by subhoghoshX**
Though the original issue #19384 used wg-quick to configure wireguard, I was unable to reproduce the issue with it, unless I created a brand new connection which seems unnecessary as the tests already had a profile configured. Using `sed` to edit wg keyfile and reproduce should be equivalent.

Other wireguard properties `endpoint` and `listen-port` are either optional or have a default value, so the /network page shouldn't break if they're not set. Missing or invalid `public-key` is equivalent to no peer, so it shouldn't break /network page as well.

fixes #19384

### CODE REVIEW

**Comment by subhoghoshX** [comment]
Let's test on fedora-38 and debian-stable for now. I'm a little worried about debian, IIRC it doesn't keep keyfiles in /etc/NetworkManager. And it took > 1 hr download fedora image, not downloading debian locally :)

**Comment by subhoghoshX** [comment]
Ok debian passed and fedora [failed](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19395-20230926-164105-cb3bfffd-fedora-38-networking/log.html#39-2). Looks like a routing issue.

**Comment by subhoghoshX** [comment]
> Ok debian passed and fedora [failed](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19395-20230926-164105-cb3bfffd-fedora-38-networking/log.html#39-2). Looks like a routing issue.

Fixed :tada: 

I'm not sure how to trigger the rest of the tests...

File: pkg/networkmanager/interfaces.js [hunk 1]
```diff
@@ -591,7 +591,7 @@ export function NetworkManagerModel() {
                 peers: get("wireguard", "peers", []).map(peer => ({
                     publicKey: peer['public-key'].v,
```
Comment (martinpitt) [inline pkg/networkmanager/interfaces.js:592]: The commit message said "public-key is optional as well, so should this also get the `?` treatment?

File: test/verify/check-networkmanager-wireguard [hunk 2]
```diff
@@ -123,6 +123,24 @@ class TestWireGuard(packagelib.PackageCase, netlib.NetworkCase):
         b.wait_not_present("#network-wireguard-settings-dialog")
         b.wait_in_text(f"#networking-interfaces th:contains('{iface_name}') + td", f"1.2.3.4/32, {m1_ip4}/24")
 
+        # if some wg properties are not valid, for example, if it was changed by some external tool, don't crash
+        m1.execute("sed -i 's/.*allowed-ips.*//' /etc/NetworkManager/system-connections/con-wg0.nmconnection")
```
Comment (martinpitt) [inline test/verify/check-networkmanager-wireguard:127]: A more canonical way to write this is `'/allowed-ips/d'`, i.e. "delete a line if it contains that string".

File: test/verify/check-networkmanager-wireguard [hunk 3]
```diff
@@ -140,7 +158,6 @@ class TestWireGuard(packagelib.PackageCase, netlib.NetworkCase):
         m2.execute(f"ip addr add {m2_ip6}/64 dev wg0")
         m2.execute(f"wg set wg0 peer {m1_pubkey} allowed-ips {m1_ip4}/32,{m1_ip6}")
 
-        b.click(f"#networking-interfaces button:contains('{iface_name}')")
```
Comment (martinpitt) [inline test/verify/check-networkmanager-wireguard:143]: This change seems unrelated, what does it do?

**Review by martinpitt — CHANGES_REQUESTED** [review]
Thanks!

File: pkg/networkmanager/interfaces.js (hunk 1 above)
Comment (subhoghoshX) [reply pkg/networkmanager/interfaces.js:592]: It said "Missing or invalid public-key is equivalent to no peer", for invalid/missing `public-key` the `.map(...)` function [here](https://github.com/cockpit-project/cockpit/pull/19395/files#diff-e6968ba34dad066826484f30b54426b4891fbd5e72d45297d295a8f46086e3c8R591) wouldn't even run, as it'd be an empty array of peers.

File: test/verify/check-networkmanager-wireguard (hunk 3 above)
Comment (subhoghoshX) [reply test/verify/check-networkmanager-wireguard:143]: It visits are the interface details page, clicking the interaface name:

image

But now it's visiting the page much earlier [here](https://github.com/cockpit-project/cockpit/pull/19395/files#diff-1e9b8cca06a692aac8083ddc21489f716c3ead2ba9cfd7b88de882faab5dbdd4R132). So, it'd be already be in that page, when it reaches this line.

File: test/verify/check-networkmanager-wireguard (hunk 2 above)
Comment (subhoghoshX) [reply test/verify/check-networkmanager-wireguard:127]: ah, this looks much better, thanks!

File: pkg/networkmanager/interfaces.js (hunk 1 above)
Comment (martinpitt) [reply pkg/networkmanager/interfaces.js:592]: Ah, sorry for the misunderstanding.

File: test/verify/check-networkmanager-wireguard (hunk 3 above)
Comment (martinpitt) [reply test/verify/check-networkmanager-wireguard:143]: Makes sense, thanks!

**Review by martinpitt — APPROVED** [review]
Thanks, the issues are resolved, so this LGTM! I triggered the remaining networking tests.
