### PR TITLE
nav: fix toggling of the system dropdown

### LINKED ISSUE #18182: mobile: When in responsive mode, the system navigation menu pops up again when unasked for
Steps to reproduce:

1. Resize browser to trigger mobile breakpoint. (You don't have to use a mobile browser or even mobile emulation.)
2. Switch pages to something that's not cluttered (so you're not clicking on something accidentally), such as SELinux or Diagnostic Reports.  This happens all the time on the terminal page as well.
3. Click (or tap) on the background of the page.

My guess is that it's either related to focus (possibly with bubbling too) activating the menu again. And/or it's using some kind of a `toggle()` without explicitly setting to true/false.

This breaks mobile functionality everywhere. It can also break desktop browsers too, but only when resized to be small and/or using large enough fonts to trigger the issue. (Both of these things can happen when used "in the wild".)

_Originally posted by @garrett in https://github.com/cockpit-project/cockpit/issues/18157#issuecomment-1384277486_

### PR DESCRIPTION
**Pull request by KKoukiou**
* Don't assume 'active' state of dropdown when toggling the 'interact' class.
* Call the addEventListener only on component mount, and not each time the 'active' state changes.

Fixes #18182

### CODE REVIEW

File: pkg/shell/nav.jsx [hunk 1]
```diff
@@ -19,10 +19,16 @@ export const SidebarToggle = () => {
...
         window.addEventListener("blur", handleClickOutside);
 
         return () => window.removeEventListener("blur", handleClickOutside);
+    }, []);
+
+    useEffect(() => {
+        if (active)
+            document.getElementById("nav-system").classList.add("interact");
+        else
+            document.getElementById("nav-system").classList.remove("interact");
```
Comment (garrett) [inline pkg/shell/nav.jsx:31]: This does the same thing, but with 1 line. It either adds or removes, based on the boolean(ish) value of `active` passed as a second option to [classList.toggle()](https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle).

```suggestion
        document.getElementById("nav-system").classList.toggle("interact", active);
```

...But it could probably be integrated in the above `useEffect` block as well, right? (There probably wouldn't need to be two `useEffect` blocks?)

Comment (KKoukiou) [reply pkg/shell/nav.jsx]: We need the two useEffect blocks, so that the first one runs only on component's first render, as it adds the event listeners.

**Comment by garrett** [comment]
I've been playing around with this on my phone this morning and it's still not fixed. Now it sometimes has the opposite problem, where the menu doesn't show up when it should.

**Comment by garrett** [comment]
A guess: I think when the menu is toggled with the button, it doesn't set the state? So you have to tap it again?
