### PR TITLE
tls: Support multiple listening ports

### LINKED ISSUE #12627: cockpit-tls split regression with multiple listen ports
Cockpit version: 200

With the cockpit-tls introduction, it is no longer possible to set more than one listen port (in my case, 80 and 443).

As explained in https://cockpit-project.org/guide/149/listen.html, it is possible to set multiple listen ports in cockpit.socket file. When file is modified to listen on ports 80 and 443, cockpit-tls failed on start and indicate that it could not start with 2 listen ports.

### PR DESCRIPTION
**Pull request by martinpitt**
In cockpit.socket it's possible to specify `ListenStream=` multiple
times, which will result in multiple listening fds being passed via
systemd. We even document that in our guide.

Support up to 10 fds now and handle them in an array. The epoll data.ptr
is a bit clunky, but as epoll does not return the actual fd for an
event, this saves us from introducing yet another housekeeping
structure.

Fixes #12627

### CODE REVIEW

File: src/tls/server.c [hunk 1]
```diff
@@ -552,45 +553,53 @@ server_init (const char *ws_path,
...
-        errx (1, "This program can only accept exactly one socket from systemd, but got passed %s", listen_fds);
-      server.listen_fd = SD_LISTEN_FDS_START;
-      debug ("Server ready. Listening to systemd activated socket fd %i", server.listen_fd);
+      char *endptr = NULL;
+      long n = strtol (env_listen_fds, &endptr, 10);
+      if (n < 1 || n > MAX_LISTEN_FDS || !endptr || *endptr != '\0')
+        errx (1, "Invalid $LISTEN_FDS value '%s'; this program supports up to 10 fds", env_listen_fds);
+      for (int i = 0, fd = SD_LISTEN_FDS_START; i < n; ++i, ++fd)
+        {
+          server.listen_fds[i] = fd;
```
Comment (allisonkarlitskaya) [inline src/tls/server.c]: This is deeply weird.  We have an array which we fill with completely deterministic values.

I can almost imagine an optimisation where we rather record the number of fds and then any time we see an fd ready to poll which has a value between 3 and 3+num then we know it's a listener.  That's also deeply weird, though.  Also: it doesn't give us an otherwise-useless location to use as epoll's data ptr.

File: src/tls/server.c [hunk 2]
```diff
@@ -552,45 +553,53 @@ server_init (const char *ws_path,
...
+          debug ("Listening to systemd activated socket fd %i", fd);
+        }
```
Comment (allisonkarlitskaya) [inline src/tls/server.c]: please mark EOF (if <10) with -1 rather than 0.  0 is a valid fd.

File: src/tls/server.c [hunk 3]
```diff
@@ -552,45 +553,53 @@ server_init (const char *ws_path,
...
 
-  /* epoll the listening fd */
+  /* epoll the listening fds */
   server.epollfd = epoll_create1 (EPOLL_CLOEXEC);
   if (server.epollfd < 0)
     err (1, "Failed to create epoll fd");
-  ev.data.ptr = &server;
-  if (epoll_ctl (server.epollfd, EPOLL_CTL_ADD, server.listen_fd, &ev) < 0)
-    err (1, "Failed to epoll server listening fd");
+  for (int i = 0; i < MAX_LISTEN_FDS && server.listen_fds[i] > 0; ++i)
```
Comment (allisonkarlitskaya) [inline src/tls/server.c]: `!= -1`, not `> 0`

File: src/tls/server.c [hunk 4]
```diff
@@ -617,7 +626,8 @@ void
 server_cleanup (void)
 {
   close (server.epollfd);
-  close (server.listen_fd);
+  for (int i = 0; i < MAX_LISTEN_FDS && server.listen_fds[i] > 0; ++i)
```
Comment (allisonkarlitskaya) [inline src/tls/server.c]: ditto

File: src/tls/server.c [hunk 5]
```diff
@@ -680,8 +690,8 @@ server_poll_event (int timeout)
     }
   else if (ret > 0)
     {
-      if (ev.data.ptr == &server)
-        handle_accept ();
+      if (ev.data.ptr >= (void *) server.listen_fds && ev.data.ptr < (void *) &server.listen_fds[MAX_LISTEN_FDS])
```
Comment (allisonkarlitskaya) [inline src/tls/server.c]: Is the cast necessary?

File: src/tls/server.c (hunk 1 above)
Comment (martinpitt) [reply src/tls/server.c]: Right, it's by and large an encoding of the fd number to be used with data.ptr, as we want to use pointers consistently. When we previously had the intermixed "data.fd for listen and data.ptr for connections", this was also error prone/weird. Hopefully this will go away with your threading rework anyway. Right now this still strikes me as the less bad approach, but I'm happy to change  this around if you have a cleaner idea.

File: src/tls/server.c (hunk 5 above)
Comment (martinpitt) [reply src/tls/server.c]: Yes, without it:

    src/tls/server.c:699:23: error: comparison of distinct pointer types lacks a cast [-Werror]

which seems fair. Comparing an int* to a void* (i. e. effectively a byte pointer) should be safe for the array start, but not for any of its subsequent members.

File: src/tls/server.c [hunk 6]
```diff
@@ -552,45 +553,53 @@ server_init (const char *ws_path,
...
+  env_listen_fds = secure_getenv ("LISTEN_FDS");
+  if (env_listen_fds && check_sd_listen_pid ())
     {
-      if (strcmp (listen_fds, "1") != 0)
-        errx (1, "This program can only accept exactly one socket from systemd, but got passed %s", listen_fds);
-      server.listen_fd = SD_LISTEN_FDS_START;
-      debug ("Server ready. Listening to systemd activated socket fd %i", server.listen_fd);
+      char *endptr = NULL;
+      long n = strtol (env_listen_fds, &endptr, 10);
+      if (n < 1 || n > MAX_LISTEN_FDS || !endptr || *endptr != '\0')
```
[the remark this answers is not in the document]
Comment (martinpitt) [reply src/tls/server.c]: indeed. I also cleaned it up from the other place.

File: src/tls/server.c (hunk 2 above)
Comment (martinpitt) [reply src/tls/server.c]: Seems odd to not have stdin, but indeed that's better. fixed.

File: src/tls/server.c (hunk 3 above)
Comment (martinpitt) [reply src/tls/server.c]: fixed.

**Comment by martinpitt** [comment]
> Having the n_listen_fds would make it easier to rewrite the pointer compare.

I didn't yet address that part. How would that look easier, OOI? In both cases I would have an integer (`MAX_LISTEN_FDS` vs. `server.n_listen_fds`). I still somehow need to decide whether a data.ptr points inside the listen_fds array. I can't use `data.ptr - server.listen_fds` as that is undefined if it's pointing outside. So I'm a bit at loss here..

Thanks!

**Comment by allisonkarlitskaya** [comment]
> > Having the n_listen_fds would make it easier to rewrite the pointer compare.
> 
> I didn't yet address that part. How would that look easier, OOI? In both cases I would have an integer (`MAX_LISTEN_FDS` vs. `server.n_listen_fds`).

I mean that it would be easier relative to replacing the array with a dynamically allocated one and `-1`-terminating it.  It's exactly equivalent to what you're doing now.

**Comment by allisonkarlitskaya** [comment]
Honestly, though, look:  once we split the connection fds out into helper threads, the main thread epoll is going to contain only the listener sockets and some eventfds.  At this point we could reasonably switch to just using fd numbers in the epoll data struct again, eliminating this entire discussion about the oddity of using an array.

I guess I wouldn't put too much effort into improving this further.
