### PR TITLE
storage: When fixing NBDE, also recognize indirect root filesystems

### LINKED ISSUE #18687: storage: NBDE on block devices without a filesystem is broken
The code for determining whether or not the user is adding a tang key to the root filesystem crashes when there is no filesystem on the LUKS container at all.

### PR DESCRIPTION
**Pull request by mvollmer**
For example, when adding a Clevis key to a block device that is a physical volume of the volume group that contains the root filesystem.

Fixes #18687

### CODE REVIEW

File: pkg/storaged/crypto-keyslots.jsx [hunk 1]
```diff
@@ -303,6 +303,17 @@ function ensure_package_installed(steps, progress, package_name) {
                                 return install_missing_packages(data, status_callback(progress));
                         }
                     });
+            })
+            .catch(error => {
```
Comment (cockpituous) [inline pkg/storaged/crypto-keyslots.jsx:307]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230424-134533-fc33405c-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/storaged/crypto-keyslots.jsx [hunk 2]
```diff
@@ -303,6 +303,17 @@
...
+            // Something wrong with PackageKit, maybe it is not even
+            // installed.  Let's show the error during fixing.
+                progress(null, null);
+                steps.push({
+                    title: cockpit.format(_("The $0 package must be installed."), package_name),
+                    func: progress => {
+                        return Promise.reject(cockpit.format(_("PackageKit error: $0"), error.toString()));
```
Comment (cockpituous) [inline pkg/storaged/crypto-keyslots.jsx:314]: These 5 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230424-134533-fc33405c-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/storaged/utils.js [hunk 3]
```diff
@@ -624,6 +624,30 @@ function get_children(client, path) {
     return children;
 }
 
+export function get_all_children(client, path) {
+    const children = get_children(client, path);
+
+    if (client.blocks[path]) {
+        const mdraid = client.blocks[path].MDRaidMember;
+        if (mdraid != "/")
+            children.push(mdraid);
```
Comment (cockpituous) [inline pkg/storaged/utils.js:633]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230424-134533-fc33405c-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/storaged/utils.js [hunk 4]
```diff
@@ -624,6 +624,30 @@
...
+    }
+
+    if (client.blocks_pvol[path]) {
+        const vgroup = client.blocks_pvol[path].VolumeGroup;
+        if (vgroup != "/")
+            children.push(vgroup);
```
Comment (cockpituous) [inline pkg/storaged/utils.js:639]: These 4 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230424-134533-fc33405c-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/storaged/utils.js [hunk 5]
```diff
@@ -624,6 +624,30 @@
...
+    }
+
+    if (client.blocks_stratis_blockdev[path]) {
+        const pool = client.blocks_stratis_blockdev[path].Pool;
+        if (pool != "/")
+            children.push(pool);
```
Comment (cockpituous) [inline pkg/storaged/utils.js:645]: These 4 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230424-134533-fc33405c-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/storaged/crypto-keyslots.jsx (hunk 1 above)
Comment (mvollmer) [inline pkg/storaged/crypto-keyslots.jsx:307]: Hmm, this could be its own commit.

File: pkg/storaged/crypto-keyslots.jsx [hunk 6]
```diff
@@ -267,6 +267,14 @@ export function init_existing_passphrase(block, just_type, callback) {
    do this unconditionally because it's so fast.
 */
 
+function check_installed_package(name) {
+    // This needs to work without PackageKit, so that people can make
+    // progress by manually installing a package and trying again in Cockpit.
+    return cockpit.spawn(["rpmquery", name], { err: "message" })
+            .then(() => true)
```
Comment (cockpituous) [inline pkg/storaged/crypto-keyslots.jsx:274]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230425-113621-0ab0dcb3-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/storaged/crypto-keyslots.jsx [hunk 7]
```diff
@@ -288,21 +296,40 @@
...
+                if (!installed) {
+                    return check_missing_packages([package_name], null)
+                            .then(data => {
+                                progress(null, null);
+                                if (data.missing_names.length + data.unavailable_names.length > 0)
+                                    steps.push({
+                                        title: cockpit.format(_("The $0 package must be installed."), package_name),
+                                        func: progress => {
+                                            if (data.remove_names.length > 0)
+                                                return Promise.reject(cockpit.format(_("Installing $0 would remove $1."), name, data.remove_names[0]));
```
Comment (cockpituous) [inline pkg/storaged/crypto-keyslots.jsx:310]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230425-113621-0ab0dcb3-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/storaged/crypto-keyslots.jsx [hunk 8]
```diff
@@ -288,21 +296,40 @@
...
+                                            else if (data.unavailable_names.length > 0)
+                                                return Promise.reject(cockpit.format(_("The $0 package is not available from any repository."), name));
```
Comment (cockpituous) [inline pkg/storaged/crypto-keyslots.jsx:312]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230425-113621-0ab0dcb3-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/storaged/crypto-keyslots.jsx [hunk 9]
```diff
@@ -288,21 +296,40 @@
...
+                                            else
+                                                return install_missing_packages(data, status_callback(progress));
+                                        }
+                                    });
+                            })
+                            .catch(error => {
```
Comment (cockpituous) [inline pkg/storaged/crypto-keyslots.jsx:318]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230425-113621-0ab0dcb3-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/storaged/crypto-keyslots.jsx [hunk 10]
```diff
@@ -288,21 +296,40 @@
...
+                                // Something wrong with PackageKit, maybe it is not even
+                                // installed.  Let's show the error during fixing.
+                                progress(null, null);
+                                steps.push({
+                                    title: cockpit.format(_("The $0 package must be installed."), package_name),
+                                    func: progress => {
+                                        if (error.problem == "not-found")
+                                            return Promise.reject(cockpit.format(_("Error installing $0: PackageKit is not installed"), package_name));
```
Comment (cockpituous) [inline pkg/storaged/crypto-keyslots.jsx:326]: These 6 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230425-113621-0ab0dcb3-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/storaged/crypto-keyslots.jsx [hunk 11]
```diff
@@ -288,21 +296,40 @@
...
+                                        else
+                                            return Promise.reject(cockpit.format(_("Unexpected PackageKit error during installation of $0: $1"), package_name, error.toString()));
```
Comment (cockpituous) [inline pkg/storaged/crypto-keyslots.jsx:328]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230425-113621-0ab0dcb3-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/storaged/utils.js [hunk 12]
```diff
@@ -617,6 +617,30 @@ function get_children(client, path) {
     return children;
 }
 
+export function get_all_children(client, path) {
+    const children = get_children(client, path);
+
+    if (client.blocks[path]) {
+        const mdraid = client.blocks[path].MDRaidMember;
+        if (mdraid != "/")
+            children.push(mdraid);
```
Comment (cockpituous) [inline pkg/storaged/utils.js:626]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230425-113621-0ab0dcb3-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/storaged/utils.js [hunk 13]
```diff
@@ -617,6 +617,30 @@
...
+    if (client.blocks_pvol[path]) {
+        const vgroup = client.blocks_pvol[path].VolumeGroup;
+        if (vgroup != "/")
+            children.push(vgroup);
+    }
+
+    if (client.blocks_stratis_blockdev[path]) {
+        const pool = client.blocks_stratis_blockdev[path].Pool;
+        if (pool != "/")
+            children.push(pool);
```
Comment (cockpituous) [inline pkg/storaged/utils.js:638]: These 4 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230425-113621-0ab0dcb3-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/storaged/crypto-keyslots.jsx (hunk 1 above)
Comment (mvollmer) [reply pkg/storaged/crypto-keyslots.jsx]: Done.

**Comment by mvollmer** [comment]
> I'll increase the coverage of the "packagekit not available" code.

Nice, turns out that code can be a lot simpler, thanks Coverage!

File: pkg/storaged/utils.js (hunk 12 above)
Comment (cockpituous) [inline pkg/storaged/utils.js:626]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230426-124427-e87666b7-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/storaged/utils.js (hunk 13 above)
Comment (cockpituous) [inline pkg/storaged/utils.js:638]: These 4 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230426-124427-e87666b7-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

**Comment by mvollmer** [comment]
This should urgently go into RHEL 9, IMO.

File: pkg/storaged/crypto-keyslots.jsx [hunk 14]
```diff
@@ -395,15 +395,25 @@ function ensure_non_root_nbde_support(steps, progress, client, block) {
...
+function contains_rootfs(client, path) {
+    const block = client.blocks[path];
+    const crypto = client.blocks_crypto[path];
+    let fsys_config = null;
 
-    if (dir == "/") {
+    if (block)
+        fsys_config = block.Configuration.find(c => c[0] == "fstab");
+    if (crypto)
+        fsys_config = crypto.ChildConfiguration.find(c => c[0] == "fstab");
```
Comment (martinpitt) [inline pkg/storaged/crypto-keyslots.jsx:421]: I suppose that works, but it feels a bit brittle and too implicit without an `else` (or possibly reversing the check). Could it ever happen that `block` is in fstab, `crypto` exists, but isn't in fstab?

File: pkg/storaged/utils.js [hunk 15]
```diff
@@ -617,6 +617,30 @@ function get_children(client, path) {
     return children;
 }
 
+export function get_all_children(client, path) {
```
Comment (martinpitt) [inline pkg/storaged/utils.js:620]: Excuse my ignorance here -- does this need to consider partitions on device block objects as well? E.g. "sda1" is also a child of "sda", no?

File: test/common/storagelib.py [hunk 16]
```diff
@@ -588,11 +588,13 @@ def encrypt_root(self, passphrase):
 parted -s {dev} mkpart primary ext4 1M 500M
 parted -s {dev} mkpart primary ext4 500M 100%
 echo {passphrase} | cryptsetup luksFormat --pbkdf-memory=300 {dev}2
-echo {passphrase} | cryptsetup luksOpen --pbkdf-memory=300 {dev}2 dm-test
 luks_uuid=$(blkid -p {dev}2 -s UUID -o value)
-mkfs.ext4 /dev/mapper/dm-test
```
Comment (martinpitt) [inline test/common/storagelib.py:593]: Do we still test a direct "LUKS on plain physical disk" case somewhere? I know that these "encrypted root" tests are horribly expensive, and if we have to choose, then I agree we should test the more complex code path.

**Review by martinpitt — COMMENTED** [review]
Thanks! The tests still need some work, so I'll slip in some thinking aloud. No show-stoppers for me.

File: pkg/storaged/crypto-keyslots.jsx (hunk 14 above)
Comment (mvollmer) [reply pkg/storaged/crypto-keyslots.jsx:421]: Right, adding a "else" is cleaner.
(When crypto is non-null, then block should never have an entry in fstab, since it contains a LUKS container.)

File: test/common/storagelib.py (hunk 16 above)
Comment (martinpitt) [reply test/common/storagelib.py:593]: > Or do you mean rootfs without LVM

Yes, that's what I meant.

File: pkg/storaged/utils.js (hunk 15 above)
Comment (martinpitt) [reply pkg/storaged/utils.js]: I see, thanks for the doc comment!

**Review by martinpitt — APPROVED** [review]
Assuming green, this LGTM now, danke!

File: pkg/storaged/utils.js [hunk 17]
```diff
@@ -617,6 +630,30 @@ function get_children(client, path) {
     return children;
 }
 
+export function get_children(client, path) {
+    const children = get_children_for_teardown(client, path);
+
+    if (client.blocks[path]) {
+        const mdraid = client.blocks[path].MDRaidMember;
+        if (mdraid != "/")
+            children.push(mdraid);
```
Comment (cockpituous) [inline pkg/storaged/utils.js:639]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230427-131407-22f0bf87-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/storaged/utils.js [hunk 18]
```diff
@@ -617,6 +630,30 @@
...
+    if (client.blocks_pvol[path]) {
+        const vgroup = client.blocks_pvol[path].VolumeGroup;
+        if (vgroup != "/")
+            children.push(vgroup);
+    }
+
+    if (client.blocks_stratis_blockdev[path]) {
+        const pool = client.blocks_stratis_blockdev[path].Pool;
+        if (pool != "/")
+            children.push(pool);
```
Comment (cockpituous) [inline pkg/storaged/utils.js:651]: These 4 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230427-131407-22f0bf87-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/storaged/utils.js (hunk 17 above)
Comment (cockpituous) [inline pkg/storaged/utils.js:639]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230428-065732-20b8588e-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/storaged/utils.js (hunk 18 above)
Comment (cockpituous) [inline pkg/storaged/utils.js:651]: These 4 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18698-20230428-065732-20b8588e-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

**Comment by mvollmer** [comment]
I think all the remaining test failures are unrelated.

**Review by KKoukiou — APPROVED** [review]
Trivial reapproval after rebase.
