### PR TITLE
systemd: Fix journalctl follow invocation race

### LINKED ISSUE #18976: TestJournal.testRebootAndTime flakes
Flaky test under the Python bridge: https://cockpit-logs.us-east-1.linodeobjects.com/pull-18963-20230618-195214-a4635ecf-fedora-38-pybridge/log.html#81-2

After changing the test, I now log a `console.error` when there is no match:

```
error: ["check-journal","BEFORE BOOT",""] does not match ["check-journal","BEFORE BOOT","2Occurrences"]
error: ["check-journal","BEFORE BOOT",""] does not match ["check-journal","BEFORE BOOT","2Occurrences"]
```

So we get 2 messages instead of the expected 1. When I execute another unique logger command I get the same issue:

```
logger -p user.err --tag check-journal "BANANA"
```

Two messages logged instead of one. Refreshing the page fixes the “issue”.

Setting a debug point in the append function of `journal.js` we indeed get two journal_entry messages while `journalctl -f` only shows one. Interestingly:

```
root        1297  0.0  0.7  39020  8320 ?        S    00:00   0:00 journalctl -q --no-tail --output=json --priority=err --follow -- SYSLOG_IDENTIFIER=check-journal
root        1308  0.0  0.7  39020  8320 ?        S    00:00   0:00 journalctl -q --no-tail --output=json --cursor=s=9bf0c5004ca44faab06bc462dfd1a555;i=637;b=c9863ac3c88949509069b16ff9e8de70;m=1222567;t=78304a4fe6aee;x=5aa9807b30a9be95 --priority=err --follow -- SYSLOG_IDENTIFIER=check-journal
```

After a refresh!

```
[root@fedora-38-127-0-0-2-2201 ~]# ps aux | grep journalctl
root        1509  0.0  0.7  39020  8320 ?        S    00:11   0:00 journalctl -q --no-tail --output=json --cursor=s=9bf0c5004ca44faab06bc462dfd1a555;i=759;b=c9863ac3c88949509069b16ff9e8de70;m=24c291bf;t=78304c89ed758;x=427f69f20ed6aca6 --priority=err --follow -- SYSLOG_IDENTIFIER=check-journal
root        1526  0.0  0.1   6360  2048 pts/0    S+   00:12   0:00 grep --color=auto journalctl
```

So we somehow keep a journalctl -f alive from the initial load of the logs page after switching to `/logs#?tags=check-journal`.

[another example](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19009-20230628-103340-4195a080-fedora-38-other/log.html#126-2)

### PR DESCRIPTION
**Pull request by martinpitt**
When the filter gets changed while the initial non-following journalctl
runs, that runs updateQuery with new options. That will first stop all
previous journalctls. However, that will still call the `.done()`
handler for that initial journalctl query, and happily go on with
starting the subsequent journalctl in following mode. This results in
two journalctls running at the same time, leading to duplicated entries.

To fix that, add a `stopped` flag to the returned journalctl object, and
don't start the following journalctl if it's set.

Fixes #18976

-----

This fixes the [TestJournal.testRebootAndTime() flake](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19009-20230628-103340-4195a080-fedora-38-other/log.html#126-2). See #18976 for the gory details. This now locally survived two parallel runs of

    for i in `seq 10`; do TEST_ALLOW_JOURNAL_MESSAGES='.*avc.*' test/verify/check-system-journal TestJournal.testRebootAndTime || break; done
 
on a fedora-38 pybridge image.

### CODE REVIEW

File: pkg/systemd/logsJournal.jsx [hunk 1]
```diff
@@ -137,16 +137,8 @@ export class JournalBox extends React.Component {
...
-                            boot,
-                            count: 0,
-                            follow: true,
-                            grep,
-                            priority,
-                            since,
-                            until,
-                        };
+                    if (!last && !promise.stopped) {
+                        Object.assign(journalctlOptions, { since, count: 0, follow: true });
```
Comment (cockpituous) [inline pkg/systemd/logsJournal.jsx:141]: These 2 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19041-20230629-103311-398fec5e-fedora-38-devel-expensive//Coverage/lcov/github-pr.diff.gcov.html)

**Comment by martinpitt** [comment]
I added a second commit to fix the timeouts in testBasic. I ran this 5 times locally with a global `wait_timeout(5)` and did not get a single "XX% of the timeout" warning aside from the  expected wait_slow10() one. Let's test this on all OSes.

File: pkg/systemd/logsJournal.jsx [hunk 2]
```diff
@@ -137,7 +137,7 @@ export class JournalBox extends React.Component {
                 .done(() => {
                     this.setState({ streamFinished: true });
 
-                    if (!last) {
+                    if (!last && !promise.stopped) {
```
Comment (cockpituous) [inline pkg/systemd/logsJournal.jsx:140]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19041-20230629-141509-f1fca553-fedora-38-devel-expensive//Coverage/lcov/github-pr.diff.gcov.html)

**Comment by martinpitt** [comment]
[another easy fix](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19041-20230629-152605-f1fca553-debian-testing-other/log.html#57), will send a separate PR for that. Retrying.

**Review by jelly — APPROVED** [review]
Thanks for pushing this over the finish line :+1:
