### PR TITLE
lib: Avoid infinite layout measurements in plots

### LINKED ISSUE #20171: plot useLayoutSize() crashes on infinite recursion
### Explain what happens

1. Click the "Storage" or "Networking" tab
2. Load to a blank screen with the "Oops!" error hint at the top right

This issue does not manifest in Firefox. Ungoogled Chromium (flatpak 122.0.6261.111)

#### Storage error:
```
storaged.js:8 Uncaught Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at oi (storaged.js:8:33845)
    at OQ (storaged.js:6:24880)
    at storaged.js:655:511
    at $h (storaged.js:8:24270)
    at tB (storaged.js:8:31626)
    at YT (storaged.js:8:31478)
    at VQ (storaged.js:8:31016)
    at YQ (storaged.js:8:40923)
    at Rc (storaged.js:8:40281)
    at aB (storaged.js:8:36889)
```

#### Networking error
```
networkmanager.js:8 Error: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at bn (networkmanager.js:8:33829)
    at hD (networkmanager.js:6:24854)
    at networkmanager.js:17:509
    at kv (networkmanager.js:8:24259)
    at pI (networkmanager.js:8:31611)
    at o2 (networkmanager.js:8:31463)
    at OD (networkmanager.js:8:31001)
    at AD (networkmanager.js:8:40897)
    at hi (networkmanager.js:8:40257)
    at dI (networkmanager.js:8:36867)
```

### Version of Cockpit

311

### Where is the problem in Cockpit?

Storage, Networking

### Server operating system

Fedora

### Server operating system version

39

### What browsers are you using?

Other

### System log

_No response_

### PR DESCRIPTION
**Pull request by mvollmer**
The SvgPlot component forces a re-render when the size of its outer
"div" has changed. This requires that this outer div settles on a
stable size.
    
However, some browsers can optionally add noise to the result of
getBoundingClientRect, which causes a constant re-rendering of the
plots since the "div" never seems to settle.
    
Thus, we tolerate the noise and only re-render when the size has
changed significantly.

Fixes #20171

### CODE REVIEW

**Comment by mvollmer** [comment]
I feel like I am missing some obvious solution here... is it really that hard to get the size of things?  There is ResizeObserver...

**Comment by martinpitt** [comment]
Thanks @mvollmer! @joshqou please feel free to test the built packages here: https://copr.fedorainfracloud.org/coprs/packit/cockpit-project-cockpit-20225/build/7215820/

```sh
sudo dnf copr enable packit/cockpit-project-cockpit-20225
sudo dnf update --repo='*copr*'
```

File: pkg/lib/cockpit-components-plot.jsx [hunk 1]
```diff
@@ -288,28 +288,30 @@ export const ZoomControls = ({ plot_state }) => {
...
+        if (ref.current && size == null) {
             const rect = ref.current.getBoundingClientRect();
-            if (rect.width != size.width || rect.height != size.height)
-                setSize({ width: rect.width, height: rect.height });
+            setSize({ width: rect.width, height: rect.height });
         }
     });
     /* eslint-enable */
-    return [ref, size];
+    return [ref, size, () => setSize(null)];
```
Comment (cockpituous) [inline pkg/lib/cockpit-components-plot.jsx:302]: This added line is not executed by any test.

File: pkg/lib/cockpit-components-plot.jsx [hunk 2]
```diff
@@ -288,28 +288,30 @@ export const ZoomControls = ({ plot_state }) => {
...
-    const [measure_ref, measure_size] = useLayoutSize(36, 20);
+    const [container_ref, container_size, container_size_reset] = useLayoutSize();
+    const [measure_ref, measure_size, measure_size_reset] = useLayoutSize();
 
     useEvent(plot_state, "plot:" + plot_id);
     useEvent(plot_state, "changed");
-    useEvent(window, "resize");
+    useEvent(window, "resize", () => {
+        container_size_reset();
+        measure_size_reset();
```
Comment (cockpituous) [inline pkg/lib/cockpit-components-plot.jsx:313]: These 3 added lines are not executed by any test.

File: pkg/lib/cockpit-components-plot.jsx [hunk 3]
```diff
@@ -334,18 +339,20 @@ export const SvgPlot = ({ title, config, plot_state, plot_id, className }) => {
...
-        const m_left = Math.ceil(measure_size.width) + tick_gap + tick_length;
+        const m_left = Math.ceil(ms.width) + tick_gap + tick_length;
 
         // half of the time label so that it pops in fully formed at the far right edge
         const m_right = 30;
 
         // half a line for the top-half of the top-most y-axis label
         // plus one extra line if there is a unit or a title.
-        const m_top = (y_ticks.unit || title ? 1.5 : 0.5) * Math.ceil(measure_size.height);
+        const m_top = (y_ticks.unit || title ? 1.5 : 0.5) * Math.ceil(ms.height);
```
Comment (cockpituous) [inline pkg/lib/cockpit-components-plot.jsx:352]: This added line is not executed by any test.

**Comment by martinpitt** [comment]
@joshqou thanks for testing! I'd call that an improvement, though :grin:

**Comment by mvollmer** [comment]
@joshqou has figured it out: https://github.com/cockpit-project/cockpit/issues/20171#issuecomment-2021505658

I'll update this PR to take the rect noise into account. (Maybe rounding the size to pixels is enough.)

**Comment by mvollmer** [comment]
@joshqou, could you test again with [a4295f1](https://github.com/cockpit-project/cockpit/pull/20225/commits/a4295f1f67cf355968a7e4ee39787e061a6c3305)?

**Comment by mvollmer** [comment]
I could reproduce this locally and [a4295f1](https://github.com/cockpit-project/cockpit/pull/20225/commits/a4295f1f67cf355968a7e4ee39787e061a6c3305) fixes the "oops" for me.

**Comment by mvollmer** [comment]
> @joshqou, could you test again with [a4295f1](https://github.com/cockpit-project/cockpit/pull/20225/commits/a4295f1f67cf355968a7e4ee39787e061a6c3305)?

https://copr.fedorainfracloud.org/coprs/packit/cockpit-project-cockpit-20225/build/7220828/

It should be same repo as before, but with new packages: cockpit 313-1.20240327075912449800.pr20225.57.g14c9141cd .

```sh
sudo dnf copr enable packit/cockpit-project-cockpit-20225
sudo dnf update --repo='*copr*'
```

**Comment by joshqou** [comment]
@mvollmer Jitter seems to be fixed now. Also tested with the other `fingerprinting` flags, no issues.

**Review by martinpitt — APPROVED** [review]
Uh wow, APIs giving deliberately wrong results? Where did we turn wrong.. :sweat: 

Thanks @mvollmer and @joshqou !

**Comment by mvollmer** [comment]
Thanks everyone! This shall go to todays release!
