### PR TITLE
selinux: Inform user that reading of system mods failed

### LINKED ISSUE #12284: selinux: Infinite spinner on system modifications
System modifications never shows up properly. I just get an infinite spinner.

Screenshot_2019-07-10 SELinux - Sunny(1)

It _might_ be related to this weird error message at the top of the page:

Screenshot_2019-07-10 SELinux - Sunny(2)

### PR DESCRIPTION
**Pull request by marusak**
@garrett reported in  #12284 that `semanage` failes on his system. There is not much we can do about broken systems. However we can at least stop the spinner with message `Loading sys mods` and show that it failed. There is opened always alert message that shows more info.

@garrett can you verify that on your system it shows "Failed to load system modifications"? I've created some artificial crash but it would be great if you could ack that it also catches your problem. Thanks.

Fixes  #12284

### CODE REVIEW

**Comment by garrett** [comment]
"Loading of system modifications failed"

Screenshot_2019-07-11 SELinux - Sunny

**Comment by garrett** [comment]
It's kind of weird that it's "loading".

**Comment by andreasn** [comment]
Is there any good path for recovering from this error, or could it be pretty much anything?

**Comment by marusak** [comment]
> Is there any good path for recovering from this error, or could it be pretty much anything?

Not in general. There is a bit of logic and when the message looks like the user does not have permission the message is different. In other cases it can be anything (such as in @garrett case where we don't know what the problem is at all)

File: pkg/lib/cockpit-components-modifications.jsx [hunk 1]
```diff
@@ -141,6 +141,8 @@ export class Modifications extends React.Component {
 
     render() {
         let emptyRow = null;
+        let fail_message = this.props.permitted ? _("No System Modifications") : _("The logged in user is not permitted to view system modifications");
+        fail_message = this.props.failed ? _("Loading of system modifications failed") : fail_message;
```
Comment (martinpitt) [inline pkg/lib/cockpit-components-modifications.jsx]: Nitpick: This feels upside down -- as this.props.failed has the highest priority, it should be tested first.

Comment (marusak) [reply pkg/lib/cockpit-components-modifications.jsx]: Yes, it may seem wierd, but it is two lines and has logic that it sets up default message and if failed it overwrites it as it has priority.

Other case would be:
```
let fail_message = _("Loading of system modifications failed");
if (!this.props.failed)
     fail_message = this.props.permitted ? _("No System Modifications") : _("The logged in user is not permitted to view system modifications");
```
Which I think is a bit stranger, because you set up fail message and immediately check if it did not fail.

The proper way would be:
```
let failed_message = ""
if (this.props.failed)
    failed_message = _("Loading of system modifications failed");
else
    fail_message = this.props.permitted ? _("No System Modifications") : _("The logged in user is not permitted to view system modifications");
```
(or even better not to have the ternary operator there but move it into the condition through `if/elif/else`)
It is pointlessly long for such simple condition. But surely I can go with it if you think it is better.

Comment (martinpitt) [reply pkg/lib/cockpit-components-modifications.jsx]: Right, I was thinking of the latter, but let's not dwell on that. It's clear enough. Thanks!

**Comment by garrett** [comment]
Uhhhh... even more of All The Things™!

How do I even have two error messages here — and in different places?!

Screenshot_2019-07-11 SELinux - Sunny(2)

**Comment by andreasn** [comment]
> Error running semanage to discover system modifications.

I think this is honest and works for me. The semanage somewhat points you in the right direction of at least having something to tell support, possibly a string that allows you to search logs, but not sure that's a given.

**Comment by marusak** [comment]
> How do I even have two error messages here — and in different places?!

Ech, now I see it in the code where the second one can come from. Anyway after #12292 lands, these two error would be one above another, so that would be fine.

**Comment by marusak** [comment]
Updated to `Error running semanage to discover system modifications`.

**Comment by andreasn** [comment]
> Updated to Error running semanage to discover system modifications.

Sounds good to me!
@martinpitt I think we can merge it then.
