### PR TITLE
Fix inconsistent tooltips on system page and menu

### LINKED ISSUE #8829: inconsistent tool tips
We currently have at least three tooltip styles. On our React pages, like kdump or React Patterns:

tooltip-react

On the system page there are "broken" ones on Hardware and Machine ID, as well as the navigation menu items on the left:

tooltip machine id

This is because this just sets the `title=` attribute instead of using the [jQuery .tooltip()](https://www.w3schools.com/bootstrap/bootstrap_ref_js_tooltip.asp) method. When doing that, they look like the React ones:

tooltip-system-fixed

Finally, on the system page on the blue (i)s we have this style, which also needs to be *clicked*, not just hovered:

tooltip-system-2

We should pick one style and apply it consistently.

The React one has a nice contrast and looks a little more "distinguished". The latter (white) one is nicer for showing icons, as the grey one has poor contrast in this case:

tooltip-system-updates

(The text color is wrong, I haven't looked into that yet - but the icon is the point here)

Hint from @garrett: try `text-shadow`

### PR DESCRIPTION
**Pull request by martinpitt**
See individual commits for details.

Fixes #8829

### CODE REVIEW

**Comment by martinpitt** [comment]
See #8829 for screenshots of current master: We use three different tooltip styles on one page!

Now the "hardware info", "machine ID", time, and tuned table cells all use the standard bootstrap notifications, and the blue (i) buttons are gone:

tooltip-system-fixed

tooltip-machineid

tooltip-ntp

tooltip-tuned

Extra care is taken for the machine ID, this uses a monospaced font now; according to @garrett this is more appropriate, and it also makes maximum width calculation easier (expressed in terms of #digits).

**Comment by martinpitt** [comment]
I added another commit to fix #8827

**Comment by martinpitt** [comment]
Need to adjust the [tuned test on rhel-7-4](https://fedorapeople.org/groups/cockpit/logs/pull-8835-20180316-012929-b7f1d6db-verify-rhel-7-4/log.html#209) to the old behaviour.

**Comment by martinpitt** [comment]
tuned test fix for RHEL 7.4 pushed.

**Comment by mvollmer** [comment]
> the blue (i) buttons are gone:

Are the spinner and red (!) button still there?

File: pkg/systemd/host.js [hunk 1]
```diff
@@ -296,20 +292,10 @@ PageServer.prototype = {
...
-            var popover_html = Mustache.render(self.ntp_status_tmpl, model);
-            if (popover_html != $elt.attr('data-content')) {
-                $elt.attr("data-content", popover_html);
-                // Refresh the popover if it is open
-                if ($elt.data('bs.popover').tip().hasClass('in'))
-                    $elt.popover('show');
-            }
-
-            var icon_html = Mustache.render(self.ntp_status_icon_tmpl, model);
-            $elt.html(icon_html);
```
Comment (mvollmer) [inline pkg/systemd/host.js]: I think we should leave the spinner and error icons.

**Comment by mvollmer** [comment]
I like the blue (i) icon since it tells me that there is more to reveal here.  Otherwise tooltips are like easter eggs: I have to discover them and remember where they are.

**Comment by martinpitt** [comment]
So we could keep the blue/red (i) vs. spinner icon and attach the tooltip there, as now. It would again be a bit of a special notification case, but even with that it would be much more consistent than what we have now. @garrett, @andreasn, any opinion?

**Comment by andreasn** [comment]
I don't have a super-strong stance on (i)'s vs. hover tooltips.
The Patternfly guidelines for info-popups doesn't have a lot of details.
I agree that we need to keep the spinner and error states though.

File: pkg/systemd/host.js (hunk 1 above)
Comment (andreasn) [reply pkg/systemd/host.js]: I agree.

**Comment by mvollmer** [comment]
If you zoom with the browser (Ctrl-plus), the machine id tooltip looks like this:

tooltip-zoomed

Note that the machine id is truncated inside the tooltip.

The one pixel gap between triangle and actuall tooltip is probably caused by rounding errors somewhere.  I have this in `storage.css`, it probably is time to promote it to `lib/..`.

```
/* Layout fix for tooltip arrows.
 *
 * Sometimes when there are non-integer coordinates involved
 * somewhere, rounding seems to make it so that there is a visible one
 * pixel gap between tooltip-inner and tooltip-arrow.  We avoid that
 * gap by letting the arrow and inner parts overlap by one pixel.
 *
 * This happens within the caption of the content listing.
 */

.tooltip.top .tooltip-arrow {
    bottom: 1px;
}

.tooltip.bottom .tooltip-arrow {
    top: 1px;
}
```

**Comment by mvollmer** [comment]
Clicking on the "Hardware" link and then coming back leaves the tooltip open.  It closes when the mouse touches the link again.

File: pkg/systemd/host.css [hunk 2]
```diff
@@ -212,6 +212,11 @@ a.disabled {
     word-wrap: break-word;
 }
 
+#system_information_machine_id_row .tooltip-inner {
+    font-family: monospace;
+    max-width: 35ex;
```
Comment (mvollmer) [inline pkg/systemd/host.css]: What is the intention of this?  Can't we just let the tooltip be as large as the browser/bootstrap makes it?  Also, `ex` is for height, and `em` is for width, no?

File: pkg/realmd/operation.js [hunk 3]
```diff
@@ -413,7 +413,9 @@
     function setup() {
         var $ = jQuery;
 
-        var element = $("<a>");
+        var element = $("<span>");
+        var link = $("<a>");
+        element.append(link);
```
Comment (mvollmer) [inline pkg/realmd/operation.js]: `update_realm_privileged` still puts `disabled` on element, not on the link.

File: pkg/systemd/host.css (hunk 2 above)
Comment (martinpitt) [reply pkg/systemd/host.css]: The intention was to make this wide enough to fit the 33 characters of a machine id. Without this, tooltips have a too narrow max width, so that the machine ID doesn't even fit on default zoom.

Indeed I should  use `em` instead of `ex`, this fixes the truncation. Thanks for spotting!

File: pkg/realmd/operation.js (hunk 3 above)
Comment (martinpitt) [reply pkg/realmd/operation.js]: `update_privileged()` itself needs to be modified for that, but fortunately all other usages of this involve buttons (where notifications work on disabled buttons). Fixed locally.

**Comment by martinpitt** [comment]
> Clicking on the "Hardware" link and then coming back leaves the tooltip open. It closes when the mouse touches the link again.

Fixed.

> Note that the machine id is truncated inside the tooltip.

I moved the css fix to pkg/lib/tooltip.css in a new commit. There it's automaticaly being used for the `Tooltip` react component (thus on the storage, packagekit, and other pages). I then adjusted the existing commit to slurp in tooltip.css.

This should cover all your findings, thanks @mvollmer! Can you PTAL?

File: pkg/systemd/host.css (hunk 2 above)
Comment (mvollmer) [reply pkg/systemd/host.css]: > Without this, tooltips have a too narrow max width

Ah, so this overrides an existing style, makes sense.

**Comment by mvollmer** [comment]
> fixed all of the issues you found, thanks!

Thanks!

**Comment by martinpitt** [comment]
> Why is the time sync notification below?

I don't know, I'm afraid. I kept the existing positioning. Note that having it on the side might not work well with the single-column layout of mobile mode/narrow windows?

**Comment by garrett** [comment]
Yeah, that's probably true about mobile mode.

What about on top instead of below? With the tooltip below, it makes it difficult to scan downward while using the mouse. (It's basically covering up the next item.)

**Comment by garrett** [comment]
Oops. Trying to retrigger the review thing in GitHub is a bit odd.
