### PR TITLE
firewall: Remove the name field from the AddServices dialog

### LINKED ISSUE #12849: Firewalld: add custom ports, leads to unpredictable names and persistent data, inconsistecy with firewallcmd
I creted custom port to network firewall via cockpit: 
with name: ``random_name``
tcp port: 22
udp port: 55

it is properly created and displayed in cockpit.

But:
1. **firewallcmd inconsitency** command ``# firewall-cmd --list-services`` shows
```
amqp cockpit custom--ssh-isi-gl dhcpv6-client ssh
```
where ``custom--ssh-isi-gl`` is name of ``random_name`` service

the name is used not the proper one bug name of generated file: 
```
# cat /etc/firewalld/services/custom--ssh-isi-gl.xml 
<?xml version="1.0" encoding="utf-8"?>
<service>
  <short>random_name</short>
  <port port="22" protocol="tcp"/>
  <port port="55" protocol="udp"/>
</service>
```
what leads to incompatibilty of names via cmd line tool and cockpit
probably solution is to generate also name of file, or set some attribute there, to not use file name, but some name defined in XML

2. I'm **able to use same name** for creting new ports with another number (eg tcp 33, udp 55), it leads that I have same name, what is confusing

3. I'm **not able to create new port filter with another name**: because file name will be same:
leads to erros, because this short name is not unique identificator: 
```
Failed to add service

Error message: org.fedoraproject.FirewallD1.Exception: NAME_CONFLICT: new_service(): 'custom--ssh-isi-gl' 
```

4. last one is more less RFE: when I' create custom ports, this is permanently stored, unable to anyhow to **remove** it, I can add it via add service dialog and search for this newly created. So that unable to revert when I've create something by mistake and previous errors causes to misuse of same firewall service name

### PR DESCRIPTION
**Pull request by Gundersanne**
We switched over to using ids for presentation for both services and
zones. So instead of a custom name, allow setting of a custom id.

Fixes #12849 partially

----
image

image

image

### CODE REVIEW

File: pkg/networkmanager/firewall.jsx [hunk 1]
```diff
@@ -576,9 +560,9 @@ class AddServicesModal extends React.Component {
                                            placeholder={_("Example: 88,2019,nfs,rsync")} />
                                     <output className="has-error" htmlFor="udp-ports">{this.state.udp_error}</output>
 
-                                    <label className="control-label" htmlFor="service-name">Name</label>
-                                    <input id="service-name" className="form-control" type="text" onChange={this.setName}
-                                           placeholder={_("(Optional)")} value={this.state.custom_name} />
+                                    <label className="control-label" htmlFor="service-name">Id</label>
```
Comment (martinpitt) [inline pkg/networkmanager/firewall.jsx]: Just like the old "Name", the "Id" string should be translatable.

File: pkg/networkmanager/firewall.jsx [hunk 2]
```diff
@@ -408,60 +389,63 @@ class AddServicesModal extends React.Component {
...
-                return;
-            let ports;
-            if (port.indexOf("-") > -1) {
-                ports = port.split("-");
-                if (ports.length != 2) {
-                    error = _("Invalid range");
+        const event_value = event.target.value;
+        const event_id = event.target.id;
+
+        this.setState(oldState => {
```
Comment (martinpitt) [inline pkg/networkmanager/firewall.jsx]: Just OOI, what is the benefit of having a functional setState() here? (I'm not saying it's wrong/bad, I'm just not aware of  its advantage)

File: pkg/networkmanager/firewall.jsx [hunk 3]
```diff
@@ -408,60 +389,63 @@ class AddServicesModal extends React.Component {
...
+            const ports = event_value.split(',');
+            ports.forEach(function(port) {
```
Comment (martinpitt) [inline pkg/networkmanager/firewall.jsx]: Could this use an Arrow, and avoid the `self = this` dance?

File: pkg/networkmanager/firewall.jsx (hunk 2 above)
Comment (Gundersanne) [reply pkg/networkmanager/firewall.jsx]: Well the new state is based on the old state. And I thought to avoid Object.assign side-effects you have to use the functional setState.
