### PR TITLE
ssh: Fix parsing of IPv6 addresses

### LINKED ISSUE #9612: Adding IPv6 machine
Hi,

how do i add a machine that is only available through ipv6? i simply added the ip adress in backets in the json file in /etc/cockpit/machines.d/, but it isnt working. The machine from which iam trying to connect is able to connect through ssh ("ssh -6 [IP] -p PORT", also without the -6 option it works) to the machine, but cockpit is not able to do so. 

BR,
Blubbsy

### PR DESCRIPTION
**Pull request by martinpitt**
The previous host/port parsing misinterpreted IPv6 addresses: "::1"
ended up as host ":" with port 1, and "[::1]:22" as host "[::1]" (which
libssh can't parse and interprets as name) with port 22. 

Replace this with a regular expression which handles all user/host/port
formats correctly. Thanks to Allison Karlitskaya for this approach!

Add unit test for an IPv6 address. Due to mock-sshd always using a
random port, this can't test default port handling, thus also add an
integration test which covers all combinations of host name/IPv4/IPv6
address and port specification.

Fixes #9612

### CODE REVIEW

**Comment by martinpitt** [comment]
Ugh, [semaphore is right](https://semaphoreci.com/cockpit-project/cockpit/branches/pull-request-14615/builds/1), fixed.

**Comment by martinpitt** [comment]
Semaphore failure:

    (mock-sshd:19252): CRITICAL **: 06:08:05.876: couldn't listen on socket: Binding to ::1:0: Cannot assign requested address

I don't get that in my local or VM environment, that needs a deeper look. Looks like the default port handling isn't done consistently.

File: src/ssh/cockpitsshrelay.c [hunk 1]
```diff
@@ -1320,61 +1320,46 @@ send_auth_reply (CockpitSshData *data,
...
-  if (!user_arg || user_arg[0] == '\0')
-    user_arg = (gchar *) g_get_user_name ();
-
-  host_arg = g_strndup (host + host_offset, host_length);
-  *hostname = g_strdup (host_arg);
-  *username = g_strdup (user_arg);
-
-  g_free (host_arg);
-  g_free (user_arg);
+  address = G_NETWORK_ADDRESS (g_network_address_parse (host, 0, &error));
```
Comment (allisonkarlitskaya) [inline src/ssh/cockpitsshrelay.c:1351]: Can you use a static (C-style) cast here?  It would make me happier for two silly reasons :)

File: src/ssh/cockpitsshrelay.c [hunk 2]
```diff
@@ -1320,61 +1320,46 @@ send_auth_reply (CockpitSshData *data,
...
+  if (address)
+    {
+      *hostname = g_strdup (g_network_address_get_hostname (address));
```
Comment (allisonkarlitskaya) [inline src/ssh/cockpitsshrelay.c:1354]: Shame that there appears to be nowhere a function that will split this out without creating a GObject in the process...

It's a particularly awkward fit with the way we use `default_port` here...

**Comment by martinpitt** [comment]
[that failure](https://logs-https-cockpit.apps.ci.centos.org/logs/pull-14615-20200914-055652-69de9759-debian-testing/log.html#292) is the old "too quick logout after login" test race. I think I have a fix for that.

I can reproduce the unit test failure in semaphore. Unfortunately the container does not have `ip` or `ifconfig` installed, but /proc/net/if_inet6 is empty, and I get similar errors with ssh:
```
builder@8f4778ed203c:/tmp/source$ ssh ::1
ssh: connect to host ::1 port 22: Cannot assign requested address
builder@8f4778ed203c:/tmp/source$ ssh localhost
ssh: connect to host localhost port 22: Cannot assign requested address
builder@8f4778ed203c:/tmp/source$ ssh 127.0.0.1
ssh: connect to host 127.0.0.1 port 22: Connection refused
```

However, there does seem to be some minimal support:
```
$ cat /proc/net/ipv6_route
00000000000000000000000000000000 00 00000000000000000000000000000000 00 00000000000000000000000000000000 ffffffff 00000001 0000000f 00200200       lo
00000000000000000000000000000000 00 00000000000000000000000000000000 00 00000000000000000000000000000000 ffffffff 00000001 0000000f 00200200       lo
```

**Review by allisonkarlitskaya — CHANGES_REQUESTED** [review]

**Comment by allisonkarlitskaya** [comment]
I'll just leave this here...

```
#include <glib.h>

int
main (int argc, char **argv)
{
  GError *error = NULL;
  GRegex *regex = g_regex_new ("^"
                                 "(?:(.+)@)?"         /* optional username */
                                 "(?|"                /* one of... */
                                   "\\[([^]@]+)\\]"     /* hostname in square brackets, no @ */
                                 "|"                  /* or */
                                   "([^@:]+)"           /* hostname with no : or @ */
                                 ")"                  /* . */
                                 "(?::([0-9]+))?"     /* optional port _number_ */
                               "$",
                               0, 0, &error);
  g_assert_no_error (error);   
  
  g_autoptr(GMatchInfo) info = NULL;

  if (g_regex_match (regex, argv[1], 0, &info))
    {
      g_autofree gchar *user = g_match_info_fetch (info, 1);
      g_autofree gchar *host = g_match_info_fetch (info, 2);
      g_autofree gchar *port = g_match_info_fetch (info, 3);
      
      g_print ("parsed user '%s' host '%s' port '%s'\n", user, host, port);

      return 0;
    } 
  else
    {
      g_printerr ("failed\n");

      return 1;
    }
} 
```

File: src/ssh/cockpitsshrelay.c [hunk 3]
```diff
@@ -1320,61 +1320,46 @@ send_auth_reply (CockpitSshData *data,
...
-
-  gsize host_offset = 0;
-  gsize host_length = strlen (host);
+  gchar *user_end = NULL;
+  g_autoptr(GError) error = NULL;
+  g_autoptr(GNetworkAddress) address = NULL;
 
-  tmp = strrchr (host, '@');
-  if (tmp)
+  user_end = strrchr (host, '@');
```
[the remark this answers is not in the document]
Comment (martinpitt) [reply src/ssh/cockpitsshrelay.c:1333]: I don't see the benefit of `g_strsplit()`, it only makes things worse as you then have to handle an array. We need to make up our mind whether `@` is supported in user names or host names, and we did that years ago: with strrchr(), we support @ in user names.

File: src/ssh/cockpitsshrelay.c (hunk 2 above)
Comment (martinpitt) [reply src/ssh/cockpitsshrelay.c:1354]: That's right, we need to differentiate between "unset port" (to use ssh config) vs. "explicitly set port 22", so I need to keep the default as 0, just like the old code did. I didn't find a better method to parse all the corner cases, and the code below is exactly the type which I wouldn't want to replicate :-)

File: src/ssh/cockpitsshrelay.c [hunk 4]
```diff
@@ -1320,61 +1320,46 @@ send_auth_reply (CockpitSshData *data,
...
-  gchar *user_arg = NULL;
-  gchar *host_arg = NULL;
-  gchar *tmp = NULL;
-  gchar *end = NULL;
-
-  guint64 tmp_num;
-
-  gsize host_offset = 0;
-  gsize host_length = strlen (host);
+  gchar *user_end = NULL;
```
[the remark this answers is not in the document]
Comment (martinpitt) [reply src/ssh/cockpitsshrelay.c:1329]: Fixed.

File: src/ssh/cockpitsshrelay.c (hunk 1 above)
Comment (martinpitt) [reply src/ssh/cockpitsshrelay.c]: Done. OOI, why? The dynamic glib ones are safer and fail much more usefully, and this code isn't at all performance critical.

**Comment by martinpitt** [comment]
I fixed the semaphore failure (argh @ docker), and addressed some of your review concerns.

File: src/ssh/cockpitsshrelay.c (hunk 3 above)
[the remark this answers is not in the document]
Comment (allisonkarlitskaya) [reply src/ssh/cockpitsshrelay.c:1333]: OK.

File: src/ssh/cockpitsshrelay.c (hunk 1 above)
Comment (allisonkarlitskaya) [reply src/ssh/cockpitsshrelay.c]: Basically, the fancy cast has no value here (since it's a constructor and we know exactly what type we're getting out of it) and because I always forget if we're allowed to put NULL through a GLib cast or not :rofl:

**Review by allisonkarlitskaya — DISMISSED** [review]
Thanks!

ps: fwiw, I think the regexp approach isn't bad.

**Comment by martinpitt** [comment]
@allisonkarlitskaya : I updated this to the regexp approach. It's 18 more code lines, but overall more flexible and tailored to the SSH destination format. Having a consistent way to parse the entire thing convinced me in the end. Thanks!

**Comment by martinpitt** [comment]
@allisonkarlitskaya : oh no -- that doesn't work. It doesn't accept hosts like "::1". The unit test doesn't catch that, but the integratin tests (and my manual test) do. That is a valid address that's the host name, not the port. The first "either/or" influences whether or not the last part is a port number, i.e. I think the port number needs to be folded into the alternative.

**Comment by martinpitt** [comment]
I updated the RE to distinguish the three cases, and it seems to work now.

File: src/ssh/cockpitsshrelay.c [hunk 5]
```diff
@@ -1320,61 +1320,67 @@ send_auth_reply (CockpitSshData *data,
...
+  g_autoptr (GRegex) regex = g_regex_new ("^"
+         "(?:(.+)@)?"         /* optional username */
+         "(?|"                /* one of... */
+           "\\[([^]@]+)\\]"     /* hostname in square brackets, no @ */
+           "(?::([0-9]+))?"     /* optional port number */
+         "|"                  /* or */
+           "([^@:]+)"           /* hostname with no : or @ */
+           "(?::([0-9]+))?"     /* optional port number */
+         "|"                  /* or */
+           "([^@]+)"            /* hostname with no @ but : (IPv6 address), and no port */
```
Comment (allisonkarlitskaya) [inline src/ssh/cockpitsshrelay.c:1339]: You new case will also match a string like `hostname:ssh` (because of the failure to match the non-numeric port name in the previous iteration).  These aren't supported by `ssh(1)`, but then again, neither are numeric ports.

The thing that identifies an IPv6 address is that it always has at least two colons in it.  Maybe like `([^@]*:[^@]*:[^@]*)`.  That would match addresses like `2::1` `::1` `3::4:5:6%ifname` and others, along with `::`, which is a valid IPv6 address, but nothing that we'd ever want to SSH to.

We might also be okay to stop being so careful about the `@` thing.  The initial part, being greedy, should always consume every character up to the last `@`, as I understand it... although in the case that we *don't* get a match in th second part, it may decide to backtrack and try to get more creative...

**Review by allisonkarlitskaya — CHANGES_REQUESTED** [review]

File: src/ssh/cockpitsshrelay.c (hunk 5 above)
Comment (allisonkarlitskaya) [reply src/ssh/cockpitsshrelay.c:1339]: Or as just mentioned on IRC (writing it here so we don't forget): who cares?  We're arguing about the exact way in which this should fail to handle an invalid case.  It needs to fail anyway, and it will, later, when ssh rejects the hostname with a colon in it.

Comment (martinpitt) [reply src/ssh/cockpitsshrelay.c:1339]: Curiously, this is totally working with ssh:
```
Host p:foo
    Hostname piware.de
```

Then `ssh p:foo` actually works. So I agree that it's "good enough", and we kick the error handling can down the road towards ssh. The most important thing of this RE is that it does *not* mutilate an IPv6 address by misinterpreting a component of it as port, and reliably parses a user name and port. We don't need to go through great lengths of defining what a valid host name is, as that is very fungible.

File: src/ssh/cockpitsshrelay.c [hunk 6]
```diff
@@ -1320,61 +1320,67 @@ send_auth_reply (CockpitSshData *data,
...
+
+  g_autoptr(GMatchInfo) info = NULL;
+
+  if (g_regex_match (regex, host, 0, &info))
+    {
+      g_autofree gchar *port_str = g_match_info_fetch (info, 3);
+      gchar *endptr;
+      gint64 value;
+
+      if (port_str)
```
Comment (allisonkarlitskaya) [inline src/ssh/cockpitsshrelay.c:1353]: Be careful here: you're depending on broken GLib behaviour.  This is actually documented to return the empty string, not NULL.  Please check both cases here, in case this ever gets fixed in GLib.

See https://gitlab.gnome.org/GNOME/glib/-/issues/229

File: src/ssh/cockpitsshrelay.c [hunk 7]
```diff
@@ -1320,61 +1320,67 @@ send_auth_reply (CockpitSshData *data,
...
         {
-          user_arg = g_strndup (host, tmp - host);
-          host_offset = strlen (user_arg) + 1;
-          host_length = host_length - host_offset;
+          value = g_ascii_strtoull (port_str, &endptr, 10);
+          if (port_str[0] == '\0' || *endptr != '\0' || value > G_MAXUINT16)
```
Comment (allisonkarlitskaya) [inline src/ssh/cockpitsshrelay.c:1356]: ...and remove the `port_str[0] == '\0'` check here plz.  fwiw, it's not possible for the port to be empty in the case you're probably thinking about here, because we match on `[0-9]+`.

In general, we probably need to do a little bit less error checking here, since we know that the string in question is definitely made of all digits, with no whitespace, and not negative.  The only real possible error is that it's too large...  You could almost just do `atoi()` and check the range.  On the other hand, the extra checking doesn't really hurt, either.

File: src/ssh/cockpitsshrelay.c [hunk 8]
```diff
@@ -1320,61 +1320,67 @@ send_auth_reply (CockpitSshData *data,
...
+       "$",
+       0, 0, &error);
+  g_assert_no_error (error);
+
+  g_autoptr(GMatchInfo) info = NULL;
+
+  if (g_regex_match (regex, host, 0, &info))
+    {
+      g_autofree gchar *port_str = g_match_info_fetch (info, 3);
+      gchar *endptr;
```
Comment (allisonkarlitskaya) [inline src/ssh/cockpitsshrelay.c:1350]: Pull those (`endptr`, `value`) inside the block below (optional: put them on the same line where they are first used).

**Review by allisonkarlitskaya — CHANGES_REQUESTED** [review]
Really only one thing that properly needs fixing.  Feel free to ignore the other banter :)

File: src/ssh/cockpitsshrelay.c (hunk 7 above)
Comment (martinpitt) [reply src/ssh/cockpitsshrelay.c:1356]: Good point -- I turned the endptr check into an assertion.

File: src/ssh/cockpitsshrelay.c (hunk 8 above)
Comment (martinpitt) [reply src/ssh/cockpitsshrelay.c:1350]: Done.

File: src/ssh/cockpitsshrelay.c (hunk 6 above)
Comment (martinpitt) [reply src/ssh/cockpitsshrelay.c]: Right, thanks for spotting!

File: src/ssh/cockpitsshrelay.c [hunk 9]
```diff
@@ -1320,61 +1320,67 @@ send_auth_reply (CockpitSshData *data,
...
+    {
+      g_autofree gchar *port_str = g_match_info_fetch (info, 3);
+
+      if (port_str && port_str[0] != '\0')
         {
-          user_arg = g_strndup (host, tmp - host);
-          host_offset = strlen (user_arg) + 1;
-          host_length = host_length - host_offset;
+          gchar *endptr;
+          gint64 value = g_ascii_strtoull (port_str, &endptr, 10);
```
Comment (allisonkarlitskaya) [inline src/ssh/cockpitsshrelay.c:1354]: Careful.  That returns a `guint64` and you're implicitly casting it to signed here.  You could well end up with a negative value (and the check below only checks for `value` being too large).

Also: I think it makes sense to reject 0.  0 has the special meaning here of "not specified".  It should not be possible to explicitly specify to connect to port 0 (which is both impossible, and would be interpreted as "default port" anyway).

**Review by allisonkarlitskaya — CHANGES_REQUESTED** [review]

File: src/ssh/cockpitsshrelay.c (hunk 9 above)
Comment (allisonkarlitskaya) [reply src/ssh/cockpitsshrelay.c:1354]: We could tweak the regexp to require the pattern `[1-9][0-9]*` for port number... and then we could replace the entire thing with some code like:

```
  g_autofree gchar *port_str = get_match();
  int p = atoi (port_str ?: "");
  if (0 <= p && p < 65536)
    *port = p;
  else
    complain();
```

Comment (martinpitt) [reply src/ssh/cockpitsshrelay.c:1354]: Argh, well spotted -- that was a typo, I deliberately chose strto*u*ll. I fixed it locally. I still want to look at the [brittle integration test](https://logs.cockpit-project.org/logs/pull-14615-20200915-180548-fbde9afb-debian-testing/log.html#292) -- that's an old root cause, but it bites us again here.

Comment (martinpitt) [reply src/ssh/cockpitsshrelay.c]: Nice idea! Seems to work fine locally. I pushed that, so that the tests can run again. I still want to track down that flake, though.

**Comment by martinpitt** [comment]
Oh wait -- that flaky integration test is `testBasic()`, not `testServer()` (which is touched here) -- so that's unrelated, and I'll send a separate PR about it.

File: src/ssh/cockpitsshrelay.c [hunk 10]
```diff
@@ -1320,61 +1320,61 @@ send_auth_reply (CockpitSshData *data,
...
+  g_assert_no_error (error);
+
+  g_autoptr(GMatchInfo) info = NULL;
+
+  if (g_regex_match (regex, host, 0, &info))
+    {
+      g_autofree gchar *port_str = g_match_info_fetch (info, 3);
+      /* regexp makes sure that it's a positive number, so don't need much error checking */
+      guint value = atoi (port_str ?: "");
+      if (value >= 0 && value < 65536)
```
Comment (allisonkarlitskaya) [inline src/ssh/cockpitsshrelay.c:1352]: `value` is unsigned, so it's always `>= 0`.  I did the `guint` for that reason.  You could also turn it into a `gint` (to better match the return type of `atoi()`) if you wanted, and then this extra check would make sense...

**Review by allisonkarlitskaya — APPROVED** [review]
I mean, at this point, it's probably fine...

File: src/ssh/cockpitsshrelay.c (hunk 10 above)
Comment (martinpitt) [reply src/ssh/cockpitsshrelay.c]: Argh, indeed -- tests didn't get very far yet, I just fixed it.

**Review by allisonkarlitskaya — APPROVED** [review]
It's on the bots now :) 

thanks!
