### PR TITLE
packagekit: Fix crash on security updates without CVE URLs

### LINKED ISSUE #8375: Software Updates on RHEL 7 crash with: TypeError: reduce of empty array with no initial value
I added a real RHEL 7.4 machine to Cockpit and went to Software Updates:

updates

The JS log only shows:

    TypeError: reduce of empty array with no initial value

This is with cockpit-packagekit-155-1.el7.x86_64

### PR DESCRIPTION
**Pull request by martinpitt**
If an update is marked as type "security" but has no CVE URLs,
`insertCommas()` is called on an empty list. This does not work with the
`.reduce()` function and it crashes with

    TypeError: reduce of empty array with no initial value

Fix this by checking for an empty list in `insertCommas()`.

Reproduce this in a test case with `severity="security"` and no CVE
URLs. This only works on yum, as PackageKit's apt backend does not
support severities, and the dnf backend yields wrong values
(https://bugs.freedesktop.org/show_bug.cgi?id=101070). For that, move
the backend detection from `TestAutoUpdates` to the parent `PackageCase`
class.

Fixes #8375

### CODE REVIEW

File: pkg/packagekit/updates.jsx [hunk 1]
```diff
@@ -135,6 +135,8 @@ function deduplicate(list) {
 // Insert comma strings in between elements of the list. Unlike list.join(",")
 // this does not stringify the elements, which we need to keep as JSX objects.
 function insertCommas(list) {
+    if (list.length == 0)
+        return list;
     return list.reduce((prev, cur) => [prev, ", ", cur])
```
Comment (larskarlitski) [inline pkg/packagekit/updates.jsx]: This fix works, but note that there is another weird edge case in `Array.reduce` when not passing the `initialValue` parameter: for one-element lists, it doesn't call the callback and returns the element, not a list with that one element.  MDN documentation thus suggests always passing an `initalValue`.

Comment (martinpitt) [reply pkg/packagekit/updates.jsx]: Good point. It doesn't matter here as JSX treats a single item and an one-element list the same, but for the sake of clarity I force-pushed a fix. There is no `initialValue` that actually works here, but just checking for `length <= 1` does the trick.

Comment (larskarlitski) [reply pkg/packagekit/updates.jsx]: Thanks!
