### PR TITLE
tls: add connectat() and bindat()-style wrappers

### LINKED ISSUE #13220: [tests] test-tls-server fails with non-default $TMPDIR
I'm trying to run the Cockpit's test suite (version: 208).
All pass, but `test-tls-server`:

```
test-tls-server: src/tls/socket-io.c:306: sockaddr_printf: Assertion `0 < r && r < sizeof addr->sun_path' failed.
**
ERROR:src/tls/test-server.c:227:assert_https_outcome: assertion failed (len >= 100): (-54 >= 100)
SKIP: test-tls-server Bail out! ERROR:src/tls/test-server.c:227:assert_https_outcome: assertion failed (len >= 100): (-54 >= 100)
ERROR: test-tls-server process failed: -6
```

`./test-tls-server --debug-log`

```
# random seed: R02S2e1e0d93bb70ec4f4e86bcdcead06e03
{*LOG(binary):{test-tls-server}:{R02S2e1e0d93bb70ec4f4e86bcdcead06e03}:LOG*}
1..15
{*LOG(start suite):{}:LOG*}
# Start of server tests
{*LOG(start suite):{server}:LOG*}
{*LOG(start):{/server/mixed-protocols}:LOG*}
# GLib-DEBUG: posix_spawn avoided (fd close requested) 
{*LOG(message):{GLib-DEBUG: posix_spawn avoided (fd close requested) }:LOG*}
socket-activation-helper: src/tls/socket-activation-helper.c:209: main: Assertion `res < sizeof (addr.sun_path)' failed.
test-tls-server: src/tls/socket-io.c:306: sockaddr_printf: Assertion `0 < r && r < sizeof addr->sun_path' failed.
Aborted
**
ERROR:src/tls/test-server.c:227:assert_https_outcome: assertion failed (len >= 100): (-54 >= 100)
Bail out! ERROR:src/tls/test-server.c:227:assert_https_outcome: assertion failed (len >= 100): (-54 >= 100)
{*LOG(error):{ERROR:src/tls/test-server.c:227:assert_https_outcome: assertion failed (len >= 100): (-54 >= 100)}:LOG*}
```

`gdb ./socket-activation-helper`

```
(gdb) show args
Argument list to give program being debugged when it is started is "./cockpit-ws /usr/src/tmp/server.wssock.PYN8B0/".

(gdb) p res
$22 = 110
(gdb) p sizeof(addr.sun_path)
$23 = 108
(gdb) p addr
$24 = {sun_family = 1, 
  sun_path = "/usr/src/tmp/server.wssock.PYN8B0//https@e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.s"}

(gdb) bt
#0  main (argc=<optimized out>, argv=<optimized out>)
    at src/tls/socket-activation-helper.c:209
```

OS: ALTLinux

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
This lets us remove all sockaddr_un handling from the code and avoids an
issue when the pasted-together paths overrun the (relatively small)
buffer.

Comments welcome.  Note that bindat_printf() is never used because we only bind to static example paths (ie: hardcoded key fingerprints) from the socket activation helper.

Fixes #13220

### CODE REVIEW

File: src/tls/connection.c [hunk 1]
```diff
@@ -371,12 +371,10 @@ request_dynamic_wsinstance (const Fingerprint *fingerprint)
...
 
-  sockaddr_printf (&addr, "%s/https-factory.sock", parameters.wsinstance_sockdir);
-
-  debug (CONNECTION, "  -> connecting to %s...", addr.sun_path);
-  if (connect (fd, (struct sockaddr *) &addr, sizeof addr) != 0)
+  debug (CONNECTION, "  -> connecting to https-factory.sock");
+  if (af_unix_connectat (fd, parameters.wsinstance_sockdir, "https-factory.sock") != 0)
     {
-      warn ("connect(%s) failed", addr.sun_path);
+      warn ("connect failed");
```
Comment (martinpitt) [inline src/tls/connection.c]: Please still let this say "https-factory.sock", so that in case of failure it's easier to debug (the directory is obvious from that).

File: src/tls/connection.c [hunk 2]
```diff
@@ -427,15 +424,13 @@ connection_connect_to_dynamic_wsinstance (Connection *self)
       self->certfile_fd = -1;
     }
 
-  sockaddr_printf (&addr, "%s/https@%s.sock", parameters.wsinstance_sockdir, self->fingerprint.str);
-  debug (CONNECTION, "Connecting dynamic https wsinstance %s:", addr.sun_path);
```
Comment (martinpitt) [inline src/tls/connection.c]: This could also get back with `https@%s` and showing the fingerprint?

**Comment by allisonkarlitskaya** [comment]
> Nice trick! LGTM in general (I find the `_printf()` variants a bit overkill, but why not -- your call). Just two nitpicks.

No. You're right.  I'll drop the `_printf()`

File: src/tls/connection.c (hunk 1 above)
Comment (allisonkarlitskaya) [reply src/tls/connection.c]: Done.

File: src/tls/connection.c (hunk 2 above)
Comment (allisonkarlitskaya) [reply src/tls/connection.c]: Done (but using the newly-formatted name, since I nixed the printf magic)

**Comment by martinpitt** [comment]
Oops, this breaks all the https tests

**Comment by allisonkarlitskaya** [comment]
> Oops, this breaks all the https tests

Probably unrelated :rofl:

**Comment by allisonkarlitskaya** [comment]
No but seriously, I'm a little bit alarmed that this brokenness wasn't picked up in `make check`.  Maybe we should add something there...

**Comment by allisonkarlitskaya** [comment]
Theory: systemd is removing/recreating the socket directory when it's empty, causing our fd that we `open()` at the start to become stale.

**Comment by allisonkarlitskaya** [comment]
New theory: careless programmer makes embarrassing copy-paste error. :see_no_evil:

**Comment by allisonkarlitskaya** [comment]
Btw: the reason that we don't detect this problem under `make check` is because we don't actually test the "factory" stuff at all: under the socket activation helper, the sockets are all statically there from the start and connections always succeed on the first attempt.  I consider this to be a hole in our unit testing that would be nice to address (although our integration testing clearly caught it).
