### PR TITLE
users: Fix truncated "From" in account logs

### LINKED ISSUE #21383: [Bug] Login history truncates IPv6 addresses
### Explain what happens

1. Login via an IPv6 address.
2. View Accounts->account that logged in via IPv6 address
3. Notice login history truncation.

### Version of Cockpit

329-1

### Where is the problem in Cockpit?

None

### Server operating system

None

### Server operating system version

_No response_

### What browsers are you using?

_No response_

### System log

The actual `td` information is truncated. I checked the browser console log and noticed some JavaScript mixed with Python and Shell script in `/cockpit/@localhost/users/users.js`? Why would anything like that ever be in JavaScript for this? No matter what client-side interaction is doing this is weird.

### PR DESCRIPTION
**Pull request by martinpitt**
Call `last` with `--fullnames` to avoid truncating values (like IPv6
addresses). We don't rely on a "nicely" (argh) formatted ASCII table
with fixed column widths, but parse the structure.

Flesh out TestAccounts.testAccountLogs to actually test some values on
the page. It was almost empty before. Like in the previous commit, we
can afford to hardcode the expected IPv6 "from" address.

Fixes #21383

### CODE REVIEW

File: test/verify/check-users [hunk 1]
```diff
@@ -1079,14 +1079,26 @@ class TestAccounts(testlib.MachineCase):
...
+
+        # second login: one entry from the first one
         self.login_and_go("/users#/admin")
-        b.wait_visible("#account-logs")
         # Header + one line of logins
         b.wait_js_func("ph_count_check", "#account-logs tr", 2)
+        started = b.text("#account-logs [data-label='Started']")
+        ended = b.text("#account-logs [data-label='Ended']")
+        self.assertIn(year, started)
+        self.assertIn(year, ended)
```
Comment (martinpitt) [inline test/verify/check-users:1098]: This of course assumes that this test doesn't run at precisely mightnight on new year. But if you send a PR around that time, shame on you :grin: I tried to parse the shown date with `date`, but it's a custom format which `date -d` doesn't understand, so I gave up.

File: pkg/users/account-logs-panel.jsx [hunk 2]
```diff
@@ -31,7 +31,7 @@ const _ = cockpit.gettext;
 export function AccountLogs({ name }) {
     const [logins, setLogins] = useState([]);
     useInit(() => {
-        cockpit.spawn(["last", "--time-format", "iso", "-n", 25, name], { environ: ["LC_ALL=C"] })
+        cockpit.spawn(["last", "--time-format", "iso", "-n25", "--fullnames", name], { environ: ["LC_ALL=C"] })
```
Comment (jelly) [inline pkg/users/account-logs-panel.jsx:34]: Was confused for a bit, why isn't this `-w`, but that's the same thing :) I guess for historical raisins.

File: test/verify/check-users (hunk 1 above)
Comment (jelly) [reply test/verify/check-users:1098]: With this comment it feels like "challenge accepted". But maybe more for dependabot :)

**Review by jelly — APPROVED** [review]
Thanks!

File: pkg/users/account-logs-panel.jsx (hunk 2 above)
Comment (martinpitt) [reply pkg/users/account-logs-panel.jsx:34]: I prefer long options in code for better readability. But `-w` is the same thing indeed.
