### PR TITLE
systemd: Fix spinner gap

### LINKED ISSUE #19059: No spacing between spinner and text
### Explain what happens

When clicking `Report to Fedora` the spinner has no spacing between itself and the text. Also when an error occurs and you re-click report the error is not cleared (as can be seen in `Report to ABRT Analysis`)

Easiest to reproduce by putting a `testlib.sit()` in `test/verify/check-system-journal` and run

```
TEST_SHOW_BROWSER=1 ./test/verify/check-system-journal -vst TestJournal.testAbrtSegv
```

image

### Version of Cockpit

_No response_

### Where is the problem in Cockpit?

None

### Server operating system

None

### Server operating system version

_No response_

### What browsers are you using?

_No response_

### System log

_No response_

### PR DESCRIPTION
**Pull request by tahamukhtar20**
1. a flex-gap of 0.5 rem added between the spinner and text
2. fixed the error not clearing when the report button is re-clicked, now it first becomes "Waiting to start" same as the other options before cycling through the other checks for errors.

Fixes #19059

### CODE REVIEW

File: pkg/systemd/reporting.jsx [hunk 1]
```diff
@@ -397,8 +398,26 @@ const WorkflowRow = ({ message, problemState, reportLinks, label, onReportButton
...
-                {status}
+                <div style={{
+                    display: "flex",
+                    flexDirection: "row",
+                    justifyContent: "center",
+                    alignItems: "center",
+                    width: "100%",
+                    height: "fit-content",
+                    gap: "0.5rem"
+                }}>
```
Comment (martinpitt) [inline pkg/systemd/reporting.jsx:409]: We can't/shouldn't do inline CSS, please move that to pkg/systemd/reporting.scss and use a class. HTML/JSX should just contain the structural bits.

However, this shouldn't use manual layout/css at all. Please use the [PatternFly Flex component](https://www.patternfly.org/layouts/flex) -- check `git grep -w Flex` for lots of existing examples.

Comment (tahamukhtar20) [reply pkg/systemd/reporting.jsx:409]: Sorry for any inconveniences, I'll get to it. Thanks for the review

**Comment by tahamukhtar20** [comment]
@martinpitt please review now, I believe I've fixed the issue. Thanks

**Comment by martinpitt** [comment]
@tahamukhtar20 Just to set expectations: The whole team is on end-of-year holiday until Jan 2. I'll test your change when I'll find a few mins in between the family events :grin: but there's at least nothing obviously wrong. Thank you!

**Comment by martinpitt** [comment]
> fixed the error not clearing when the report button is re-clicked, now it first becomes "Waiting to start" same as the other options before cycling through the other checks for errors.

Does it actually do that? I don't see any code change related to that, just the spinner gap.

**Comment by tahamukhtar20** [comment]
> @tahamukhtar20 Just to set expectations: The whole team is on end-of-year holiday until Jan 2. I'll test your change when I'll find a few mins in between the family events 😁 but there's at least nothing obviously wrong. Thank you!

I understand, and I believe your family should come first, so happy holidays, please enjoy your time thanks!

**Comment by tahamukhtar20** [comment]
> > fixed the error not clearing when the report button is re-clicked, now it first becomes "Waiting to start" same as the other options before cycling through the other checks for errors.
> 
> Does it actually do that? I don't see any code change related to that, just the spinner gap.

From what I understood about that issue was that when the error button was clicked the error message didn't change and it felt as if it was stuck on that same message and was not updating whatsoever, so I looked at the code of the error display below, it had one line above it which reset the error message before assigning a new one, you can find the line I added in the same file please go through the changes again, if you think that this was not the intended issue, please do elaborate and I'll try to the best of my efforts to fix the intended issue

I'll drop a screenshot showing the changes I made =>

The change I meant

**Comment by tahamukhtar20** [comment]
@martinpitt please review this and tell if there is any issue with this or if I need to change anything in this

**Review by martinpitt — APPROVED** [review]
Thanks a lot, and sorry for the delay! This works well. The RPMs failed to build in your push and the logs are gone by now, so I rebased your PR against current main, squashed the commits, and cleaned up the message a bit. But no code changes.
