### PR TITLE
systemd: Serialize reload and unit start/stop on Service details page

### LINKED ISSUE #17768: TestServices.testLogs consistently fails on ubuntu-stable
Found in PR #17759, but this is complicated/subtle enough to collect information in a new issue.

This testLogs failure gets hidden by auto-retries, e.g. [here](https://cockpit-logs.us-east-1.linodeobjects.com/pull-3880-20220920-082726-859a7543-ubuntu-stable-cockpit-project-cockpit/log.html) and [here](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17758-20220922-125547-149d7b9f-ubuntu-stable/log.html). 

Reproducer:
```
TEST_OS=ubuntu-stable test/verify/check-system-services -tv TestServices.testLogs
```

### PR DESCRIPTION
**Pull request by martinpitt**
The On/Off button previously ran EnableUnitFiles() and Start() in parallel, with the Reload() happening right after Start(). This triggers race conditions in journalling, where the first few messages of the service start would get eaten by the reload.

Serialize these actions similar to what pkg/lib/service.js does. This is also what `systemctl enable --now` does.

Fixes #17768

### CODE REVIEW

File: pkg/systemd/services/service-details.jsx [hunk 1]
```diff
@@ -291,15 +291,21 @@ export class ServiceDetails extends React.Component {
 
     onOnOffSwitch() {
         if (this.props.unit.UnitFileState === "enabled") {
-            this.unitFileAction("DisableUnitFiles", undefined);
+            let promise;
             if (this.props.unit.ActiveState === "active" || this.props.unit.ActiveState === "activating")
-                this.unitAction("StopUnit");
-            if (this.props.unit.ActiveState === "failed")
-                this.unitAction("ResetFailedUnit", []);
+                promise = this.unitAction("StopUnit");
```
Comment (cockpituous) [inline pkg/systemd/services/service-details.jsx:296]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17999-20221206-150957-1a6e9961-fedora-36-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/services/service-details.jsx [hunk 2]
```diff
@@ -291,15 +291,21 @@
...
+            else if (this.props.unit.ActiveState === "failed")
+                promise = this.unitAction("ResetFailedUnit", []);
```
Comment (cockpituous) [inline pkg/systemd/services/service-details.jsx:298]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17999-20221206-150957-1a6e9961-fedora-36-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/services/service-details.jsx [hunk 3]
```diff
@@ -291,15 +291,21 @@
...
+            else
+                promise = Promise.resolve();
```
Comment (cockpituous) [inline pkg/systemd/services/service-details.jsx:300]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-17999-20221206-150957-1a6e9961-fedora-36-devel//Coverage/lcov/github-pr.diff.gcov.html)
