### PR TITLE
ws: Fix origin validation for IPv6 addresses

### LINKED ISSUE #22333: cockpit-ws: received request from bad Origin: https://[::1]:9090
### Explain what happens

1. Attempt to access the Cockpit UI from a local system using the IPv6 loopback address ( ::1 / URL format - [::1] ) which is a valid URL
2. After logging in an error instructing the user to check `journalctl -u cockpit` is displayed and not the normal screen.

The UI works fine if the name `localhost`, or the IPv4 loopback is used.

### Version of Cockpit

344 (Fedora)

### Where is the problem in Cockpit?

None

### Server operating system

None

### Server operating system version

Fedora Workstation 42

### What browsers are you using?

GNOME Web

### System log

https://issues.redhat.com/browse/RHEL-137586

### PR DESCRIPTION
**Pull request by martinpitt**
The websocket server validates that the Origin header matches the
request protocol and host using fnmatch(). However, that treats square
brackets [ and ] as character classes, so IPv6 addresses like
[::1]:9090 failed validation.

Fix this by escaping these characters.

Fixes #22333
https://issues.redhat.com/browse/RHEL-137586

### CODE REVIEW

**Comment by martinpitt** [comment]
Rebased to get rawhide green, and I fixed the two commit message typos.

**Comment by martinpitt** [comment]
@allisonkarlitskaya Fair enough. I didn't quite like it either, I just found it inelegant to escape the host string in cockpit_web_service_new(). But anyway, this is the simple and safe approach, so I changed it to that.

> We could do something silly like setting the first item to the literal string "=" and putting the computed origin into the second item

If we assume that the headers object is not fully trustworthy, then I'd rather avoid these games at all. I mean, I'd really want *all* of this silly web server code go away at some point :sweat_smile:

File: src/ws/cockpitwebservice.c [hunk 1]
```diff
@@ -1301,6 +1301,18 @@ cockpit_web_service_new (CockpitCreds *creds,
   return self;
 }
 
+/* Escape a host string for fnmatch.
+ * IPv6 addresses look like [::1]:9090 which fnmatch treats as character classes.
+ */
+static gchar *
+escape_host_for_fnmatch (const gchar *host)
```
Comment (allisonkarlitskaya) [inline src/ws/cockpitwebservice.c:1308]: Sorry to nag, but can we make this a bit more robust?  Like a proper loop that escapes all of the relevant characters (`[`, `]`, `*`, `?` and `\` itself)?

Comment (martinpitt) [reply src/ws/cockpitwebservice.c:1308]: Hm, right -- I had this thing in my head that `*` and `?` are legit, but they are only so in cockpit.conf -- for our internal defaults they are not. Changed into a loop, thanks for spotting!

File: src/ws/cockpitwebservice.c [hunk 2]
```diff
@@ -1301,6 +1301,25 @@ cockpit_web_service_new (CockpitCreds *creds,
...
+{
+  GString *escaped = g_string_new (host);
+  /* Backslash must be escaped first to avoid double-escaping */
+  const char *escape_chars[] = {"\\", "[", "]", "?", "*", NULL};
+
+  for (const char **c = escape_chars; *c; c++)
+    {
+      const char escaped_char[3] = {'\\', (*c)[0], '\0'};
+      g_string_replace (escaped, *c, escaped_char, 0);
+    }
```
Comment (allisonkarlitskaya) [inline src/ws/cockpitwebservice.c]: I was thinking more like

```c
escaped = g_string_new(NULL);
for (int i = 0; host[i]; i++)
  {
    if (chrstr (host[i], "[]?*\\"))
      g_string_append_c (escaped, '\\');
    g_string_append_c (escaped, host[i]);
  }
```

or whatever...

Comment (martinpitt) [reply src/ws/cockpitwebservice.c]: Oh, that's nicer, thanks! Done.

**Comment by martinpitt** [comment]
[testTls message again](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-22812-c1d9c90e-20260130-115820-debian-trixie-networking/log.html) ! I'll brood over this again.

File: src/ws/cockpitwebservice.c [hunk 3]
```diff
@@ -1301,6 +1301,23 @@ cockpit_web_service_new (CockpitCreds *creds,
   return self;
 }
 
+/* Escape a host string for fnmatch.
+ * IPv6 addresses look like [::1]:9090 which fnmatch treats as character classes.
+ */
+static gchar *
+escape_host_for_fnmatch (const gchar *host)
+{
+  GString* escaped = g_string_new(NULL);
```
Comment (allisonkarlitskaya) [inline src/ws/cockpitwebservice.c:1310]: lol `*` in the wrong place

**Comment by martinpitt** [comment]
[testTls message again](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-22812-c1d9c90e-20260130-115820-debian-trixie-networking/log.html) ! It's on the [weather report](https://ci-weather-cockpit.apps.ocp.cloud.ci.centos.org/tests.html?repo=cockpit-project%2Fcockpit&days=7), too. But I can't for the life of me see why -- testTls does *not* start cockpit-ws directly and talk to it with https. Some tests do that, but not this one.
