### PR TITLE
storage: Do not open dialog for non-authorized user

### LINKED ISSUE #11058: User can change RAID settings without permission.
Cockpit version: 164
OS: Ubuntu 18.04 LTS Server
Page: Storage

When I hover over the add RAID storage option on an account without administrator permissions, it says I don't have permission. When I click it however it loads the menu. 

Steps to reproduce

1. Navigate to storage page with a user account with no administrator permissions.
2. Try to click on the add RAID + icon.
3. It will load, even though it shouldn't.

Saying I don't have permission.
image

It loads the next screen anyway.
image

### PR DESCRIPTION
**Pull request by marusak**
Fixes #11058

### CODE REVIEW

**Comment by marusak** [comment]
@KKoukiou that makes sense. However there are a few classes (StorageButton, StorageLink, StorageMultiAction, StorageOnOff), which all use function `checked` as wrapper for their `OnClick` events. My thinking was to cover all of these in a minimal way. However the truth is that I was not able to reproduce this unwanted behavior with neither StorageLink not StorageOnOff (did not try MultiAction).

Would it be better to just add `disabled` to StorageButton and not check it in JS then?

**Comment by KKoukiou** [comment]
I see, yes I would add a disabled attribute to the buttons.
I think it's safe to add to all of them like this,
``` js
                                 <button id={this.props.id}
+                                            disabled={!permission.allowed}
...
```

**Comment by KKoukiou** [comment]
And ideally can we have a test for this :) ?

**Comment by mvollmer** [comment]
So the fundamental problem is that we get a onclick event also for disabled buttons?  This is likely a regression caused by the conversion to React.  We probably need to both add the "disabled" class and the "disabled" attribute.

File: pkg/storaged/storage-controls.jsx [hunk 1]
```diff
@@ -93,6 +93,8 @@ function checked(callback) {
         // only consider primary mouse button
         if (!event || event.button !== 0)
             return;
+        if (!permission.allowed)
```
Comment (mvollmer) [inline pkg/storaged/storage-controls.jsx]: Controls can be disabled for other reasons than `!permission.allowed` so this would need to check whether the element is disabled or not.

**Comment by mvollmer** [comment]
> I was not able to reproduce this unwanted behavior

I got it only with Chrome, and you have to click on the plus symbol itself.  Clicking within the button but outside the plus does not open the dialog. With Firefox, I wasn't able to open the dialog.

**Comment by marusak** [comment]
@KKoukiou Updated. Now I am thinking about test, but I am not sure how it should work - as we want to make sure, that no dialog gets opened. Only idea I have is direct waiting some time and check there is no dialog, but I guess it is not ideal test case, right?

@mvollmer wrote:
>So the fundamental problem is that we get a onclick event also for disabled buttons? This is likely a regression caused by the conversion to React. We probably need to both add the "disabled" class and the "disabled" attribute.

Yes, that is the problem. More specific, it happens only if button element contains other element as child (such as span element for icons) and not only text. `disabled` class is already present. Now this PR adds `disabled` attribute.

**Comment by KKoukiou** [comment]
@marusak Just check that the button is disabled, you don't need to check that clicking it will cause no effect.

**Comment by marusak** [comment]
@KKoukiou test added.

**Comment by KKoukiou** [comment]
@mvollmer do you want to review all well? This look great but since I am not frequent contributor for this page I am afraid to hit the button :)

File: pkg/storaged/storage-controls.jsx [hunk 2]
```diff
@@ -117,7 +117,8 @@ export class StorageButton extends React.Component {
                             content={(excuse) => (
                                 <button id={this.props.id}
                                             onClick={checked(this.props.onClick)}
-                                            className={classes + (excuse ? " disabled" : "")}>
+                                            className={classes + (excuse ? " disabled" : "")}
+                                            disabled={excuse}>
```
Comment (martinpitt) [inline pkg/storaged/storage-controls.jsx]: I suppose `excuse` is a string. In this case, this  should be `disabled={!!excuse}` to be a boolean value?

**Comment by mvollmer** [comment]
Tested with Chrome and works as expected.

File: pkg/storaged/storage-controls.jsx (hunk 2 above)
Comment (KKoukiou) [reply pkg/storaged/storage-controls.jsx]: In es6 at least the empty strings are falsy whilst every string of lengh > 0 is truthy. So this should work.
