### PR TITLE
pkg/lib: make the upload-helper WebKit-compatible

### LINKED ISSUE #20615: uploads not working in WebKit
I thought it might be fun to test uploading from localhost to localhost.  I was surprised to get a file chooser dialog, and access to my entire home directory!  Yay for xdg portal, I guess...

This was less exciting, though:

image

_Originally posted by @allisonkarlitskaya in https://github.com/cockpit-project/cockpit/issues/20614#issuecomment-2175523464_

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
Our use of `{ mode: 'byob' }` gets us in trouble on WebKit.  We see "ReadableStreamBYOBReader needs a ReadableByteStreamController" on any attempt to upload a file.  This affects:

 - Cockpit Client
 - Epiphany
 - Safari on macOS and iOS

And indeed, https://caniuse.com/mdn-api_readablebytestreamcontroller agrees that we can't use this yet.

We also can't simply change to the default reader: the reason we chose the BYOB reader is that it let us control the block size that was returned.  The default reader returns large blocks (on the order of 2MB) which we can't send over the websocket, because of limitations in `cockpit-ws`:

```
server is trying to frame of size 524294 or greater, but max supported size is 128KiB
Received extremely large WebSocket data from the server
```

It seems we can't get around the fact that we're going to have to do some slicing here.  Let's try to use the BYOB API if possible, and fall back to an adaptor if we can't.

Fixes #20615

### CODE REVIEW

**Comment by allisonkarlitskaya** [comment]
This code isn't the prettiest thing in the world... suggestions for improvements are welcome.

File: pkg/lib/cockpit-upload-helper.ts [hunk 1]
```diff
@@ -39,6 +39,52 @@ class Waiter {
...
+    }
+
+    async read(size: number) {
+        return await this.reader.read(new Uint8Array(size));
+    }
+}
+
+class DefaultReader {
+    reader: ReadableStreamDefaultReader<Uint8Array>;
+    buffer: Uint8Array | null = null;
```
Comment (cockpituous) [inline pkg/lib/cockpit-upload-helper.ts:58]: These 2 added lines are not executed by any test.

File: pkg/lib/cockpit-upload-helper.ts [hunk 2]
```diff
@@ -39,6 +39,52 @@ class Waiter {
...
+
+    constructor(reader: ReadableStreamDefaultReader<Uint8Array>) {
+        this.reader = reader;
```
Comment (cockpituous) [inline pkg/lib/cockpit-upload-helper.ts:61]: These 2 added lines are not executed by any test.

File: pkg/lib/cockpit-upload-helper.ts [hunk 3]
```diff
@@ -39,6 +39,52 @@ class Waiter {
...
+    }
+
+    async read(size: number) {
```
Comment (cockpituous) [inline pkg/lib/cockpit-upload-helper.ts:64]: This added line is not executed by any test.

File: pkg/lib/cockpit-upload-helper.ts [hunk 4]
```diff
@@ -39,6 +39,52 @@ class Waiter {
...
+        // No buffered data?  Try a read.
+        if (!this.buffer) {
+            const { done, value } = await this.reader.read();
+            if (done) {
+                return { done, value };
```
Comment (cockpituous) [inline pkg/lib/cockpit-upload-helper.ts:69]: These 4 added lines are not executed by any test.

File: pkg/lib/cockpit-upload-helper.ts [hunk 5]
```diff
@@ -39,6 +39,52 @@ class Waiter {
...
+            } else {
+                this.buffer = value;
```
Comment (cockpituous) [inline pkg/lib/cockpit-upload-helper.ts:71]: This added line is not executed by any test.

File: pkg/lib/cockpit-upload-helper.ts [hunk 6]
```diff
@@ -39,6 +39,52 @@ class Waiter {
...
+            }
+        }
+
+        // Return the buffered data: if length < size, return it all, else return a slice
+        if (this.buffer.length < size) {
+            const value = this.buffer;
+            this.buffer = null;
+            return { done: false, value };
```
Comment (cockpituous) [inline pkg/lib/cockpit-upload-helper.ts:79]: These 4 added lines are not executed by any test.

File: pkg/lib/cockpit-upload-helper.ts [hunk 7]
```diff
@@ -39,6 +39,52 @@ class Waiter {
...
+        } else {
+            const value = this.buffer.slice(0, size);
+            this.buffer = this.buffer.slice(size);
+            return { done: false, value };
```
Comment (cockpituous) [inline pkg/lib/cockpit-upload-helper.ts:83]: These 3 added lines are not executed by any test.

File: pkg/lib/cockpit-upload-helper.ts [hunk 8]
```diff
@@ -93,7 +139,13 @@ export async function upload(
 
     try {
         debug('starting file send', contents);
-        const reader = contents.stream().getReader({ mode: 'byob' }); // byob to choose the block size
+        let reader;
+        try {
+            reader = new ByobReader(contents.stream().getReader({ mode: 'byob' }));
+        } catch {
+            reader = new DefaultReader(contents.stream().getReader());
```
Comment (cockpituous) [inline pkg/lib/cockpit-upload-helper.ts:146]: These 2 added lines are not executed by any test.

File: pkg/lib/cockpit-upload-helper.ts [hunk 9]
```diff
@@ -93,7 +139,13 @@ export async function upload(
 
     try {
         debug('starting file send', contents);
-        const reader = contents.stream().getReader({ mode: 'byob' }); // byob to choose the block size
+        let reader;
+        try {
+            reader = new ByobReader(contents.stream().getReader({ mode: 'byob' }));
+        } catch {
```
Comment (martinpitt) [inline pkg/lib/cockpit-upload-helper.ts:145]: This is a very wide catch -- would be good to check the error, and also add a comment pointing to caniuse -- we want to remove this in a year or two?

**Review by martinpitt — CHANGES_REQUESTED** [review]
Indeed it's a rather intrusive workaround (the entirely new ByobReader class), but due to the different signature of the read() method I don't see a much better approach either, so that's fine. I'd just like to make it a bit more robust to guard against incorrectly using it (i.e. catching exceptions which are unrelated to the API not existing).

**Review by jelly — COMMENTED** [review]
The commit message confuses me.

It mentions ReadableBytesStreamController is needed by ReadableStreamBYOBReader, but it seems to me that Safari/Webkit has a REadableBytesStreamController?

https://bugs.webkit.org/show_bug.cgi?id=164014
https://bugs.webkit.org/show_bug.cgi?id=167786
https://developer.apple.com/documentation/webkitjs/readablebytestreamcontroller

Should we create an issue for webkit that support is missing?

Because the bugtracker talks about bugs regarding StreamController's and they have tests for construct-byob-request.any.worker.html

https://bugs.webkit.org/show_bug.cgi?id=245994

File: pkg/lib/cockpit-upload-helper.ts (hunk 9 above)
Comment (jelly) [reply pkg/lib/cockpit-upload-helper.ts:145]: I tried looking for an issue tracking the implementation of what we need in webkit but that seems hopeless. 

The codebase does seem to implement [ReadableByteStreamController and ReadableStreamBYOBReader](https://github.com/WebKit/WebKit/blob/5a0fff2319c5d09325cdb3a17efdf2bff6d6662d/Source/WebCore/Modules/streams/ReadableStreamBYOBReader.js). So maybe what we need is implemented soon?

Comment (garrett) [reply pkg/lib/cockpit-upload-helper.ts:145]: Can't you check for the existence of the BYOB function, instead of using a blanket try/catch, like this instead?

```js
if (typeof ReadableStreamBYOBReader !== 'undefined') {
  /* BOYB path */
} else {
  /* fallback for WebKit */
}
```

or

```js
if (typeof ReadableStreamBYOBReader === 'function') {
  /* BOYB path */
} else {
  /* fallback for WebKit */
}

```
`typeof` for functions would return either `"function"` or `"undefined"` _as strings_, hence the string check.

I checked in Firefox, Chromium, and GNOME Web consoles. `(typeof ReadableStreamBYOBReader !== 'undefined')` and `(typeof ReadableStreamBYOBReader === 'function')` both return `true` in Firefox and Chromium; it's `false` in WebKit.

**Comment by allisonkarlitskaya** [comment]
> It mentions ReadableBytesStreamController is needed by ReadableStreamBYOBReader, but it seems to me that Safari/Webkit has a REadableBytesStreamController?

I think the issue is not that it lacks a ReadableBytesStreamController so much as its File object doesn't implement it...  Although I honestly have no idea with all of these classes and interfaces...

File: pkg/lib/cockpit-upload-helper.ts (hunk 9 above)
Comment (allisonkarlitskaya) [reply pkg/lib/cockpit-upload-helper.ts:145]: I like @garrett's suggestion.

File: pkg/lib/cockpit-upload-helper.ts [hunk 10]
```diff
@@ -93,7 +93,48 @@
...
+         */
+        let read;
+        if (typeof ReadableStreamBYOBReader === 'function') {
+            const reader = contents.stream().getReader({ mode: 'byob' });
+            read = () => reader.read(new Uint8Array(BLOCK_SIZE));
+        } else {
+            // fallback code (no 'byob' available)
+            const reader = contents.stream().getReader();
+            let buffer: Uint8Array | null = null;
+            read = async () => {
```
Comment (cockpituous) [inline pkg/lib/cockpit-upload-helper.ts:114]: These 3 added lines are not executed by any test.

File: pkg/lib/cockpit-upload-helper.ts [hunk 11]
```diff
@@ -93,7 +93,48 @@
...
+                // No buffered data?  Try a read.
+                if (!buffer) {
+                    const { done, value } = await reader.read();
+                    if (done) {
+                        return { done, value };
```
Comment (cockpituous) [inline pkg/lib/cockpit-upload-helper.ts:119]: These 4 added lines are not executed by any test.

File: pkg/lib/cockpit-upload-helper.ts [hunk 12]
```diff
@@ -93,7 +93,48 @@
...
+                    } else {
+                        buffer = value;
```
Comment (cockpituous) [inline pkg/lib/cockpit-upload-helper.ts:121]: This added line is not executed by any test.

File: pkg/lib/cockpit-upload-helper.ts [hunk 13]
```diff
@@ -93,7 +93,48 @@
...
+                    }
+                }
+
+                // Return the buffered data: if length < size, return it all, else return a slice
+                if (buffer.length < BLOCK_SIZE) {
+                    const value = buffer;
+                    buffer = null;
+                    return { done: false, value };
```
Comment (cockpituous) [inline pkg/lib/cockpit-upload-helper.ts:129]: These 4 added lines are not executed by any test.

File: pkg/lib/cockpit-upload-helper.ts [hunk 14]
```diff
@@ -93,7 +93,48 @@
...
+                } else {
+                    const value = buffer.slice(0, BLOCK_SIZE);
+                    buffer = buffer.slice(BLOCK_SIZE);
+                    return { done: false, value };
```
Comment (cockpituous) [inline pkg/lib/cockpit-upload-helper.ts:133]: These 3 added lines are not executed by any test.

**Review by martinpitt — APPROVED** [review]
That is really nice!

File: pkg/lib/cockpit-upload-helper.ts [hunk 15]
```diff
@@ -93,7 +93,48 @@ export async function upload(
...
+         */
+        let read;
+        if (typeof ReadableStreamBYOBReader === 'function') {
+            const reader = contents.stream().getReader({ mode: 'byob' });
+            read = () => reader.read(new Uint8Array(BLOCK_SIZE));
+        } else {
+            // fallback code (no 'byob' available)
+            const reader = contents.stream().getReader();
+            let buffer: Uint8Array | null = null;
+            read = async () => {
```
Comment (cockpituous) [inline pkg/lib/cockpit-upload-helper.ts:114]: These 3 added lines are not executed by any test.

File: pkg/lib/cockpit-upload-helper.ts [hunk 16]
```diff
@@ -93,7 +93,48 @@ export async function upload(
...
+                // No buffered data?  Try a read.
+                if (!buffer) {
+                    const { done, value } = await reader.read();
+                    if (done) {
+                        return { done, value };
```
Comment (cockpituous) [inline pkg/lib/cockpit-upload-helper.ts:119]: These 4 added lines are not executed by any test.

File: pkg/lib/cockpit-upload-helper.ts [hunk 17]
```diff
@@ -93,7 +93,48 @@ export async function upload(
...
+                    } else {
+                        buffer = value;
```
Comment (cockpituous) [inline pkg/lib/cockpit-upload-helper.ts:121]: This added line is not executed by any test.

File: pkg/lib/cockpit-upload-helper.ts [hunk 18]
```diff
@@ -93,7 +93,48 @@ export async function upload(
...
+                    }
+                }
+
+                // Return the buffered data: if length < size, return it all, else return a slice
+                if (buffer.length < BLOCK_SIZE) {
+                    const value = buffer;
+                    buffer = null;
+                    return { done: false, value };
```
Comment (cockpituous) [inline pkg/lib/cockpit-upload-helper.ts:129]: These 4 added lines are not executed by any test.

File: pkg/lib/cockpit-upload-helper.ts [hunk 19]
```diff
@@ -93,7 +93,48 @@ export async function upload(
...
+                } else {
+                    const value = buffer.slice(0, BLOCK_SIZE);
+                    buffer = buffer.slice(BLOCK_SIZE);
+                    return { done: false, value };
```
Comment (cockpituous) [inline pkg/lib/cockpit-upload-helper.ts:133]: These 3 added lines are not executed by any test.
