### PR TITLE
SELinux: Fixes npe in setroubleshoot

### LINKED ISSUE #10522: SELinux: cannot read property localId of undefined
Updated my server to Fedora Server 29, looking through the tabs, it hanged on SELinux. 

```
selinux.js:2380 TypeError: Cannot read property 'localId' of undefined
    at selinux.js:16251
    at Array.map (<anonymous>)
    at t.value (selinux.js:16219)
    at jn (selinux.js:2142)
    at Hn (selinux.js:2135)
    at Wn (selinux.js:2265)
    at qn (selinux.js:2932)
    at Qn (selinux.js:2943)
    at fa (selinux.js:3173)
    at ca (selinux.js:3153)
    at ua (selinux.js:3113)
    at na (selinux.js:3073)
    at ka (selinux.js:3530)
    at ga (selinux.js:3535)
    at wa.render (selinux.js:4455)
    at Ha (selinux.js:3607)
    at Object.render (selinux.js:4488)
    at p (selinux.js:72)
    at Function.M (selinux.js:102)
    at T (cockpit.js:879)
    at cockpit.js:891
    at j (cockpit.js:808)
```

Edit: cockpit version is 181.

### PR DESCRIPTION
**Pull request by leomoty**
Closes #10522

### CODE REVIEW

File: pkg/selinux/setroubleshoot-view.jsx [hunk 1]
```diff
@@ -434,7 +434,7 @@ class SETroubleshootPage extends React.Component {
                 }
                 return (
                     <cockpitListing.ListingRow
-                        key={itm.details.localId || index}
+                        key={itm.details && itm.details.localId || index}
```
Comment (martinpitt) [inline pkg/selinux/setroubleshoot-view.jsx]: This looks fine in principle, but can you please use `? :` instead of `&& ||` for this? eslint fails on this:

      437:42  error  Unexpected mix of '&&' and '||'  no-mixed-operators

**Comment by leomoty** [comment]
Oh sorry, nullpointerexception, or in javascript "undefined". Want me to update the commit name as well?

**Comment by martinpitt** [comment]
Thanks, I'm happy to update the commit message when merging.
