### PR TITLE
ws: Automatically renew auto-created expired certificates

### LINKED ISSUE #14121: Reduce expiration time of self-signed cert, and auto-renew it
Cockpit version: 219
OS: Arch
Page: Login

I'm having trouble TLS with various browsers, especially safari on iOS. For example, I just can't log in at all on iOS and get messages in journalctl like this:

`cockpit-tls[3455082]: cockpit-tls: gnutls_handshake failed: The TLS connection was non-properly terminated.`

One thing I notice is that the certificate being generated doesn't appear to be valid:

From the journalctl:
`remotectl[3328058]: Generating temporary certificate using: openssl req -x509 -days 36500 -newkey rsa:2048 -keyout /etc/cockpit/ws-certs.d/0-self-signed...{snip}`

--days 36500 is the question. Where does 36500 come from, and why?
A few years ago it looks like the max limit was fixed at 2 years:  [https://www.globalsign.com/en/blog/ssl-certificate-validity-capped-at-maximum-two-years](https://www.globalsign.com/en/blog/ssl-certificate-validity-capped-at-maximum-two-years)

What is the correct way of altering the length of time? I don't see anything [https://cockpit-project.org/guide/latest/remotectl.8](https://cockpit-project.org/guide/latest/remotectl.8)

### PR DESCRIPTION
**Pull request by martinpitt**
TLS certificates should not be valid for longer than two years [1], and
some browsers (in particular, Safari) are being really picky about it.

So reduce the lifetime for our self-signed (previously 100 years) or
sscg (previously 10 years) certificates to 1 year, and automatically
renew them when they are expired.

[1] https://www.globalsign.com/en/blog/ssl-certificate-validity-capped-at-maximum-two-years

Fixes #14121

### CODE REVIEW

**Comment by martinpitt** [comment]
New unit test [fails](https://logs.cockpit-project.org/logs/pull-14293-20200701-073858-a1d9d5e1-debian-stable/log) on RHEL and Debian/Ubuntu:
```
DEBUG: SKIP: test-remotectlcertificate Bail out! FATAL-WARNING: (null)
DEBUG: ** (remotectl:7272): WARNING **: 03:47:01.045: (null)
```
I also found some whitespace/comment nitpicks.

**Comment by garrett** [comment]
Mentioned in IRC:

- It seems to work here for me, from what I can tell.
- FWIW: It doesn't fix Safari on iOS (but that's really on Apple's end and unrelated to this issue).

File: src/ws/cockpitcertificate.c [hunk 1]
```diff
@@ -133,10 +133,10 @@ openssl_make_dummy_cert (const gchar *key_file,
...
-  gchar *command_line = NULL;
-  gchar *ssl_config = NULL;
-  gchar *subject = generate_subject ();
+  g_autofree gchar *stderr_str = NULL;
+  g_autofree gchar *command_line = NULL;
+  g_autofree gchar *ssl_config = NULL;
+  g_autofree gchar *subject = generate_subject ();
 
   /* make config file with subjectAltName for localhost and our tests */
   ssl_config = create_temp_file (g_get_tmp_dir (), "ssl.conf.XXXXXX", error);
```
Comment (allisonkarlitskaya) [inline src/ws/cockpitcertificate.c:142]: Not your bug, but worth fixing while you're in here: the `return FALSE` in the event of fail from `g_file_set_contents()` will leave the (empty) temp file dangling.

While you're at it, change the `if (!ssl_config)` to a `goto out;` for consistency.

File: src/ws/test-remotectlcertificate.c [hunk 2]
```diff
@@ -245,12 +289,25 @@ static const TestFixture fixture_preinstall_combined_key_last = {
...
 };
 
+static void
+detect_openssl (void)
+{
+  gint exit_status;
+  g_autofree gchar *stdout = NULL;
+  g_autofree gchar *stderr = NULL;
+
+  g_assert (g_spawn_command_line_sync ("which openssl", &stdout, &stderr, &exit_status, NULL));
```
Comment (allisonkarlitskaya) [inline src/ws/test-remotectlcertificate.c:362]: `g_find_program_in_path()`

File: src/ws/test-remotectlcertificate.c [hunk 3]
```diff
@@ -99,6 +102,9 @@ setup (TestCase *tc,
       g_assert (g_chmod (tc->cert_dir, 0555) == 0);
     }
 
+  if (fix->needs_openssl && !have_openssl)
+    return;
```
Comment (allisonkarlitskaya) [inline src/ws/test-remotectlcertificate.c:106]: Surprised to discover that it's not possible to `skip()` inside of a setup function.

Comment (martinpitt) [reply src/ws/test-remotectlcertificate.c:106]: Yeah, I found that quite annoying as well..

File: src/ws/cockpitcertificate.c (hunk 1 above)
Comment (martinpitt) [reply src/ws/cockpitcertificate.c:142]: Well spotted, thanks! Fixed in a separate commit.

File: src/ws/test-remotectlcertificate.c (hunk 2 above)
Comment (martinpitt) [reply src/ws/test-remotectlcertificate.c]: :heart_eyes: Nice! I had a gut feeling that glib had such a thing, but I couldn't find it any more. Changed.

File: src/ws/test-remotectlcertificate.c [hunk 4]
```diff
@@ -251,6 +295,8 @@ main (int argc,
 {
   cockpit_test_init (&argc, &argv);
 
+  openssl_path = g_find_program_in_path ("openssl");
```
Comment (allisonkarlitskaya) [inline src/ws/test-remotectlcertificate.c:361]: Neat idea to save the string.  I almost suggested doing that, except that we don't actually use the value.

In any case, maybe you want to free it before we exit?  It shouldn't trigger any problems with valgrind (since it's still very much reachable), so I leave the choice to you.

Comment (martinpitt) [reply src/ws/test-remotectlcertificate.c:361]: Right, I'd only be concerned about valgrind. I don't see much point in doing extra work that the kernel does anyway, honestly.
