### PR TITLE
systemd: show a warning if the last shutdown/reboot was unclean

### LINKED ISSUE #12947: Help diagnose why a machine went down unexpectedly
Cockpit should help someone diagnose why a machine unexpectedly went down.

1. Unclean shutdown happens (system crash, intentional power cycle, power outage, etc.)
2. Computer boots
3. User logs into Cockpit
4. Cockpit shows that the computer was shutdown unexpectedly
5. Cockpit provides a way to figure out what happened

My initial thought would be to:
- add a notice about the unexpected shutdown
- provide a link to the logs page that shows the previous system boot, sorted with the last entries at the top

While this wouldn't outright solve the problem, it would be a good way to at least let someone know that the system crashed and provide a minimal possible way to start debugging the issue.

### PR DESCRIPTION
**Pull request by adrianocarvalhopt**
Fixes #12947

### Additional Notes

- No copyright header has been included in the new files. I'm unsure what is appropriate.
- If the `last` command is missing from the system, it fails silently: no warning is displayed and nothing is logged.
- The dismissal of the warning is not persistent; it reappears after logout/login, similar to how MOTD messages behave.
- No pixel tests have been included.

Please let me know if anything needs to be revised.

* [ ] the log pages boot link does not seem to properly filter on the given boot, needs debugging.

---

## Shown a warning if the last shutdown/reboot was unclean

Cockpit's healtchard will now show warning when the system was shutdown uncleanly. 

image

### CODE REVIEW

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx [hunk 1]
```diff
@@ -0,0 +1,73 @@
...
+
+export const UncleanShutdownStatus = () => {
+    const [uncleanShutdownId, setUncleanShutdownId] = useState(() => {
+        cockpit.spawn(
+            ["last", "-xn2", "shutdown", "reboot"],
+            { err: "ignore", }
+        ).then((data) => {
+            const shutdownLines = data
+                .split("\n")
+                .filter((line) => line.startsWith("shutdown"));
```
Comment (jelly) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx]: Looking at this implementation, this doesn't seem correct:

```
[jelle@carbon][~/projects/cockpit/unclean-shutdown]%last -xn2 shutdown reboot
reboot   system boot  6.16.4-arch1-1   Mon Sep  1 08:45   still running
shutdown system down  6.16.4-arch1-1   Sun Aug 31 20:14 - 08:45  (12:30)
```

That shutdown was clean

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+
+            const newUncleanShutdownId = shutdownLines.length == 0 ? data : "";
+            setUncleanShutdownId(newUncleanShutdownId);
+            setUncleanShutdownStatusVisible(
+                newUncleanShutdownId != cockpit.localStorage.getItem("dismissed-unclean-shutdown-id")
+            );
+        });
```
Comment (jelly) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx]: Please use `useEffect` or better `useInit` for setting the initial state, combining this in `useState` a bit hard to read.

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+                                {_("View logs")}
+                            </Button>
+                        </li>
+                        <li>
+                            <Button variant="link" isInline
+                                    className="pf-v6-u-font-size-sm"
+                                    onClick={() => hideAlert()}
+                                    id="unclean-shutdown-status-dismiss">
+                                {_("Dismiss")}
+                            </Button>
```
Comment (jelly) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx]: No need for a comma between the list elements, the design doesn't include it.

image

File: pkg/systemd/overview-cards/uncleanShutdownStatus.scss [hunk 4]
```diff
@@ -0,0 +1,23 @@
...
+}
+
+.comma-list li {
+  display: inline-block;
+}
+
+.comma-list li:not(:last-child)::after {
+  content: ",";
+  margin-inline-end: 0.5em;
+}
```
Comment (jelly) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.scss]: Please drop the whole `comma-list`

File: test/verify/check-system-shutdown-restart [hunk 5]
```diff
@@ -144,6 +144,64 @@ class TestShutdownRestart(testlib.MachineCase):
...
+        self.login_and_go("/system")
+
+        # Clean reboot
+        self._cleanReboot(m, b)
+        b.wait_not_present(".unclean-shutdown-status")
+
+        # Unclean reboot
+        self._uncleanReboot(m, b)
+        b.is_present(".unclean-shutdown-status")
+        b.wait_in_text(".system-information-unclean-shutdown-status", "Unclean shutdown")
```
Comment (jelly) [inline test/verify/check-system-shutdown-restart]: This misses one scenario, `Unclean shutdown`

**Review by jelly — CHANGES_REQUESTED** [review]

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx (hunk 1 above)
Comment (jelly) [reply pkg/systemd/overview-cards/uncleanShutdownStatus.jsx]: Oh right `shutdown` is filtered but then still:
```
reboot   system boot  6.15.10-200.fc42 Mon Sep  1 11:46   still running
reboot   system boot  6.15.10-200.fc42 Mon Sep  1 11:30 - 11:45  (00:15)
reboot   system boot  6.15.10-200.fc42 Mon Sep  1 11:26 - crash  (00:03)
reboot   system boot  6.15.10-200.fc42 Mon Sep  1 11:24 - crash  (00:02)
reboot   system boot  6.15.10-200.fc42 Mon Sep  1 11:17 - crash  (00:07)
reboot   system boot  6.15.10-200.fc42 Mon Sep  1 10:06 - 10:07  (00:00)
reboot   system boot  6.15.10-200.fc42 Tue Aug 26 03:59 - 03:59  (00:00)
reboot   system boot  6.14.0-63.fc42.x Tue Aug 26 03:50 - 03:59  (00:09)
```

Some of those are valid sessions.

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx [hunk 6]
```diff
@@ -0,0 +1,73 @@
+import React, { useState } from 'react';
```
Comment (jelly) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx:20]: Please include a SPDX license header

File: pkg/systemd/overview-cards/uncleanShutdownStatus.scss [hunk 7]
```diff
@@ -0,0 +1,23 @@
+.comma-list {
```
Comment (jelly) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.scss]: Same as above, please add a license header

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx (hunk 1 above)
Comment (jelly) [reply pkg/systemd/overview-cards/uncleanShutdownStatus.jsx]: Running a VM and doing a  "Shutdown force off" gives me:

```
[root@fedora-42-127-0-0-2-2201 ~]# last -xn8 reboot shutdown
reboot   system boot  6.15.10-200.fc42 Mon Sep  1 12:08   still running
reboot   system boot  6.15.10-200.fc42 Mon Sep  1 12:06   still running
```

The first line is a still running session:

```
[root@fedora-42-127-0-0-2-2201 ~]# last
root     pts/0        172.27.0.2       Mon Sep  1 12:08   still logged in
reboot   system boot  6.15.10-200.fc42 Mon Sep  1 12:08   still running
reboot   system boot  6.15.10-200.fc42 Mon Sep  1 12:06   still running
```

**Review by jelly — CHANGES_REQUESTED** [review]
Sorry for the very late review, impressive work just needs some small changes to land and a further investigation in unclean shutdown detection

**Comment by jelly** [comment]
>     * If the `last` command is missing from the system, it fails silently: no warning is displayed and nothing is logged.

We already depend on `last` so this is fine:

```
pkg/users/account-logs-panel.jsx:        cockpit.spawn(["last", "--time-format", "iso", "-n25", "--fullnames", name], { environ: ["LC_ALL=C"] })
```

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx (hunk 1 above)
Comment (adrianocarvalhopt) [reply pkg/systemd/overview-cards/uncleanShutdownStatus.jsx]: The rationale is, in summary, if there are no shutdown lines then the last shutdown was unclean.

However, note that only the last two entries of "shutdown" or "reboot" are requested from last (i.e., `last -xn2 shutdown reboot`).

The first line is always `reboot ... still running` (the current session).

The second line will be either:

`shutdown ...` meaning clean shutdown

Or:

`reboot ... still running` meaning unclean shutdown

Suppose `last -xn2 shutdown reboot` returns:

```
reboot   system boot  6.8.0-71-generic Mon Sep  1 22:00   still running
shutdown system down  6.8.0-71-generic Mon Sep  1 22:00 - 22:00  (00:00)
```

If you reboot cleanly `last -xn3 shutdown reboot` (note 3 not 2) returns:

```
reboot   system boot  6.8.0-71-generic Mon Sep  1 22:05   still running
shutdown system down  6.8.0-71-generic Mon Sep  1 22:05 - 22:05  (00:00)
reboot   system boot  6.8.0-71-generic Mon Sep  1 22:00   22:05  (00:05)
```

(The previous reboot entry is "closed" and a new shutdown entry is added with the time of shutdown.)

That means that `last -xn2 shutdown reboot` returns:

```
reboot   system boot  6.8.0-71-generic Mon Sep  1 22:05   still running
shutdown system down  6.8.0-71-generic Mon Sep  1 22:05 - 22:05  (00:00)
```

There is one shutdown line: clean shutdown.

If now you force an unclean shutdown/reboot, `last -xn3 shutdown reboot` (note 3 not 2) returns:

```
reboot   system boot  6.8.0-71-generic Mon Sep  1 22:10   still running
reboot   system boot  6.8.0-71-generic Mon Sep  1 22:05   still running
shutdown system down  6.8.0-71-generic Mon Sep  1 22:05 - 22:05  (00:00)
```

(The previous reboot entry remains "open" and a shutdown entry *not* is added.)

Then `last -xn2 shutdown reboot` returns:

```
reboot   system boot  6.8.0-71-generic Mon Sep  1 22:10   still running
reboot   system boot  6.8.0-71-generic Mon Sep  1 22:05   still running
```

No shutdown lines: unclean shutdown.

There is, however, a problem with this logic which I found out just now. On the first boot `last -xn2 shutdown reboot` returns:

```
reboot   system boot  6.8.0-71-generic Mon Sep  1 22:19   still running
```

Which according to the logic above: unclean shutdown.

So, perhaps a better approach is to count reboot lines:
- If there are two reboot lines: unclean shutdown
- Else, clean shutdown

Do you agree?

File: test/verify/check-system-shutdown-restart (hunk 5 above)
Comment (adrianocarvalhopt) [reply test/verify/check-system-shutdown-restart]: As explained by my other comment it shouldn't make any difference whether it's reboot or shutdown. But I agree that it's better to also cover that scenario in case something changes in the future.

However, I am not being able to recover from a shutdown. In the test scripts, if I shutdown a machine and try to start it again, a new machine is created. I am using:

```
m.spawn("poweroff -f", "poweroff", check=False)
m.wait_poweroff()
m.start()
m.wait_boot()
```

It seems that the API wasn't designed for such a scenario, e.g., m.restart.

I can work on this. I just need to know whether or not I should put that into a separate PR.

Comment (jelly) [reply test/verify/check-system-shutdown-restart]: Let me investigate this for you

Comment (adrianocarvalhopt) [reply test/verify/check-system-shutdown-restart]: Any update on this?

File: pkg/systemd/overview-cards/uncleanShutdownStatus.scss [hunk 8]
```diff
@@ -0,0 +1,8 @@
+.system-information-unclean-shutdown-status-icon {
+  color: var(--pf-t--global--color--status--danger--100);
+}
+
+.system-information-unclean-shutdown-status {
+  color: var(--pf-t--global--color--status--danger--200);
+  font-weight: var(--pf-t--global--font--weight--body--bold);
+}
```
Comment (Venefilyn) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.scss]: Don't think we need to change font-weight here either
```suggestion
.system-information-unclean-shutdown-status {
  color: var(--pf-t--global--text--color--status--danger--default);
}
```

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx [hunk 9]
```diff
@@ -0,0 +1,95 @@
...
+    function hideAlert() {
+        setUncleanShutdownStatusVisible(false);
+        cockpit.localStorage.setItem('dismissed-unclean-shutdown-id', uncleanShutdownId);
+    }
+
+    return (
+        <li className="unclean-shutdown-status" id="page_status_unclean_shutdown">
+            <Flex flexWrap={{ default: 'nowrap' }}>
+                <FlexItem>
+                    <ExclamationTriangleIcon className="system-information-unclean-shutdown-status-icon" />
```
Comment (Venefilyn) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx]:
```suggestion
                    <Icon status="danger">
                        <ExclamationTriangleIcon />
                    </Icon>
```

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx [hunk 10]
```diff
@@ -0,0 +1,95 @@
...
+ * (at your option) any later version.
+ *
+ * Cockpit is distributed in the hope that it will be useful, but
+ * WITHOUT ANY WARRANTY; without even the implied warranty of
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
+ * Lesser General Public License for more details.
+ *
+ * You should have received a copy of the GNU Lesser General Public License
+ * along with Cockpit; If not, see <https://www.gnu.org/licenses/>.
+ */
```
Comment (Venefilyn) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx:18]: @jelly we don't have SPDX in any of our JS files. We have one in a python file in the bots repo. Do you want us to do something like this?
```suggestion
// This file is part of Cockpit.
// SPDX-License-Identifier: LGPL-2.1-or-later
```

**Review by Venefilyn — CHANGES_REQUESTED** [review]
The colors you used are not part of the [Patternfly semantic tokens but rather the base tokens](https://www.patternfly.org/design-foundations/colors). Added two suggestions to fix the colors for the status so it works on both light and dark theme. There is also a way for [icons to get color through the use of components](https://www.patternfly.org/components/icon#status-colors), so we can drop the CSS completely for that.

~~Also with SPDX comment, left a comment for Jelle to take a look at. For now though that copyright header is correctly made!~~ Edit: Jelly meant release header which is now added - thanks!

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx (hunk 10 above)
Comment (Venefilyn) [reply pkg/systemd/overview-cards/uncleanShutdownStatus.jsx:18]: Sorted out, Jelle meant including a license header (which is added, thanks!), not SPDX. Resolving

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx (hunk 6 above)
Comment (Venefilyn) [reply pkg/systemd/overview-cards/uncleanShutdownStatus.jsx:20]: License header has been added. Thanks!

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx [hunk 11]
```diff
@@ -0,0 +1,98 @@
...
+        });
+    });
+
+    if (!uncleanShutdownId || !uncleanShutdownStatusVisible) {
+        return null;
+    }
+
+    function hideAlert() {
+        setUncleanShutdownStatusVisible(false);
+        cockpit.localStorage.setItem('dismissed-unclean-shutdown-id', uncleanShutdownId);
```
Comment (cockpituous) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx]: These 3 added lines are not executed by any test.  [Details](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-22289-c45ae717-20251111-201844-fedora-43-devel/Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx [hunk 12]
```diff
@@ -0,0 +1,98 @@
...
+                    </Icon>
+                </FlexItem>
+                <div>
+                    <div className="pf-v6-u-text-break-word system-information-unclean-shutdown-status">
+                        {_("Unclean shutdown")}
+                    </div>
+                    <Flex>
+                        <Button variant="link" isInline
+                                    className="pf-v6-u-font-size-sm"
+                                    onClick={() => cockpit.jump("/system/logs#/?boot=-1")}>
```
Comment (cockpituous) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx]: This added line is not executed by any test.  [Details](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-22289-c45ae717-20251111-201844-fedora-43-devel/Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx [hunk 13]
```diff
@@ -0,0 +1,98 @@
...
+                            {_("View logs")}
+                        </Button>
+                        <Button variant="link" isInline
+                                    className="pf-v6-u-font-size-sm"
+                                    onClick={() => hideAlert()}
```
Comment (cockpituous) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx]: This added line is not executed by any test.  [Details](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-22289-c45ae717-20251111-201844-fedora-43-devel/Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx [hunk 14]
```diff
@@ -0,0 +1,100 @@
...
+        });
+    });
+
+    if (!uncleanShutdownId || !uncleanShutdownStatusVisible) {
+        return null;
+    }
+
+    function hideAlert() {
+        setUncleanShutdownStatusVisible(false);
+        cockpit.localStorage.setItem('dismissed-unclean-shutdown-id', uncleanShutdownId);
```
Comment (cockpituous) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx]: These 3 added lines are not executed by any test.  [Details](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-22289-ddb39e90-20251112-150302-fedora-43-devel/Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx [hunk 15]
```diff
@@ -0,0 +1,100 @@
...
```
Comment (cockpituous) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx]: These 3 added lines are not executed by any test.  [Details](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-22289-e08317bd-20251112-190250-fedora-43-devel/Coverage/lcov/github-pr.diff.gcov.html)

**Comment by jelly** [comment]
@Venefilyn do you mind reviewing this one? As I wrote part of the commit it is weird to self review :)

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx [hunk 16]
```diff
@@ -0,0 +1,100 @@
...
+            if (previous_boot === undefined)
+                return;
+
+            // "crash" on wtmpdb, "still running" on util-linux
+            if (!previous_boot.includes("crash") && !previous_boot.includes("still running"))
+                return;
+
+            const lines = previous_boot.split(/ +/);
+            const started = new Date(lines[4]);
+            if (isNaN(started)) {
```
Comment (Venefilyn) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx:51]: Checking the command myself I see:
```bash
❯ last --system --limit=2 --time-format=iso shutdown reboot
reboot   system boot  6.17.5-ba07.fc4* 2025-11-13T12:39:15+01:00   still running
shutdown system down  6.17.5-ba07.fc4* 2025-11-13T02:09:52+01:00 - 2025-11-13T12:39:15+01:00  (10:29)
```
I don't think the RegEx is stable enough. Not only that, if I understand this correctly getting the endtime wouldn't work due to `- `. Which we don't need here but still showcases it being icky
```suggestion
            const re = /(?<status>\S+) +(?<action>system \S+) +(?<kernel>\S+) +(?<startDate>\S+) +(?:(?<endDate>still running)|- (?<endDate>\S+)) *(?:\((\S+)\))?/g
            const match = re.exec(previous_boot);
            const started = new Date(match.groups["startDate"]);
            if (isNaN(started)) {
```

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx (hunk 15 above)
Comment (Venefilyn) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx]: Feels like this is more suited for `sessionStorage` as it doesn't have to persist until the website data is cleared. If we want this to remain between sessions, this could stack up over time as there is nothing to clear them atm.

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx [hunk 17]
```diff
@@ -0,0 +1,100 @@
...
+    return (
+        <li className="unclean-shutdown-status" id="page_status_unclean_shutdown">
+            <Flex flexWrap={{ default: 'nowrap' }}>
+                <FlexItem>
+                    <Icon status="danger">
+                        <ExclamationTriangleIcon className="system-information-unclean-shutdown-status-icon" />
+                    </Icon>
+                </FlexItem>
+                <div>
+                    <div className="pf-v6-u-text-break-word system-information-unclean-shutdown-status">
```
Comment (Venefilyn) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx]: Found a CSS that we can likely use from the [PF utilities page](https://www.patternfly.org/utility-classes/text#status-and-state-text-colors), which would be great if it works as we avoid creating another CSS class.
```suggestion
                    <div className="pf-v6-u-text-break-word pf-v6-u-text-color-status-danger system-information-unclean-shutdown-status">
```

**Review by Venefilyn — COMMENTED** [review]
Sure, @jelly PTAL :pray: 

Overall implementation seems fine and tests too. One concern with RegEx and figured we can also remove the CSS file

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx [hunk 18]
```diff
@@ -0,0 +1,99 @@
...
+        });
+    });
+
+    if (!uncleanShutdownId || !uncleanShutdownStatusVisible) {
+        return null;
+    }
+
+    function hideAlert() {
+        setUncleanShutdownStatusVisible(false);
+        cockpit.sessionStorage.setItem('dismissed-unclean-shutdown-id', uncleanShutdownId);
```
Comment (cockpituous) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx]: These 3 added lines are not executed by any test.  [Details](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-22289-b6b353db-20251113-165614-fedora-43-devel/Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx [hunk 19]
```diff
@@ -0,0 +1,99 @@
...
+                    </Icon>
+                </FlexItem>
+                <div>
+                    <div className="pf-v6-u-text-break-word pf-v6-u-text-color-status-danger">
+                        {_("Unclean shutdown")}
+                    </div>
+                    <Flex>
+                        <Button variant="link" isInline
+                                    className="pf-v6-u-font-size-sm"
+                                    onClick={() => cockpit.jump("/system/logs#/?boot=-1")}>
```
Comment (cockpituous) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx]: This added line is not executed by any test.  [Details](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-22289-b6b353db-20251113-165614-fedora-43-devel/Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx [hunk 20]
```diff
@@ -0,0 +1,99 @@
...
+                            {_("View logs")}
+                        </Button>
+                        <Button variant="link" isInline
+                                    className="pf-v6-u-font-size-sm"
+                                    onClick={() => hideAlert()}
```
Comment (cockpituous) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx]: This added line is not executed by any test.  [Details](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-22289-b6b353db-20251113-165614-fedora-43-devel/Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx (hunk 18 above)
Comment (cockpituous) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx:67]: These 3 added lines are not executed by any test.  [Details](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-22289-a4d6eb80-20251113-203547-fedora-43-devel/Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx [hunk 21]
```diff
@@ -0,0 +1,99 @@
...
+                    </Icon>
+                </FlexItem>
+                <div>
+                    <div className="pf-v6-u-text-break-word pf-v6-u-text-color-status-danger">
+                        {_("Unclean shutdown")}
+                    </div>
+                    <Flex>
+                        <Button variant="link" isInline
+                                    className="pf-v6-u-font-size-sm"
+                                    onClick={() => cockpit.jump("/system/logs#/?boot=-1")}>
```
Comment (cockpituous) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx:85]: This added line is not executed by any test.  [Details](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-22289-a4d6eb80-20251113-203547-fedora-43-devel/Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx [hunk 22]
```diff
@@ -0,0 +1,99 @@
...
+                            {_("View logs")}
+                        </Button>
+                        <Button variant="link" isInline
+                                    className="pf-v6-u-font-size-sm"
+                                    onClick={() => hideAlert()}
```
Comment (cockpituous) [inline pkg/systemd/overview-cards/uncleanShutdownStatus.jsx:90]: This added line is not executed by any test.  [Details](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-22289-a4d6eb80-20251113-203547-fedora-43-devel/Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/overview-cards/uncleanShutdownStatus.jsx (hunk 16 above)
Comment (jelly) [reply pkg/systemd/overview-cards/uncleanShutdownStatus.jsx:51]: This is stable enough, we are only interested in the start time here, not the "end time" so we don't have to deal with a `-`. We check on line 46 if there was a crash. We just use the start time as unique boot identifier.

```
> line = "shutdown system down  6.17.7-arch1-1   2025-11-12T22:40:15+01:00 - 2025-11-14T09:25:14+01:00 (1+10:44)"
'shutdown system down  6.17.7-arch1-1   2025-11-12T22:40:15+01:00 - 2025-11-14T09:25:14+01:00 (1+10:44)'
> lines = line.split(/ +/);
[
  'shutdown',
  'system',
  'down',
  '6.17.7-arch1-1',
  '2025-11-12T22:40:15+01:00',
  '-',
  '2025-11-14T09:25:14+01:00',
  '(1+10:44)'
]
> lines[4]
'2025-11-12T22:40:15+01:00
```

Comment (Venefilyn) [reply pkg/systemd/overview-cards/uncleanShutdownStatus.jsx:51]: Sure, up to you. Just that without checking the command output or tests I can't know what the output of the command would be, just that the 5th element in the array is a start time

**Review by Venefilyn — APPROVED** [review]
Code LGTM, thanks!
