### PR TITLE
Fix outdated/redirected urls

### LINKED ISSUE #20621: Validate all URLs
Checked 179 URLs out of which 1 is/are invalid:
    https://developer-old.gnome.org/gio/stable/gio-GDBusError.html#g-dbus-error-encode-gerror : [Errno -2] Name or service not known

### PR DESCRIPTION
**Pull request by jelly**
Fixes #20621

### CODE REVIEW

File: pkg/systemd/reporting.jsx [hunk 1]
```diff
@@ -312,7 +312,7 @@ const BusWorkflowRow = ({ problem, client, workflow }) => {
                         /* GLib encodes errors for transport over the wire,
                          * but we don’t have a good way of decoding them without calling into GIO.
                          *
-                         * https://developer-old.gnome.org/gio/stable/gio-GDBusError.html#g-dbus-error-encode-gerror
+                         * https://dbus.freedesktop.org/doc/dbus-glib/dbus-glib-DBusGError.html#enum%20DBusGError
```
Comment (allisonkarlitskaya) [inline pkg/systemd/reporting.jsx:315]: This is not the same thing.   One of those is from libdbus and the other is from gio (glib).   https://docs.gtk.org/gio/type_func.DBusError.encode_gerror.html is the first google hit for what I think you're looking for.

**Review by allisonkarlitskaya — CHANGES_REQUESTED** [review]
