### PR TITLE
users: Retain authorized_keys file permissions

### LINKED ISSUE #11876: File ownership changed when removing authorized pubkey from user
Cockpit version: 188, 194
OS: 188 on Debian Stretch, 194 on Arch Linux
Page: "Accounts"

When removing a key from the list of `Authorized Public SSH Keys` of a user, that user's `~/.ssh/authorized_keys` file becomes owned by `root:root`. If the file is not world-readable (or group-readable if the user is a member of group `root`), this breaks that user's ssh key login.

Steps to reproduce
1. Make sure the target user has a file `~/.ssh/authorized_keys` with more than 1 key in it.
2. Check that this file is owned by the target user and group.
3. Remove one of the keys through Cockpit>Accounts>[target user]>Authorized Public SSH Keys.
4. Check ownership of the target user's `~/.ssh/authorized_keys`.

Expected result:
File ownership remains unchanged.

Actual result:
File is now owned by `root:root`.

### PR DESCRIPTION
**Pull request by martinpitt**
cockpit.file().replace() creates an entirely new file with root:root    
permissions, which completely breaks a user's ~/.ssh/authorized_keys    
file when removing a key.    
    
Until we have a more powerful file API, use `sed -i` instead, which    
keeps file permissions of existing files. This doesn't automagically    
remove empty lines, so adjust the integration test to expect the extra    
empty line that it added a few lines up.    
    
Fixes #11876

### CODE REVIEW

File: pkg/users/authorized-keys.js [hunk 1]
```diff
@@ -114,24 +114,12 @@ function AuthorizedKeys (user_name, home_dir) {
...
-                else
-                    new_lines.push(lines[i]);
-            }
-            return new_lines.join("\n");
-        });
-    };
+    // don't use cockpit.file.modify() here, as that doesn't preserve permissions
+    // (https://github.com/cockpit-project/cockpit/issues/18033)
+    self.remove_key = key => cockpit.spawn(
+        ["sed", "-i", "\\!^" + key + "$!d", filename],
```
Comment (martinpitt) [inline pkg/users/authorized-keys.js:120]: I use the `!` delimiter here as ! is not a [base64 character](https://en.wikipedia.org/wiki/Base64). `/` is, so we can't use sed's default delimiter.

**Review by KKoukiou — APPROVED** [review]
