### PR TITLE
tuned: Sensible text and tooltip on insufficient permissions

### LINKED ISSUE #8601: Performance Profile shows error for unprivileged
Using Version 161 (from ubuntu 18.04 repo), with tuned 2.9.0 installed.

When logged in without checking "Reuse my password for privileged tasks", Performance Profile shows "error" and its status shows "Communication with tuned has failed". 

Perhaps a message suggesting "requires elevation" is more informative.

### PR DESCRIPTION
**Pull request by Gundersanne**
Fixes #8601

### CODE REVIEW

**Comment by Gundersanne** [comment]
@garrett Can you take a look at the text I used in case the user is not permitted to use tuned? 

screen-tuned-permissions

**Comment by Gundersanne** [comment]
@garrett Would the tooltip "The user $user is not permitted to view or modify tuned" also be ok? As you also need admin permission to view the current status.

**Comment by garrett** [comment]
In-person discussion: As a non-admin cannot see the state of tuned, it might make more sense to hide the status completely for those without administration privileges.

**Comment by martinpitt** [comment]
@Gundersanne : Semaphore spotted an i18n problem:
```
DEBUG: ERROR: translatable strings must be marked with _("")
DEBUG: pkg/tuned/dialog.js:                    _('The user $0 is not permitted to view or modify tuned'),
```
You can run these checks yourself easily with tools/test-static-code.

**Comment by martinpitt** [comment]
@Gundersanne : Setting needswork label, it seems this needs some redesign according to the discussion above, and fixing the syntax. Once you force-push, please drop the needswork label and leave a comment here so that potential reviewers get a notification email (label changes and pushes don't generate one).

**Comment by Gundersanne** [comment]
screen-tuned-permissions

I was wrong, admin is not needed to read (or even modify) tuned. But as we also interact with systemd in the dialog, we do need it to modify it from the dialog. I disabled the click and added a tooltip when admin access is required.

**Comment by Gundersanne** [comment]
hover

File: pkg/tuned/dialog.js [hunk 1]
```diff
@@ -76,7 +77,7 @@
         }
 
         function update_button() {
-            var tuned = cockpit.dbus('com.redhat.tuned', { superuser: true });
+            var tuned = cockpit.dbus('com.redhat.tuned', { superuser: false });
```
Comment (martinpitt) [inline pkg/tuned/dialog.js]: `false` is the default (but nitpick). This could use a comment like "reading the current profile works as user". However, do *all* operations we do on com.redhat.tuned are possible as user, in particular changing the current profile? That would seem a bit strange to me, but maybe pcp ships a polkit rule that allows this to normal users.

If `false` breaks, then usually the right thing to do is `superuser: "try"`, see [cockpit.spawn()](https://cockpit-project.org/guide/latest/cockpit-spawn.html).

File: pkg/tuned/dialog.js [hunk 2]
```diff
@@ -275,18 +280,13 @@
         button.on('click', open_dialog);
 
         tuned_service.addEventListener("changed", update_button);
-        update_button();
```
Comment (martinpitt) [inline pkg/tuned/dialog.js]: I think this is okay. We always get an initial `change` event when the service object initializes.

File: pkg/tuned/dialog.js (hunk 1 above)
Comment (Gundersanne) [reply pkg/tuned/dialog.js]: You're absolutely right, you can only change the profile when you have a physical shell or are root. I'll change this and add a test to make sure this doesn't break. This patch tests whether or not you can read a profile as non-root, but not that you *can't* change it.

Superuser try seems good, but I guess we could also just do superuser true. Since the dialog needs admin anyway, and I assume there are few cases where you log into your own system via cockpit.

File: pkg/tuned/dialog.js [hunk 3]
```diff
@@ -266,6 +272,10 @@
             tuned_service.start()
                 .done(function () {
                     update_button();
+                    /* There are a few cases where tuned can be started as user,
```
Comment (martinpitt) [inline pkg/tuned/dialog.js]: This is a bit confusing - better say "by an user", as tuned will still run as root.

File: pkg/tuned/dialog.js (hunk 2 above)
Comment (martinpitt) [reply pkg/tuned/dialog.js]: On second thought, please put it back. This is a theoretical race if the service object can finish reading the properties before we attach the `changed` handler above.
