### PR TITLE
bridge: Fix cockpitdbuscache barrier ordering

### LINKED ISSUE #5792: dbusjson: Introspection in the presence of an ObjectManager has issues
The D-Bus cache either uses introspection to retrieve the object hierarchy or an ObjectManager.  
However, if the cache uses introspection and _also_ receives ObjectManager signals such as InterfaceAdded, there seem to be ordering issues.

Making the cache use introspection while a ObjectManager would be available is very likely a programmer error, and I think it is reasonable to just not support this, or if we support it, not optimize for it and just ignore the ObjectManager signals.

(I provide more details soon.)

### PR DESCRIPTION
**Pull request by mvollmer**
Fixes #5792

### CODE REVIEW

**Comment by mvollmer** [comment]
Another try at fixing the network tests.

**Comment by mvollmer** [comment]
I should probably add a unit test.

The concrete case was something like this:

Cache receives InterfacesAdded ( iface1, iface2 ) and PropertiesChanged ( iface 2) very close together so that both sit in the barrier queue, in proper order.

When InterfacesAdded is processed, it does iface1, and then causes a recursive call to barrier_progress before going on to iface2. 

barrier_progress then calls the PropertiesChanged handler.

When that is done, the iface2 portion of InterfacesChanged runs, and undoes the PropertiesChanged work.

**Comment by mvollmer** [comment]
> I should probably add a unit test.

It's a bit difficult to steer the cache into just the right state from the outside, so I am giving up on this for now, unfortunately.

File: src/bridge/cockpitdbuscache.c [hunk 1]
```diff
@@ -150,25 +152,52 @@ barrier_progress (CockpitDBusCache *self)
...
+       * recursive calls in the middle of its work when it
+       * processes multiple interfaces.
        */
-      if (batch && batch->number <= barrier->number)
-        return;
 
-      g_queue_pop_head (self->barriers);
-      (barrier->callback) (self, barrier->user_data);
-      g_slice_free (BarrierData, barrier);
+      self->barrier_more_progress = TRUE;
```
Comment (dperpeet) [inline src/bridge/cockpitdbuscache.c]: I think this may have to be a counting variable. If `n>1` calls to `barrier_progress` occur while one is already running, the outer loop will only run one extra time. I believe this is ok for most cases, but if they affect more than one batch, they will not get called until the next time `barrier_progress` is invoked. That wouldn't lead to an error directly, but in perceptible delays (work done only on the next call of `barrier_progress`).

Comment (dperpeet) [inline src/bridge/cockpitdbuscache.c]: I suggest using a plain counter and decrementing that in the `barrier_progress` loop. This corresponds to a semaphore-like pattern instead of a mutex.

Comment (mvollmer) [inline src/bridge/cockpitdbuscache.c]: Yes, very good catch.

File: src/bridge/cockpitdbuscache.c [hunk 2]
```diff
@@ -86,6 +86,8 @@ struct _CockpitDBusCache {
   GQueue *batches;
   GQueue *barriers;
   guint number;
+  gboolean barrier_progressing;
+  gboolean barrier_progressing_rounds;
```
Comment (dperpeet) [inline src/bridge/cockpitdbuscache.c]: I don't think this should be of type `gboolean`

File: src/bridge/cockpitdbuscache.c [hunk 3]
```diff
@@ -150,25 +152,53 @@ barrier_progress (CockpitDBusCache *self)
...
 
-      g_queue_pop_head (self->barriers);
-      (barrier->callback) (self, barrier->user_data);
-      g_slice_free (BarrierData, barrier);
+      self->barrier_progressing_rounds += 1;
+      return;
     }
+
+  self->barrier_progressing = TRUE;
+  self->barrier_progressing_rounds = 1;
```
Comment (dperpeet) [inline src/bridge/cockpitdbuscache.c]: Excellent, I think this is much better. This could have been achieved with only the counter variable, but having the extra boolean makes the code a bit easier to read and less error prone.

File: src/bridge/cockpitdbuscache.c [hunk 4]
```diff
@@ -150,25 +152,53 @@ barrier_progress (CockpitDBusCache *self)
   BarrierData *barrier;
   BatchData *batch;
 
-  batch = g_queue_peek_head (self->batches);
-
-  for (;;)
+  if (self->barrier_progressing)
```
Comment (dperpeet) [inline src/bridge/cockpitdbuscache.c]: It would be really nice to have a test for this change...

**Comment by dperpeet** [comment]
I pushed a change to change the variable to `guint`

**Comment by dperpeet** [comment]
remaining failures seem unrelated
