### PR TITLE
tls: Support separate certificate key file

### LINKED ISSUE #8922: ws: separate cert and key for easy LetsEncrypt integration
is this: 
https://github.com/cockpit-project/cockpit/blob/master/containers/kubernetes/README.md#web-certificates
always available or just with kubernetes? 
i am trying and keep failing...
CentOS 7 with cockpit and LetsEncrypt (acme.sh), 
/var/run/secrets/ws-certs.d/tls.crt and /var/run/secrets/ws-certs.d/tls.key available, 
but cockpit-ws still creating selfsigned. 

any hint please?

### PR DESCRIPTION
**Pull request by martinpitt**
If a found ws-certs.d/ *.cert file has a corresponding *.key file, use
that instead of expecting a merged private key in the *.cert file. This
makes it easier to use Cockpit with LetsEncrypt or other automatically
maintained TLS certificates.

These days we mostly only need that for cockpit-tls. But fix it for
cockpit-ws as well, so that we keep remotectl happy (it complains
otherwise that it cannot find the key).

Fixes #8922

 - [x] builds on top of PR #13398

### CODE REVIEW

File: src/common/cockpitwebcertificate.c [hunk 1]
```diff
@@ -69,10 +69,21 @@ load_cert_from_dir (const char *dir_name,
 
   if (n > 0)
     asprintfx (&ret, "%s/%s", dir_name, certs[n-1]->d_name);
+  while (n--)
```
Comment (allisonkarlitskaya) [inline src/common/cockpitwebcertificate.c]: This belongs in a separate commit.

File: src/common/cockpitwebcertificate.c [hunk 2]
```diff
@@ -69,10 +69,21 @@ load_cert_from_dir (const char *dir_name,
...
+    free (certs[n]);
   free (certs);
   return ret;
 }
 
+/**
+ * cockpit_certificate_locate:
```
Comment (allisonkarlitskaya) [inline src/common/cockpitwebcertificate.c]: Probably this too.

File: doc/guide/https.xml [hunk 3]
```diff
@@ -30,11 +30,16 @@
...
-      and a last one containing a <literal>BEGIN PRIVATE KEY</literal> or similar.
-      The key may not be encrypted. For example:</para>
+      alphabetical order. The <literal>.cert</literal> file should contain
+      one or more OpenSSL style <literal>BEGIN CERTIFICATE</literal>
+      blocks for the server certificate and the intermediate certificate authorities.</para>
+
+    <para>The private key can either be contained in the same <code>.cert</code> file
+    as an additional <literal>BEGIN PRIVATE KEY</literal> or similar block, or in
+    a separate file with the same name as the certificate, but with a <code>.key</code>
+    suffix instead of <code>.cert</code>. The key may not be encrypted. For example,
```
Comment (allisonkarlitskaya) [inline doc/guide/https.xml]: Since you're making changes here anyway, let's say "must not be".

File: doc/guide/https.xml [hunk 4]
```diff
@@ -30,11 +30,16 @@
...
-      alphabetical order. The <literal>.cert</literal> file should contain at least two
-      OpenSSL style PEM blocks. First one or more <literal>BEGIN CERTIFICATE</literal>
-      blocks for the server certificate and the intermediate certificate authorities
-      and a last one containing a <literal>BEGIN PRIVATE KEY</literal> or similar.
-      The key may not be encrypted. For example:</para>
+      alphabetical order. The <literal>.cert</literal> file should contain
+      one or more OpenSSL style <literal>BEGIN CERTIFICATE</literal>
+      blocks for the server certificate and the intermediate certificate authorities.</para>
+
+    <para>The private key can either be contained in the same <code>.cert</code> file
```
Comment (allisonkarlitskaya) [inline doc/guide/https.xml]: Do we want to soft-deprecate the merged file functionality?  I always found it to be very strange, to be honest...

File: src/common/cockpitwebcertificate.c [hunk 5]
```diff
@@ -111,6 +111,41 @@ cockpit_certificate_locate (char **error)
...
+  char *keypath = NULL;
+
+  /* invalid if it does not end with .cert */
+  if (len <= 5 || strcmp (certfile + len - 5, ".cert") != 0)
+    {
+      warnx ("invalid certificate file name: %s", certfile);
+      return NULL;
+    }
+
+  keypath = strdupx (certfile);
```
Comment (allisonkarlitskaya) [inline src/common/cockpitwebcertificate.c]: Better use `asprintf` with `%.*s` here.

File: src/common/cockpitwebcertificate.c [hunk 6]
```diff
@@ -111,6 +111,41 @@ cockpit_certificate_locate (char **error)
...
+  keypath[len - 4] = 'k';
+  keypath[len - 3] = 'e';
+  keypath[len - 2] = 'y';
+  keypath[len - 1] = '\0';
+
+  if (access (keypath, F_OK) < 0)
```
Comment (allisonkarlitskaya) [inline src/common/cockpitwebcertificate.c]: `access()` is weird.  It almost never makes sense to call it.

Why not have this function open and return the contents of the `.key` file instead?

Also: you should treat `ENOENT` as an expected error and all other errors as failures.

File: src/common/cockpitwebcertificate.c [hunk 7]
```diff
@@ -111,6 +111,41 @@ cockpit_certificate_locate (char **error)
...
 
+/**
+ * cockpit_certificate_key_path:
+ *
+ * Check if there is a matching *.key file for the given *.cert file.
+ *
+ * Return key file path on success, or %NULL if there is no matching *.key file.
+ */
+char *
+cockpit_certificate_key_path (const char *certfile)
```
Comment (allisonkarlitskaya) [inline src/common/cockpitwebcertificate.c]: No `*at()`-style `dirfd` argument here?

File: src/ws/cockpitcertificate.c [hunk 8]
```diff
@@ -382,19 +382,32 @@ cockpit_certificate_load (const gchar *cert_path,
...
+      g_autofree gchar *combined = NULL;
+
+      r = cockpit_certificate_parse (cert_path, &certs, &key);
+      if (r < 0)
+        {
+          g_set_error (error, G_IO_ERROR, g_io_error_from_errno (-r), "Failed to load %s: %s", cert_path, g_strerror (-r));
+          return NULL;
+        }
+
+      /* Gio only has constructors for parsing certs and key from one string, so combine them */
```
Comment (allisonkarlitskaya) [inline src/ws/cockpitcertificate.c]: This is weird.  We split the file out and concatenate it again?

We should probably ask for new GIO API here.  Its weird use of the combined format is probably what inspired cockpit's original use of the format and got us into the current mess....

File: src/common/cockpitwebcertificate.c (hunk 6 above)
Comment (martinpitt) [reply src/common/cockpitwebcertificate.c]: Returning the contents instead of the path would be rather inconvenient -- in all cases where we call it, we want the path, as that's what `connection_crypto_init()` or `g_tls_certificate_new_from_files()` takes. In particular, having the cert as path and the key as value would require more manual work on our side.

I specifically used `F_OK` instead of `R_OK` to not just silently ignore key files with wrong permissions, but getting an explicit error message about them later on, when we try to open it. 

ENOENT> fair enough, I can raise a `warn()` about it, in case there's weird errors like `ELOOP` or `ENOTDIR`.

What would you suggest instead of `access()`?

File: src/common/cockpitwebcertificate.c (hunk 7 above)
Comment (martinpitt) [reply src/common/cockpitwebcertificate.c]: We don't need it in the actual callers, neither of them has a dirfd. We could add it and add a test for it in test-webcertificate.c, but we wouldn't use it in practice.

File: src/ws/cockpitcertificate.c (hunk 8 above)
Comment (martinpitt) [reply src/ws/cockpitcertificate.c]: The split+recombine is existing code, this PR doesn't touch that case. Admittedly it's rather weird, yes.

`g_tls_certificate_new_from_files()` indeed makes a lot more sense, for the "separate files" case that this PR adds.

File: doc/guide/https.xml (hunk 4 above)
Comment (martinpitt) [reply doc/guide/https.xml]: We can consider that, and I'd be fine with that. Then remotectl should create the self-signed or sscg certificates in split format, too, and the doc should be adjusted. This sounds like a separate PR, though.

File: src/ws/cockpitcertificate.c (hunk 8 above)
Comment (martinpitt) [reply src/ws/cockpitcertificate.c]: Speculating: Perhaps `g_tls_certificate_new_from_pem()` expects cert and key in a certain order, and this dance is done to ensure that the key is last? But at least the [current documentation](https://developer.gnome.org/gio/unstable/GTlsCertificate.html#g-tls-certificate-new-from-pem) does not prescribe an ordering.

File: src/common/cockpitwebcertificate.c (hunk 1 above)
Comment (martinpitt) [reply src/common/cockpitwebcertificate.c]: Fixed.

File: src/common/cockpitwebcertificate.c (hunk 2 above)
Comment (martinpitt) [reply src/common/cockpitwebcertificate.c]: Split out.

File: src/common/cockpitwebcertificate.c (hunk 5 above)
Comment (martinpitt) [reply src/common/cockpitwebcertificate.c]: Done, thanks for the hint! This is so much nicer.

File: src/common/cockpitwebcertificate.c (hunk 6 above)
Comment (martinpitt) [reply src/common/cockpitwebcertificate.c]: The follow-up adds the warning for not-`ENOENT`.

File: doc/guide/https.xml (hunk 3 above)
Comment (martinpitt) [reply doc/guide/https.xml]: That got fixed in the recent force push.

File: src/common/cockpitwebcertificate.c (hunk 6 above)
Comment (martinpitt) [reply src/common/cockpitwebcertificate.c]: I reworked this a bit harder, and changed from this LBYL to a more robust EAFP approach. I like this much better, thanks!

**Comment by martinpitt** [comment]
I locally fixed the memleak in test-webcertificate. I'll push it when rebasing after landing #13398.

File: src/common/cockpitwebcertificate.c (hunk 7 above)
Comment (martinpitt) [reply src/common/cockpitwebcertificate.c]: This comment is obsolete now, as it's now pure string manipulation.

**Comment by martinpitt** [comment]
@allisonkarlitskaya : I'm happy with this now, and tests look reasonably good. Can you please re-review?

File: src/common/cockpitwebcertificate.c [hunk 9]
```diff
@@ -112,6 +112,30 @@ cockpit_certificate_locate (char **error)
...
+  char *keypath = NULL;
+
+  /* .cert suffix case: chop off suffix, append ".key" */
+  if (len > 5 && strcmp (certfile + len - 5, ".cert") == 0)
+    asprintfx (&keypath, "%.*s.key", len - 5, certfile);
+  /* *.crt suffix case */
+  else if (len > 4 && strcmp (certfile + len - 4, ".crt") == 0)
+    asprintfx (&keypath, "%.*s.key", len - 4, certfile);
+  else
+    warnx ("invalid certificate file name: %s", certfile);
```
Comment (allisonkarlitskaya) [inline src/common/cockpitwebcertificate.c]: This should be an assert, shouldn't it?  Is there any way that this might actually happen?

File: src/tls/connection.c [hunk 10]
```diff
@@ -790,10 +791,18 @@ connection_crypto_init (const char *certfile,
...
 
+  /* check if we have a separate key file */
+  keyfile = cockpit_certificate_key_path (certfile);
   if (keyfile)
     ret = gnutls_certificate_set_x509_key_file (parameters.x509_cred, certfile, keyfile, GNUTLS_X509_FMT_PEM);
-  else
-    ret = set_x509_key_from_combined_file (parameters.x509_cred, certfile);
+
+  /* fall back to combined file */
+  if (!keyfile || ret == GNUTLS_E_FILE_ERROR)
```
Comment (allisonkarlitskaya) [inline src/tls/connection.c]: This is a little bit gross...

Again: is it actually possible that `keyfile` will be NULL here?  Do we want to do something meaningful in that case, still?

File: src/tls/connection.c [hunk 11]
```diff
@@ -790,10 +791,18 @@ connection_crypto_init (const char *certfile,
   if (ret != GNUTLS_E_SUCCESS)
     errx (EXIT_FAILURE, "gnutls_certificate_allocate_credentials failed: %s", gnutls_strerror (ret));
 
+  /* check if we have a separate key file */
```
Comment (allisonkarlitskaya) [inline src/tls/connection.c]: This comment isn't true anymore.

File: src/tls/connection.c [hunk 12]
```diff
@@ -790,10 +791,18 @@ connection_crypto_init (const char *certfile,
...
+  keyfile = cockpit_certificate_key_path (certfile);
   if (keyfile)
```
Comment (allisonkarlitskaya) [inline src/tls/connection.c]: Which means that this `if` is weird...

File: src/ws/cockpitcertificate.c [hunk 13]
```diff
@@ -380,21 +380,39 @@ cockpit_certificate_load (const gchar *cert_path,
...
+
+  /* check if we have a separate .key file */
+  cert = g_tls_certificate_new_from_files (cert_path, key_path, error);
+  if (cert)
     {
-      g_set_error (error, G_IO_ERROR, g_io_error_from_errno (-r), "Failed to load %s: %s", cert_path, g_strerror (-r));
-      return NULL;
+      g_debug ("loaded separate cert %s and key %s", cert_path, key_path);
+    }
+  else if (g_error_matches (*error, G_FILE_ERROR, G_FILE_ERROR_NOENT))
```
Comment (allisonkarlitskaya) [inline src/ws/cockpitcertificate.c]: The error handling in the glib case is so much nicer...

You shouldn't be using `*error` in this way . It's possible that someone calls `cockpit_certificate_load()` with `error` set to `NULL`.  You should make your own `my_error` or something for this sort of thing and propagate it at the end using `g_propagate_error()`

File: src/ws/cockpitcertificate.c [hunk 14]
```diff
@@ -380,21 +380,39 @@ cockpit_certificate_load (const gchar *cert_path,
...
+      r = cockpit_certificate_parse (cert_path, &certs, &key);
+      if (r < 0)
+        {
+          g_set_error (error, G_IO_ERROR, g_io_error_from_errno (-r), "Failed to load %s: %s", cert_path, g_strerror (-r));
+          return NULL;
+        }
+
+      /* Gio only has constructors for parsing certs and key from one string, so combine them */
+      combined = g_strconcat (certs, key, NULL);
+      cert = g_tls_certificate_new_from_pem (combined, -1, error);
```
Comment (allisonkarlitskaya) [inline src/ws/cockpitcertificate.c]: Did we still not manage to move to `g_tls_certificate_new_from_file()` here?

Comment (martinpitt) [reply src/ws/cockpitcertificate.c]: This is an unrelated change, and requires some care. I filed issue #13411 for this with some thoughts, I'll work on this in a separate PR.

File: src/common/cockpitwebcertificate.c (hunk 9 above)
Comment (martinpitt) [reply src/common/cockpitwebcertificate.c]: Good point -- we currently call it from cockpit_certificate_load() and connection_crypto_init(), both of which currently accept arbitary cert paths. connection_crypto_init() is fine, it gets its input from cockpit_certificate_locate() which only spits out .crt/.cert. Same in src/ws/main.c.

I was a bit worried about remotectl when calling it with several PEM files. But cockpit_certificate_combine() fixes the target path to *.cert", and only that gets loaded, so it should be fine.

File: src/tls/connection.c (hunk 11 above)
Comment (martinpitt) [reply src/tls/connection.c]: It is -- gnutls_certificate_set_x509_key_file() fails with `GNUTLS_E_FILE_ERROR` if the key file does not exist.

File: src/tls/connection.c (hunk 12 above)
Comment (martinpitt) [reply src/tls/connection.c]: Yes, the `if`s can go away once _key_path asserts, and we only need to handle the ENOENT case.

File: src/ws/cockpitcertificate.c (hunk 13 above)
Comment (martinpitt) [reply src/ws/cockpitcertificate.c]: That's why I added the `g_assert (error)`, but indeed with propagation that's nicer. Thanks!

File: src/common/cockpitwebcertificate.c (hunk 9 above)
Comment (martinpitt) [reply src/common/cockpitwebcertificate.c]: Changed to `errx()`, to get an useful message.

File: src/tls/connection.c (hunk 10 above)
Comment (martinpitt) [reply src/tls/connection.c]: Changed so that it can't be NULL any more.

**Comment by martinpitt** [comment]
@allisonkarlitskaya : Reworked according to your comments (good ones, thanks!).

File: src/common/test-webcertificate.c [hunk 15]
```diff
@@ -94,13 +94,30 @@ test_locate (void)
...
+  path = cockpit_certificate_key_path ("/etc/cockpit/ws-certs.d/50-good.cert");
+  g_assert_cmpstr (path, ==, "/etc/cockpit/ws-certs.d/50-good.key");
+  g_free (path);
+  path = cockpit_certificate_key_path ("a.cert");
+  g_assert_cmpstr (path, ==, "a.key");
+  g_free (path);
+  path = cockpit_certificate_key_path ("a.crt");
+  g_assert_cmpstr (path, ==, "a.key");
+  g_free (path);
+}
```
Comment (allisonkarlitskaya) [inline src/common/test-webcertificate.c]: You could test the aborting case with `fork()` if you really wanted... Not saying you should...

File: src/tls/connection.c [hunk 16]
```diff
@@ -790,10 +791,18 @@ connection_crypto_init (const char *certfile,
   if (ret != GNUTLS_E_SUCCESS)
     errx (EXIT_FAILURE, "gnutls_certificate_allocate_credentials failed: %s", gnutls_strerror (ret));
 
-  if (keyfile)
-    ret = gnutls_certificate_set_x509_key_file (parameters.x509_cred, certfile, keyfile, GNUTLS_X509_FMT_PEM);
-  else
-    ret = set_x509_key_from_combined_file (parameters.x509_cred, certfile);
+  /* check if we have a separate key file */
+  keyfile = cockpit_certificate_key_path (certfile);
+  assert (keyfile);
```
Comment (allisonkarlitskaya) [inline src/tls/connection.c]: cute.

File: src/tls/connection.c [hunk 17]
```diff
@@ -790,10 +791,18 @@ connection_crypto_init (const char *certfile,
...
+  ret = gnutls_certificate_set_x509_key_file (parameters.x509_cred, certfile, keyfile, GNUTLS_X509_FMT_PEM);
+
+  /* if not, fall back to combined file */
+  if (ret == GNUTLS_E_FILE_ERROR)
```
Comment (allisonkarlitskaya) [inline src/tls/connection.c]: hm.  This could also be a problem with the cert file, but I guess we'll see the same error again when we try to load the combined file...

Comment (martinpitt) [reply src/tls/connection.c]: Right, then we'll get the error message from the "combined" fallback.

**Comment by martinpitt** [comment]
> which should remove a bunch of code from the one place that this patch adds it...

This PR doesn't add that code, it just indents it once into the if() block.. That's why I think it's ok (and safer) to clean up in a follow-up. I also want to experiment a bit whether we can use a nicer GIO API than having to read the file ourselves.

**Comment by mmomasters** [comment]
Hi all, could it be possible to push this fix in 195.12 / 195.13 for Centos 7 users ?

Thank a lot !
