### PR TITLE
Fixed issue #18680  No "languages found" text is shown when languages are not found in the language modal

### LINKED ISSUE #18680: No "languages found" text is shown when languages are not found in the language modal
### Explain what happens

We should probably show an EmptyState with an EmptyText which explains that no languages are found.

image

### Version of Cockpit

_No response_

### Where is the problem in Cockpit?

None

### Server operating system

None

### Server operating system version

_No response_

### What browsers are you using?

_No response_

### System log

_No response_

### PR DESCRIPTION
**Pull request by shubhit7**
Fixes #18680 
Added "No results found" in case of languages are not found in the modal.
image

### CODE REVIEW

File: pkg/shell/shell-modals.jsx [hunk 1]
```diff
@@ -133,11 +134,29 @@ export const LangModal = () => {
...
-                                        return <MenuItem itemId={key} key={key} data-value={key}>{manifest.locales[key]}</MenuItem>;
-                                    })}
+                            {
+                                (() => {
+                                    const filteredLocales = Object.keys(manifest.locales || {})
+                                            .filter(key => !searchInput || manifest.locales[key].toLowerCase().includes(searchInput.toString().toLowerCase()));
+
+                                    if (filteredLocales.length === 0) {
+                                        return (
+                                            <MenuItem>
```
Comment (KKoukiou) [inline pkg/shell/shell-modals.jsx:144]: No need to use EmptyState. Just put the translated text inside the MenuItem directly. 
```
<MenuItem>
{_("No results found")}
</MenuItem>
```

https://www.patternfly.org/v4/components/menu#filtering-with-search-input

**Review by KKoukiou — CHANGES_REQUESTED** [review]

File: pkg/shell/shell-modals.jsx [hunk 2]
```diff
@@ -133,11 +133,27 @@ export const LangModal = () => {
...
```
Comment (KKoukiou) [inline pkg/shell/shell-modals.jsx:143]: This needs to have isDisabled property.

**Review by KKoukiou — CHANGES_REQUESTED** [review]
Last small fix needed. And can you please rebase and squash the commits?

File: pkg/shell/shell-modals.jsx (hunk 2 above)
Comment (KKoukiou) [reply pkg/shell/shell-modals.jsx:143]: You can indeed change the text, and color will be auto-adjusted when you use the isDisabled. And I think it's already correctly aligned.

Comment (shubhit7) [reply pkg/shell/shell-modals.jsx:143]: Yes I have tried it.
Actually it is being planned to fix the size of inside language box(one with grey borders), so for example if we are making it of height 150px, "No language found" text will be shown on the top left side of the box.
current

Instead we want it to be aligned to center, vertically and horizontally.
expected

So, I am planning to remove the MenuItem and use a div directly with some inline css applied to it.
Other option is to use EmptyState component.

Comment (KKoukiou) [reply pkg/shell/shell-modals.jsx:143]: No please don't that. The way you do it right now is correct and according to the PF4 docs. https://www.patternfly.org/v4/components/select/#grouped-typeahead

Comment (KKoukiou) [reply pkg/shell/shell-modals.jsx:143]: In order to fix the jumping issue, better give the whole modal body a higher height, rather than giving the empty state menuitem a bigger height. Does this make sense @shubhit7 ?

Comment (shubhit7) [reply pkg/shell/shell-modals.jsx:143]: If we give the whole modal a higher height, the jumping issue will still be there as jumping is happening due the language box which is inside. 
So we need to give this language box(one with grey borders) a higher fixed height, once this is done we have to give the height as 100% to its children as this box acts as container of menuitems.
I am not giving the empty state menuitem a bigger height, I am making them 100% which they will relatively adjust according to their container size.

I am not resolving the jumping issue in this PR, here I am just suggesting to go ahead with EmptyState component inside MenuItem, that is pretty much it.
So that I can change the heights of these in a different PR.

Comment (shubhit7) [reply pkg/shell/shell-modals.jsx:143]: @KKoukiou There is only a slight change.
Instead of menuitem we can also directly use:
`return (
<EmptyState>
    No match
</EmptyState>
)
`

Comment (KKoukiou) [reply pkg/shell/shell-modals.jsx:143]: The Menu element creates a `<ul>`  HTML tag. MenuItem is `<li>`
The only valid element as a child of ul is the li. See https://stackoverflow.com/questions/11755628/can-i-use-div-as-a-direct-child-of-ul

By skipping the usage of MenuItem you essentially create invalid CSS. If you want to center align the text use the alignment classes from https://www.patternfly.org/v4/utilities/alignment#basic.

If you want to specify the height of the menu do it with custom CSS.

**Review by KKoukiou — APPROVED** [review]

**Review by garrett — APPROVED** [review]
:+1: LGTM (looks good to me) too! Thanks, @shubhit7.

File: pkg/shell/shell-modals.jsx [hunk 3]
```diff
@@ -139,11 +139,27 @@ export const LangModal = () => {
...
                         <MenuList>
-                            {Object.keys(manifest.locales || { })
-                                    .filter(key => !searchInput || manifest.locales[key].toLowerCase().includes(searchInput.toString().toLowerCase()))
-                                    .map(key => {
-                                        return <MenuItem itemId={key} key={key} data-value={key}>{manifest.locales[key]}</MenuItem>;
-                                    })}
+                            {
+                                (() => {
+                                    const filteredLocales = Object.keys(manifest.locales || {})
+                                            .filter(key => !searchInput || manifest.locales[key].toLowerCase().includes(searchInput.toString().toLowerCase()));
```
Comment (cockpituous) [inline pkg/shell/shell-modals.jsx:145]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18689-20230427-142709-3543de05-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/shell/shell-modals.jsx [hunk 4]
```diff
@@ -139,11 +139,27 @@
...
+
+                                    if (filteredLocales.length === 0) {
+                                        return (
+                                            <MenuItem isDisabled>
+                                                {_("No languages match")}
+                                            </MenuItem>
+                                        );
```
Comment (cockpituous) [inline pkg/shell/shell-modals.jsx:152]: These 5 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18689-20230427-142709-3543de05-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)
