### PR TITLE
common: Fix crash with unsupported HTTP methods

### LINKED ISSUE #19997: Segfault on unsupported HTTP method
### Explain what happens

Since the 2024-02-08 I get spammed by this error.  
Probably because of my upgrade from `glibc` `2.38` to `2.39`.

### Version of Cockpit

310.2

### Where is the problem in Cockpit?

Unknown or not applicable

### Server operating system

Arch Linux

### Server operating system version

latest

### What browsers are you using?

Chrome

### System log

```shell
Feb 11 13:03:30 servername systemd[1]: Started Cockpit Web Service https instance factory (PID 161002/UID 973).
Feb 11 13:03:30 servername systemd[1]: Starting Socket for Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855...
Feb 11 13:03:30 servername systemd[1]: Listening on Socket for Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
Feb 11 13:03:30 servername systemd[1]: Started Cockpit Web Service https instance e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.
Feb 11 13:03:30 servername systemd[1]: cockpit-wsinstance-https-factory@97-161002-973.service: Deactivated successfully.
Feb 11 13:03:34 servername cockpit-ws[161724]: received unsupported HTTP method
Feb 11 13:03:34 servername kernel: cockpit-ws[161724]: segfault at 0 ip 00007df1d289b82b sp 00007fffdfdb07b8 error 4 in libc.so.6[7df1d2766000+15b000] likely on CPU 6 (core 3, socket 0)
Feb 11 13:03:34 servername kernel: Code: f8 77 c3 66 2e 0f 1f 84 00 00 00 00 00 66 90 f3 0f 1e fa c4 41 01 ef ff 89 f8 09 f0 c1 e0 14 3d 00 00 00 f8 0f 87 25 03 00 00 <c5> fe 6f 07 c5 fd 74 0e c5 85 74 d0 c5 >
Feb 11 13:03:34 servername cockpit-ws[161724]: cockpit_web_response_set_method: assertion 'g_strcmp0 (method, "GET") == 0 || g_strcmp0 (method, "HEAD") == 0' failed
Feb 11 13:03:34 servername systemd[1]: Started Process Core Dump (PID 161733/UID 0).
Feb 11 13:03:34 servername systemd-coredump[161734]: [🡕] Process 161724 (cockpit-ws) of user 972 dumped core.
                                                       
                                                       Stack trace of thread 161724:
                                                       #0  0x00007df1d289b82b n/a (libc.so.6 + 0x15982b)
                                                       #1  0x000063ef6d559438 n/a (cockpit-ws + 0x20438)
                                                       #2  0x000063ef6d55cd85 n/a (cockpit-ws + 0x23d85)
                                                       #3  0x00007df1d2af4f69 n/a (libglib-2.0.so.0 + 0x59f69)
                                                       #4  0x00007df1d2b533a7 n/a (libglib-2.0.so.0 + 0xb83a7)
                                                       #5  0x00007df1d2af5b97 g_main_loop_run (libglib-2.0.so.0 + 0x5ab97)
                                                       #6  0x000063ef6d542976 n/a (cockpit-ws + 0x9976)
                                                       #7  0x00007df1d2767cd0 n/a (libc.so.6 + 0x25cd0)
                                                       #8  0x00007df1d2767d8a __libc_start_main (libc.so.6 + 0x25d8a)
                                                       #9  0x000063ef6d543145 n/a (cockpit-ws + 0xa145)
                                                       
                                                       Stack trace of thread 161729:
                                                       #0  0x00007df1d284888d syscall (libc.so.6 + 0x10688d)
                                                       #1  0x00007df1d2b4ed13 g_cond_wait_until (libglib-2.0.so.0 + 0xb3d13)
                                                       #2  0x00007df1d2ac0185 n/a (libglib-2.0.so.0 + 0x25185)
                                                       #3  0x00007df1d2ac02e7 g_async_queue_timeout_pop (libglib-2.0.so.0 + 0x252e7)
                                                       #4  0x00007df1d2b293be n/a (libglib-2.0.so.0 + 0x8e3be)
                                                       #5  0x00007df1d2b26a45 n/a (libglib-2.0.so.0 + 0x8ba45)
                                                       #6  0x00007df1d27cd55a n/a (libc.so.6 + 0x8b55a)
                                                       #7  0x00007df1d284aa3c n/a (libc.so.6 + 0x108a3c)
                                                       
                                                       Stack trace of thread 161727:
                                                       #0  0x00007df1d284888d syscall (libc.so.6 + 0x10688d)
                                                       #1  0x00007df1d2b4e337 g_cond_wait (libglib-2.0.so.0 + 0xb3337)
                                                       #2  0x00007df1d2ac01b4 n/a (libglib-2.0.so.0 + 0x251b4)
                                                       #3  0x00007df1d2b28ace n/a (libglib-2.0.so.0 + 0x8dace)
                                                       #4  0x00007df1d2b26a45 n/a (libglib-2.0.so.0 + 0x8ba45)
                                                       #5  0x00007df1d27cd55a n/a (libc.so.6 + 0x8b55a)
                                                       #6  0x00007df1d284aa3c n/a (libc.so.6 + 0x108a3c)
                                                       
                                                       Stack trace of thread 161728:
                                                       #0  0x00007df1d283d0bf __poll (libc.so.6 + 0xfb0bf)
                                                       #1  0x00007df1d2b532f6 n/a (libglib-2.0.so.0 + 0xb82f6)
                                                       #2  0x00007df1d2af3162 g_main_context_iteration (libglib-2.0.so.0 + 0x58162)
                                                       #3  0x00007df1d2af31b2 n/a (libglib-2.0.so.0 + 0x581b2)
                                                       #4  0x00007df1d2b26a45 n/a (libglib-2.0.so.0 + 0x8ba45)
                                                       #5  0x00007df1d27cd55a n/a (libc.so.6 + 0x8b55a)
                                                       #6  0x00007df1d284aa3c n/a (libc.so.6 + 0x108a3c)
                                                       ELF object binary architecture: AMD x86-64
Feb 11 13:03:34 servername systemd[1]: cockpit-wsinstance-https@e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.service: Main process exited, code=dumped, status=11/SEGV
Feb 11 13:03:34 servername systemd[1]: cockpit-wsinstance-https@e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855.service: Failed with result 'core-dump'
```

### PR DESCRIPTION
**Pull request by martinpitt**
Commit 96335a440c15859 introduced a crash: Requesting any HTTP method
other than "GET" or "HEAD" segfaulted cockpit_web_response_error() as
`self->method` is NULL. That could happen because
cockpit_web_response_set_method()` refused to set unsupported ones.

Improve the /web-response/head test to set the "HEAD" method right away
with `cockpit_web_response_new()`, instead of overwriting setup()'s
"GET" default.

That was the only consumer of `cockpit_web_response_set_method()`. This
method is rather dubious, as the method should only be set in the
constructor. So eliminate it and move the check into the constructor.

Keep the provided method value also for unknown ones.

Change the critical to a warning, as it's not an internal program error.

Fixes #19997

----

After this lands, we also need to backport this to rhel-8.

The new unit test reproduces the crash (without the fix). The new integration test also fails:
```
+ curl -k --verbose -X PATCH https://localhost:9000/ 2>&1
subprocess.CalledProcessError: Command '['env', '-u', 'LANGUAGE', 'LC_ALL=C', 'ssh', '-p', '2201', '-o', 'StrictHostKeyChecking=no', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'IdentitiesOnly=yes', '-o', 'BatchMode=yes', '-o', 'PKCS11Provider=none', '-o', 'LogLevel=ERROR', '-l', 'root', '127.0.0.2', '-o', 'ControlPath=/tmp/.cockpit-test-resources/ssh-%h-%p-%r-71851', 'set -e;', 'curl -k --verbose -X PATCH https://localhost:9000/ 2>&1']' returned non-zero exit status 52.
```

and that also crashes the cockpit-ws process (`m.spawn()`ed, not run from systemd) which would fail the next check.

### CODE REVIEW

**Comment by allisonkarlitskaya** [comment]
I thought that the webserver already rejected anything other than GET/HEAD requests.  Oops :(

**Comment by allisonkarlitskaya** [comment]
Ah, indeed!  It *does* reject them, but then it issues a "delayed reply" error for them, and that code checks the method!

**Review by allisonkarlitskaya — COMMENTED** [review]
I think I'd prefer to remove the check from the setter... it's weird and unexpected that this value ends up being NULL...

**Comment by martinpitt** [comment]
OK, good point -- src/common/cockpitwebserver.c always stores the actual method, it's only inside src/common/cockpitwebresponse.c where we hide invalid ones. It looks safe to always store it, and also change it to a warning, as it's not an internal program error.

**Comment by martinpitt** [comment]
@allisonkarlitskaya I reworked this a bit more now with some additional cleanup.

File: src/common/cockpitwebresponse.c [hunk 1]
```diff
@@ -234,7 +234,11 @@ cockpit_web_response_new (GIOStream *io,
   self->url_root = NULL;
   self->full_path = g_strdup (path);
   self->path = self->full_path;
-  cockpit_web_response_set_method (self, method);
+
+  g_assert (method != NULL);
+  if (!g_str_equal (method, "GET") && !g_str_equal (method, "HEAD"))
+    g_warning("Method %s is not supported", method);
```
Comment (allisonkarlitskaya) [inline src/common/cockpitwebresponse.c:240]: I don't like this.  Someone trying a random method on a public-listening webserver shouldn't end up in the journal... just get rid of this.

**Review by allisonkarlitskaya — CHANGES_REQUESTED** [review]
Around like 1171 in `common/cockpitwebresponse.c` we check if the method is equal to `"GET"` to avoid adding a body.  Probably we should change that to checking that the method is not equal to `"HEAD"`.

File: src/common/cockpitwebresponse.c (hunk 1 above)
Comment (martinpitt) [reply src/common/cockpitwebresponse.c]: Ack, dropped. I also flipped the GET/HEAD check as you suggested above, so that `PATCH` error responses now have a body.

**Review by allisonkarlitskaya — APPROVED** [review]
This looks pretty nice now, thanks!

**Comment by martinpitt** [comment]
rhel-8 backport: 20009
