### PR TITLE
websocket: Fix unaligned access in send_prefixed_message_rfc6455()

### LINKED ISSUE #13434: test-websocket test crashes on sparc64 due to unaligned access
On Debian unstable, ```cockpit``` fails to build from source on sparc64 due to the testsuite crashing in ```test-websocket```:

```
ERROR: test-websocket
=====================

# ./tools/tap-driver --test-name test-websocket --log-file test-websocket.log --trs-file test-websocket.trs --color-tests no --enable-hard-errors yes --expect-failure no -- sh -c "$0" "$@" --tap ./test-websocket
# random seed: R02S40d838f626fc3b1116de4331736d0b0c
1..40
# Start of web-socket tests
ok 1 /web-socket/parse-url
ok 2 /web-socket/parse-url-no-out
ok 3 /web-socket/parse-url-bad
ok 4 /web-socket/parse-url-no-path
ok 5 /web-socket/parse-url-with-user
ok 6 /web-socket/parse-req
ok 7 /web-socket/parse-req-no-out
ok 8 /web-socket/parse-req-not-enough
ok 9 /web-socket/parse-req-bad
ok 10 /web-socket/parse-status
ok 11 /web-socket/parse-status-no-out
ok 12 /web-socket/parse-status-not-enough
ok 13 /web-socket/parse-status-bad
ok 14 /web-socket/parse-version-1-0
ok 15 /web-socket/parse-version-1-1
ok 16 /web-socket/parse-headers
ok 17 /web-socket/parse-headers-no-out
# WebSocket-DEBUG: received invalid header line: Header1 value3


# WebSocket-DEBUG: received invalid header
ok 18 /web-socket/parse-headers-bad
ok 19 /web-socket/parse-headers-not-enough
ok 20 /web-socket/header-equals
ok 21 /web-socket/header-contains
ok 22 /web-socket/header-empty
# WebSocket-DEBUG: starting input source
# WebSocket-DEBUG: waiting for more handshake data
# WebSocket-DEBUG: starting input source
# WebSocket-DEBUG: waiting for more handshake data
# WebSocket-DEBUG: starting output source
# WebSocket-DEBUG: queued rfc6455 handshake request
# WebSocket-DEBUG: sent frame
# WebSocket-DEBUG: starting output source
# WebSocket-DEBUG: queued response to rfc6455 handshake
# WebSocket-DEBUG: open: responded to handshake
# WebSocket-DEBUG: stopping output source
# WebSocket-DEBUG: sent frame
# WebSocket-DEBUG: verified rfc6455 handshake
# WebSocket-DEBUG: open: handshake completed
# WebSocket-DEBUG: stopping output source
# WebSocket-DEBUG: stopping input source
# WebSocket-DEBUG: closing io stream
# WebSocket-DEBUG: stopping input source
# WebSocket-DEBUG: closing io stream
ok 23 /web-socket/handshake
# WebSocket-DEBUG: starting input source
# WebSocket-DEBUG: waiting for more handshake data
# WebSocket-DEBUG: starting input source
# WebSocket-DEBUG: waiting for more handshake data
# WebSocket-DEBUG: starting output source
# WebSocket-DEBUG: queued rfc6455 handshake request
# WebSocket-DEBUG: closed: completed io stream close
# WebSocket-DEBUG: closed: completed io stream close
# WebSocket-DEBUG: sent frame
# WebSocket-DEBUG: starting output source
# WebSocket-DEBUG: queued response to rfc6455 handshake
# WebSocket-DEBUG: open: responded to handshake
# WebSocket-DEBUG: stopping output source
# WebSocket-DEBUG: sent frame
# WebSocket-DEBUG: verified rfc6455 handshake
# WebSocket-DEBUG: open: handshake completed
# WebSocket-DEBUG: stopping output source
Bus error
```

Backtrace:

```
Thread 1 "test-websocket" received signal SIGBUS, Bus error.
0x000001000000ebf8 in send_prefixed_message_rfc6455 (self=0x10000138460, flags=<optimized out>, opcode=<optimized out>, prefix=0x0, prefix_len=<optimized out>, 
    payload=0x10000121860 "this is a test", payload_len=<optimized out>) at src/websocket/websocketconnection.c:434
434           mask = outer + bytes->len;
(gdb) bt
#0  0x000001000000ebf8 in send_prefixed_message_rfc6455
    (self=0x10000138460, flags=<optimized out>, opcode=<optimized out>, prefix=0x0, prefix_len=<optimized out>, payload=0x10000121860 "this is a test", payload_len=<optimized out>) at src/websocket/websocketconnection.c:434
#1  0x0000010000010268 in web_socket_connection_send (self=0x10000138460, type=<optimized out>, prefix=<optimized out>, message=0x10000129430)
    at src/websocket/websocketconnection.c:1754
#2  0x000001000000992c in test_send_client_to_server (test=0x10000129ca0, data=0x0) at src/websocket/test-websocket.c:607
#3  0xffff8001005a475c in  () at /usr/lib/sparc64-linux-gnu/libglib-2.0.so.0
(gdb)
```

Full build log in: https://buildd.debian.org/status/fetch.php?pkg=cockpit&arch=sparc64&ver=210-1&stamp=1578525899&raw=0

Note: There a multiple crashes due to unaligned access, just grep the build log for "Bus error".

Access to a fast sparc64 porterbox running Debian unstable is available through the GCC compile farm, see: https://gcc.gnu.org/wiki/CompileFarm

Debian also provides a sparc64 porterbox available to all Debian Developers and users with a Debian guest account.

### PR DESCRIPTION
**Pull request by glaubitz**
Fixes #13434

### CODE REVIEW

File: src/websocket/websocketconnection.c [hunk 1]
```diff
@@ -430,9 +430,10 @@ send_prefixed_message_rfc6455 (WebSocketConnection *self,
    */
   if (!self->pv->server_side)
     {
+      guint32 rand = g_random_int ();
       outer[1] |= 0x80;
       mask = outer + bytes->len;
-      * ((guint32 *)mask) = g_random_int ();
+      memcpy (mask, &rand , sizeof (guint8));
```
Comment (martinpitt) [inline src/websocket/websocketconnection.c]: Thanks @glaubitz for tracking that down! But I wonder, why does this only copy the first 8 bits instead of all 32? Shouldn't it be `sizeof guint32`?

Comment (glaubitz) [reply src/websocket/websocketconnection.c]: The target variable ```mask``` is only 8 bits (```guint8```, see at the top the function), so copying 32 bits would result in memory being overwritten.

Comment (glaubitz) [reply src/websocket/websocketconnection.c]: Hmm, although now I'm a bit confused why it worked on the other architectures in the first place without crashing when a 32-bit value is written to a 8-bit destination.

**Comment by martinpitt** [comment]
Due to only copying 8 bytes instead of 32, valgrind now complains about uninitialized memory:
```
==1889== Syscall param socketcall.sendto(msg) points to uninitialised byte(s)
==1889==    at 0x100C7518E: __libc_send (send.c:28)
==1889==    by 0x100C7518E: send (send.c:23)
==1889==    by 0x1008E9E46: g_socket_send_with_timeout (gsocket.c:3263)
==1889==    by 0x1008E9E46: g_socket_send_with_blocking (gsocket.c:3366)
==1889==    by 0x12967C: on_web_socket_output (websocketconnection.c:1046)
==1889==    by 0x100AC5897: g_main_dispatch (gmain.c:3189)
==1889==    by 0x100AC5897: g_main_context_dispatch (gmain.c:3854)
==1889==    by 0x100AC5C87: g_main_context_iterate.isra.26 (gmain.c:3927)
==1889==    by 0x100AC5D1B: g_main_context_iteration (gmain.c:3988)
==1889==    by 0x1132A3: test_basic (test-websocketstream.c:168)
==1889==    by 0x100AED39D: test_case_run (gtestutils.c:2597)
==1889==    by 0x100AED39D: g_test_run_suite_internal (gtestutils.c:2685)
==1889==    by 0x100AED143: g_test_run_suite_internal (gtestutils.c:2697)
==1889==    by 0x100AED861: g_test_run_suite (gtestutils.c:2772)
==1889==    by 0x100AED880: g_test_run (gtestutils.c:2007)
==1889==    by 0x112C07: main (test-websocketstream.c:380)
==1889==  Address 0x1012dea03 is 3 bytes inside a block of size 32 alloc'd
```

Indeed `guint8*` is a confusing/wrong datatype for `mask`, and I suppose it was only chosen so that the 4 bytes could be written to any byte position in the buffer. The buffer itself is large enough, and on the next line it also advances the length by 4 bytes. I. e. I still think that `sizeof (guint32)` is right.

**Comment by glaubitz** [comment]
Okay, that makes sense. Let me test.

**Comment by glaubitz** [comment]
Works, pushed with updated buffer size.

**Comment by glaubitz** [comment]
Thanks. Btw, on x86_64, the ```memcpy()``` is completely optimized away if I remember correctly. So there should not be any performance impact on any architecture which has less stricter alignment requirements.
