### PR TITLE
common: Fix deadlock in channel pressure handling

### LINKED ISSUE #12580: spawned processes with lots of output get stuck
Cockpit version: 199
OS: Fedora 29, Fedora 30
Page: Session Recording

cockpit-session-recording uses the journal.journalctl method to retrieve a list of journal entries, process them, then present a list of Recordings in the UI. Intermittently(about 40% of the time) when refreshing the main /session-recording page, only a subset of the total entries are returned to the .stream(data) handler. When this happens the .done() handler never is called. In our code we have:

        let matches = ["_EXE=/usr/bin/tlog-rec-session",
            "_EXE=/usr/bin/tlog-rec", "+",
            "_COMM=tlog-rec", "+",
            "_COMM=tlog-rec-session"];

        let options = {follow: false, count: "all", merge: true};

        this.journalctl = Journal.journalctl(matches, options)
                .fail(this.journalctlError)
                .stream(this.journalctlIngest)
                .done(() => {
		    console.log('Done!');
                });
    }

On my test system I have recordings(which consists of numerous back-to-back journal entries) containing a large amount of flooded output. I believe that cockpit.spawn(), when called by journalctl, is not processing all of the journalctl command JSON output. This leads to the lack of complete entries returned through journalctl, though I could not say why it happens only intermittently.

I also tried setting different cockpit.spawn option `batch` and `latency` values but the problem persists.

Steps to reproduce

1. dnf install tlog
2. tlog-rec -w journal cat /usr/share/dict/linux.words
3. In cockpit module code:

        let cmd = ["journalctl", "-q", "--lines=all", "_COMM=tlog-rec", "--output=json"];
        cockpit.spawn(cmd)
                .stream((data) => {
                    console.log(data);   /* If data contains Zyzzogeton, all entries were returned */
                    if (data.includes("Zyzzogeton")) {
                        console.log('Found string');
                    }
                })
                .done(() => {
                    console.log('Done!');
                });

4. Intermittently, not all of the output will be provided in .stream(data) and the .done() handler is never called

I can provide more information if needed, or feel free to contact me on IRC 'justintime'

Downstream report: https://bugzilla.redhat.com/show_bug.cgi?id=1751783

### PR DESCRIPTION
**Pull request by martinpitt**
When a channel applies back-pressure to its input because its output
queue is getting too large, it relies on the consumer to acknowledge the
reads by ponging to the pings that the channel sent out.

However, it can happen that the last ping was sent for a sequence number
*before* the one that the channel expects for lifting the pressure. Then
the receiver could drain the output queue and dutifully respond to all
pings, but the last sequence number would still be smaller than the
treshold for lifting the pressure. But the channel isn't sending
anything else either and thus never generates new pings.

Fix this by sending an additional ping when going into pressure mode, to
ensure that the last pong sequence number is within the out_window
again.

This can also be reproduced/investigated with this test-spawn-proc unit
test:
```js
QUnit.only("stream large output - find", function (assert) {
    const done = assert.async();
    assert.expect(2);

    cockpit.spawn(["find", "/"], { err: "ignore" })
            .stream(function(resp) {
                console.log("got block", resp.length);
            })
            .then(function(resp) {
                assert.equal(resp, "", "no done data");
            })
            .always(function() {
                assert.equal(this.state(), "resolved", "didn't fail");
                done();
            });
});
```
But this is not appropriate for actually committing -- the find often
fails at the end, and takes too many IO resources for a unit test. The
integration test confirms the fix, though.

Fixes #12580
https://bugzilla.redhat.com/show_bug.cgi?id=1751783

 - [x] Builds on top of various unit test fixes: PR #14075 
 - [x] Update PR reference in integration test
 - [x] Revert the order again and beautify the code

### CODE REVIEW

**Comment by martinpitt** [comment]
I talked this over with @stefwalter , and he confirmed that this is a valid fix. The actual new flooding test in check-terminal succeeds everywhere, I just botched the subsequent checks. I can't run this locally due to chromium changes. I have a fix prepared locally, but I also still want to reformat the code a bit.

**Comment by martinpitt** [comment]
PR #14075 landed, and I applied the code clenaup. @stefwalter, do you want to officially review that?

**Comment by mvollmer** [comment]
Nice! This makes sense to me, for what it's worth.

**Comment by martinpitt** [comment]
@mvollmer brought up that it's not clear that we avoid ping/pong loops with the same sequence number. I changed the level to edge triggering to ensure this.

File: src/common/cockpitchannel.c [hunk 1]
```diff
@@ -351,14 +351,20 @@ cockpit_channel_actual_send (CockpitChannel *self,
...
       g_return_if_fail (G_MAXINT64 - size > priv->out_sequence);
 
       /* How many bytes have been sent (queued) */
       out_sequence = priv->out_sequence + size;
 
-      /* Every CHANNEL_FLOW_PING bytes we send a ping */
-      if (out_sequence / CHANNEL_FLOW_PING != priv->out_sequence / CHANNEL_FLOW_PING)
+      /* If we've sent more than the window, we just got under pressure;
+       * do an edge trigger instead of level trigger to avoid ping/signal loops */
+      under_pressure = (priv->out_sequence <= priv->out_window) && (out_sequence > priv->out_window);
```
Comment (stefwalter) [inline src/common/cockpitchannel.c:363]: If this is edge triggered then the variable name needs to change. The variable is named for a level.

File: src/common/cockpitchannel.c [hunk 2]
```diff
@@ -367,9 +373,9 @@ cockpit_channel_actual_send (CockpitChannel *self,
...
         }
 
-      /* If we've sent more than the window, apply back pressure */
       priv->out_sequence = out_sequence;
-      if (priv->out_sequence > priv->out_window)
+
+      if (under_pressure)
         {
           g_debug ("%s: sent too much data without acknowledgement, emitting back pressure until %"
                    G_GINT64_FORMAT, priv->id, priv->out_window);
```
Comment (stefwalter) [inline src/common/cockpitchannel.c:381]: That means this emit_pressure call here has also changed from level triggered to edge triggered. Is that in line with all the other uses of this function call? Worth doing a check.

Comment (stefwalter) [reply src/common/cockpitchannel.c:381]: > src/bridge/cockpitpacketchannel.c:    cockpit_flow_emit_pressure (COCKPIT_FLOW (self), FALSE);
> src/bridge/cockpitpacketchannel.c:    cockpit_flow_emit_pressure (COCKPIT_FLOW (self), TRUE);

Edge triggered. ^^

> src/bridge/cockpitstream.c:            cockpit_flow_emit_pressure (COCKPIT_FLOW (self), FALSE);
> src/bridge/cockpitstream.c:    cockpit_flow_emit_pressure (COCKPIT_FLOW (self), TRUE);

Edge triggered ^^

> src/common/cockpitchannel.c:        cockpit_flow_emit_pressure (COCKPIT_FLOW (self), FALSE);

This other call in CockpitChannel is edge triggered. But may have an off by one on line 248. I need to double check this.

> src/common/cockpitchannel.c:          cockpit_flow_emit_pressure (COCKPIT_FLOW (self), TRUE);

This is the one we're changing.

> src/common/cockpitpipe.c:    cockpit_flow_emit_pressure (COCKPIT_FLOW (self), FALSE);
> src/common/cockpitpipe.c:    cockpit_flow_emit_pressure (COCKPIT_FLOW (self), TRUE);

Edge triggered ^^

src/common/cockpitwebresponse.c:        cockpit_flow_emit_pressure (COCKPIT_FLOW (self), FALSE);
src/common/cockpitwebresponse.c:    cockpit_flow_emit_pressure (COCKPIT_FLOW (self), TRUE);

Edge triggered ^^

src/websocket/websocketconnection.c:    cockpit_flow_emit_pressure (COCKPIT_FLOW (self), FALSE);
src/websocket/websocketconnection.c:    cockpit_flow_emit_pressure (COCKPIT_FLOW (self), TRUE);

Edge triggered ^^

Comment (martinpitt) [reply src/common/cockpitchannel.c:381]: As we just figured out, all other pressure calls use edge triggering already, so that gets cockpitchannel.c in line with the others.

File: src/common/cockpitchannel.c (hunk 1 above)
Comment (martinpitt) [reply src/common/cockpitchannel.c]: Fair enough. I renamed it to `trigger_pressure`.
