### PR TITLE
storage: Highlight side panel new items

### LINKED ISSUE #10059: storage: hard to notice a new volume group (or generally another resource, see lvolumes) that was just created
During a usability test on the storage page, where the participants were asked to create a volume, a lot of participants were able to create a volume group, but then failed to find the item they had created in the list.

### PR DESCRIPTION
**Pull request by marusak**
Peek 2022-03-18 08-02

Fixes #10059

### CODE REVIEW

**Comment by garrett** [comment]
IIRC, the sidepanel rows are implemented with flex, whereas the table rows are implemented with tables?

The animation was intended for table rows. If it adjusts display in the animation, then it would have an affect like in the video/GIF above, as the display type would change.

(I can look into this tomorrow. It's a bit too late for me to do anything other than speculate in a comment like this. 😉)

**Comment by marusak** [comment]
> IIRC, the sidepanel rows are implemented with flex, whereas the table rows are implemented with tables?

correct, both statements

Do you have a good idea how this could work also with flex?

**Comment by garrett** [comment]
I'm working on this right now. I think I know what's up, but I'm building it in VMs for testing, as I don't want to accidentally nuke anything on my work laptop. :sweat_smile: (Therefore, it's a bit slower... but it is safer.)

I'll push up a fix as a commit in this PR if/when I have one.

**Comment by marusak** [comment]
Thank you @garrett! Now it works superbly - I have updated the gif in the first comment.

**Comment by marusak** [comment]
oops, I cause some oops :)

File: pkg/storaged/side-panel.jsx [hunk 1]
```diff
@@ -32,12 +32,28 @@ export class SidePanel extends React.Component {
...
     }
 
     render() {
         let show_all_button = null;
-        let rows = this.props.rows;
+        let rows = this.props.rows.filter(!!row);
+
+        // Find new items for animations
+        const current_keys = [];
+        rows.forEach(row => { current_keys.push(row.key) });
```
Comment (martinpitt) [inline pkg/storaged/side-panel.jsx:45]: In case you have to push again: This is much nicer as a map operation:

    const current_keys = rows.map(row => row.key);

File: pkg/storaged/side-panel.jsx [hunk 2]
```diff
@@ -32,12 +32,28 @@ export class SidePanel extends React.Component {
...
+
+        if (JSON.stringify(this.current_rows_keys) !== JSON.stringify(current_keys)) {
+            if (this.current_rows_keys.length !== 0) {
+                const new_keys = current_keys.filter(key => this.current_rows_keys.indexOf(key) === -1);
+                if (new_keys.length)
+                    this.new_keys.push(...new_keys);
```
Comment (martinpitt) [inline pkg/storaged/side-panel.jsx:51]: This looks strange -- pushing a copy of an array onto itself? That gets dangerously close to [Russel's pararox](https://en.wikipedia.org/wiki/Russell%27s_paradox) and hence making the universe explode (or implode.. I always forget which :grinning: )

Joke aside, you mean something like "concat" here (except that this is not an inline modification). Can't you just do `this.new_keys = new_keys` here?

File: pkg/storaged/side-panel.jsx [hunk 3]
```diff
@@ -117,7 +138,7 @@ class SidePanelRow extends React.Component {
 
         return (
             <FlexItem data-testkey={this.props.testkey}
-                      className="sidepanel-row"
+                      className={"sidepanel-row" + (this.props.className ? " " + this.props.className : "")}
```
Comment (martinpitt) [inline pkg/storaged/side-panel.jsx:141]: It doesn't hurt to move the space to the initial `"side-panel-row "` string, and simplify this.

**Review by martinpitt — CHANGES_REQUESTED** [review]
Thanks!

File: pkg/storaged/side-panel.jsx (hunk 2 above)
Comment (martinpitt) [reply pkg/storaged/side-panel.jsx:51]: Illustration, in case it's not clear:

```node
> a = []
[]
> b = [1,2]
[ 1, 2 ]
> a.push(b)
1
> a
[ [ 1, 2 ] ]
> 
```

File: pkg/storaged/side-panel.jsx (hunk 1 above)
Comment (marusak) [reply pkg/storaged/side-panel.jsx:45]: Of yeah, I think I had there also some condition before and ha would lead o `.reduce()` but now this surely can be done with `map()`. I'll update

File: pkg/storaged/side-panel.jsx (hunk 2 above)
Comment (marusak) [reply pkg/storaged/side-panel.jsx:51]: > Joke aside, you mean something like "concat" here (except that this is not an inline modification). Can't you just do this.new_keys = new_keys here?

Same as for ListingTable: https://github.com/cockpit-project/cockpit/pull/17094#discussion_r826726870

I want to keep list of all items that were added after initial load. For that I keep global state of new items and only append into it. Otherwise I could just have local array of new keys for each render, but that might cause issues when more items are added one by one in quick succession

Comment (marusak) [reply pkg/storaged/side-panel.jsx:51]: > Illustration, in case it's not clear:

Not sure what it demonstrates. I need the spread operator exactly to avoid creating array of arrays as that is hell then to find element in.

Comment (martinpitt) [reply pkg/storaged/side-panel.jsx:51]: Oh, I wasn't aware of *that* usage of the spread operator. Your linked comment used `[...var]`, which is by and large "a copy of `var`", but this doesn't have the `[]` and thus is more like calling .push() with lots of arguments. That works fine (I just found it hard to read, but now I know it).

**Comment by marusak** [comment]
I need to refresh two pixel tests it seems :man_shrugging:

File: pkg/storaged/side-panel.jsx (hunk 1 above)
Comment (marusak) [reply pkg/storaged/side-panel.jsx]: done

File: pkg/storaged/side-panel.jsx (hunk 3 above)
Comment (marusak) [reply pkg/storaged/side-panel.jsx]: done

**Comment by martinpitt** [comment]
[unrelated failure](https://logs.cockpit-project.org/logs/pull-17143-20220321-062402-200e1966-arch/log.html#302-2), I sent PR #17156 to try and fix that.

**Review by martinpitt — APPROVED** [review]
I feel like the [stratis pixel test update](https://github.com/cockpit-project/pixel-test-reference/compare/6579d45fef970177293dc1c666530fb150476109..ac6d9ad037ca8939d6795834abf82b35c4039836) here is both unrelated and an ongoing flake. You yourself just updated its pixels a week ago in commit cb38ee82e59caff7da.

Nevertheless, LGTM if/once green. Thank you!

**Comment by marusak** [comment]
> I feel like the [stratis pixel test update](https://github.com/cockpit-project/pixel-test-reference/compare/6579d45fef970177293dc1c666530fb150476109..ac6d9ad037ca8939d6795834abf82b35c4039836) here is both unrelated and an ongoing flake. You yourself just updated its pixels a week ago in commit https://github.com/cockpit-project/cockpit/commit/cb38ee82e59caff7da0cebd62feaaf7c874c2bcf.

Yeah, I realized as well. It seems a bit odd that it fails on these two PRs which are very similar and not in any other
