### PR TITLE
cockpit: Work around bug in Firefox 146 and 147 re navigation

### LINKED ISSUE #22709: Reload loop in services page in Firefox v146+
### Explain what happens

1. Login to any Cockpit (Redhat) portal using Firefox
2. Go to Services page
3. Perpetual reload appearing to be js-triggered

**Actual results:**
The Services page is stuck in a reloading loop that never ends.
Other portal's sections are fine.

**Expected results:**
The Services page should load once and be usable.

Firefox v143 does not seem affected. Versions in-between have not been tested.

### Version of Cockpit

351

### Where is the problem in Cockpit?

Services page

### Server operating system

Fedora

### Server operating system version

42

### What browsers are you using?

Firefox
LibreWolf (same problem)

### System log

```shell

```

Edit: As suggested by @sacc-leo , a workaround would be to hit CTRL+R during the refreshing madness and it should stop. 
This will persist until the tab is closed. The problem comes back with new tabs.

### PR DESCRIPTION
**Pull request by mvollmer**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=2422331

Fixes #22709

### CODE REVIEW

File: pkg/lib/cockpit/_internal/location.ts [hunk 1]
```diff
@@ -124,7 +124,7 @@ export class Location {
 
         const query: string[] = [];
         if (options) {
-            for (const opt in options) {
+            for (const opt of Object.keys(options).sort()) {
```
Comment (martinpitt) [inline pkg/lib/cockpit/_internal/location.ts:127]: That's just for making URL building reproducible/predictable?

File: pkg/lib/cockpit/_internal/location.ts [hunk 2]
```diff
@@ -176,8 +176,20 @@ export class Location {
     go(path: Path, options?: Options) {
         if (this.#hash_changed)
             return;
-        const href = this.#href_for_go_or_replace(path, options);
-        window.location.hash = '#' + href;
+        const hash = '#' + this.#href_for_go_or_replace(path, options);
```
Comment (cockpituous) [inline pkg/lib/cockpit/_internal/location.ts:179]: This added line is not executed by any test.  [Details](https://logs-cockpit.apps.ocp.cloud.ci.centos.org/pull-22731-6e2345aa-20260105-115128-fedora-43-devel/Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/lib/cockpit/_internal/location.ts (hunk 1 above)
Comment (mvollmer) [reply pkg/lib/cockpit/_internal/location.ts:127]: Yes, we compare them below to see whether they are different, so they need to be in a canonical form.

**Comment by mvollmer** [comment]
So, any "legitimate" use of cockpit.location.go is also broken: Using it will reload the page with Firefox 146. I think we do most of our actual navigation with `<a href="#/foo">` links, and they don't seem to be affected. But we do use cockpit.location.go as well, of course.

Reloading a page should be fine, but it is slightly disruptive and of course expensive. But at least c-machines has interesting internal state (when downloading RHEL images) that gets lost during a page reload and of course the page that shows the download progress uses cockpit.location.go to get back to the main page...
