### PR TITLE
shell: Fix adding hosts with separate user name and/or ssh:// prefix

### LINKED ISSUE #17635: Add host does not work as expected when a ssh://host _and_ the username field are both used
### Explain what happens

1. Visit the host switcher
2. Add a new host
3. In the "Add a new host" dialog, use an SSH URI without a user, such as ssh://host
4. Put your username in the username field
5. Try to connect... it won't work

Screenshot:

image

It then shows this for a while:

Screenshot from 2022-08-09 16-32-02

And finally this error message:

Screenshot from 2022-08-09 16-32-11

(Also: In this case, the "Cancel" link should really be a "Close" button with a secondary style, not a link styled button.)

Please note that the host + user works, as does the ssh://user@host... but mixing the URI + user doesn't.

In other words: Cockpit should try `ssh://user@host` (with the username from the separate entry) when `ssh://host` is used and the user is also filled in.

### Version of Cockpit

273

### Where is the problem in Cockpit?

Navigation & Shell

### Server operating system

CentOS

### Server operating system version

Stream 8

### What browsers are you using?

Firefox, Chrome

### System log

_No response_

### PR DESCRIPTION
**Pull request by MahmoudHamdy02**
Fixes #17635.

The issue is caused by an extra `ssh://` in the connection address.

For example, when entering `ssh://mahmoud-PC` in the host field and `mahmoud` in the username field, cockpit tries to connect to `mahmoud@ssh://mahmoud-PC` instead of `mahmoud@mahmoud-PC`, which causes an error.

I trimmed the `ssh://` string in the `split_connection_string` function, I'm not sure if this is the best implementation so I'm opening this as a draft for now.

### CODE REVIEW

File: pkg/shell/machines/machines.js [hunk 1]
```diff
@@ -379,6 +379,8 @@ function Machines() {
         let port_spot = -1;
 
         if (conn_to) {
+            if (conn_to.substring(0, 6) === "ssh://")
+                conn_to = conn_to.substring(6);
```
Comment (martinpitt) [inline pkg/shell/machines/machines.js:383]: I actually wonder where that `ssh://` thing even  comes from. https://git.libssh.org/projects/libssh.git/ has no idea about it. Commit bb7a8b1ac3 just introduced it into the help en passant without any references to documentation or tests. So I think it's pretty much up to us to define it. As the only plausible format is `ssh://[user@]host[:port]`, and we already support `[user@]host[:port]`, stripping the prefix seems fine to me.

So the implementation is good, but we need some integration test in test/verify/check-shell-host-switching or test/verify/check-shell-multi-machine to ensure that `ssh://host`, ssh://host:port`, and `ssh://user@host:port` all work.

Comment (MahmoudHamdy02) [reply pkg/shell/machines/machines.js:383]: Hello @martinpitt,
I've added a test for the ssh connections (and modified `add_machine` to get the username). I wasn't sure where to put this exactly so I put it in a new test case `testSSH` for now. Let me know if this is correct

Comment (martinpitt) [reply pkg/shell/machines/machines.js:383]: Thanks! I'll comment on the new test in separate threads. The `machine` argument is indeed unused. Feel free to add a separate commit to remove it from the declaration and all of its callers.

Please also squash the new test into the first commit, and prefix the subject with "shell: ". Finally, please rebase your branch to latest origin/main so that the packit tests keep working (it's a good habit to `git fetch origin; git rebase origin/main` before *every* PR push).

File: test/verify/check-shell-host-switching [hunk 2]
```diff
@@ -62,10 +62,16 @@ class HostSwitcherHelpers:
           return true;
         })""", address)
 
-    def add_machine(self, b, address, known_host=False, pixel_label=None):
+    def add_machine(self, b, address, known_host=False, pixel_label=None, user=False):
```
Comment (martinpitt) [inline test/verify/check-shell-host-switching:65]: `user=None` please. It's confusing to let this be either a boolean or a string.

File: test/verify/check-shell-host-switching [hunk 3]
```diff
@@ -62,10 +62,16 @@ class HostSwitcherHelpers:
...
+        # Trim ssh:// from the address for known_host message
+        if address[:6] == "ssh://":
+            address = address[6:]
```
Comment (martinpitt) [inline test/verify/check-shell-host-switching:68]: That's cheating :grin:  The new test actually want to type the `ssh://` prefix into the `#add-machine-address` field. You only want to strip it for checking the "You are connecting to .." message.

File: test/verify/check-shell-host-switching [hunk 4]
```diff
@@ -123,6 +129,22 @@ class TestHostSwitching(MachineCase, HostSwitcherHelpers):
         self.allow_restart_journal_messages()
         self.allow_hostkey_messages()
 
+    def testSSH(self):
```
Comment (martinpitt) [inline test/verify/check-shell-host-switching:132]: Each new test here is *very* expensive, as it provides three new VMs. For that reason, please merge this into `testBasic`. I think a nice place would be in line 206, before the "Test change user, not doing in edit to reuse machines" comment.

File: test/verify/check-shell-host-switching [hunk 5]
```diff
@@ -123,6 +129,22 @@ class TestHostSwitching(MachineCase, HostSwitcherHelpers):
...
+        b = self.browser
+        m1 = self.machines["machine1"]
+
+        self.login_and_go(superuser=False)
+
+        b.click("#hosts-sel button")
+        self.wait_host_addresses(b, ["localhost"])
+
+        self.add_machine(b, "ssh://10.111.113.2", False, user="admin")
+        self.machine_remove(b, "10.111.113.2", m1, True)
```
Comment (martinpitt) [inline test/verify/check-shell-host-switching:142]: This only runs the "Add" dialog, but does not ensure it actually worked. You need to do the `self.wait_host_addresses()` and `self.connect_and_wait()` steps to assert that the connection was successful.

**Review by martinpitt — CHANGES_REQUESTED** [review]
Thank you!

File: test/verify/check-shell-host-switching (hunk 3 above)
Comment (MahmoudHamdy02) [reply test/verify/check-shell-host-switching:68]: @martinpitt also, should the test log in directly, or 'Authorize SSH key'?

Comment (martinpitt) [reply test/verify/check-shell-host-switching:68]: The SSH key gets generated without a password in `setup_ssh_auth()`, i.e. it calls `ssh-keygen` with `-N ''`. So I suppose something is legitimately broken with these `ssh://` prefixes? Does it work without the prefix? (That's exactly why we want to test all cases :grin: )

Feel free to push your current code if you want me to have a closer look -- you probably have local modifications over what's pushed here, so I can only guess what's wrong.

**Comment by martinpitt** [comment]
@MahmoudHamdy02 : This got a bit stuck. Do you still want to work on this, or shall I take over and finish this?

**Comment by MahmoudHamdy02** [comment]
Hi @martinpitt! Got a bit distracted by GSOC and never got around to finishing this :sweat_smile:. You can continue working on this, sounds good. Thanks!

**Comment by martinpitt** [comment]
OK, so that was an unexpected yak shave, the tests found a few more problems, and the fix here was incompletel. Let's give it a first run!

**Comment by martinpitt** [comment]
Unrelated: [this](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18614-20231130-141040-88c30181-fedora-39-expensive/log.html) is a known issue https://github.com/cockpit-project/bots/issues/5444 , with a non-matching naughty pattern

File: test/verify/check-shell-host-switching [hunk 6]
```diff
@@ -61,6 +61,9 @@ class HostSwitcherHelpers:
           return true;
         })""", address)
 
+        # HACK: Dropping the machine does not terminate SSH connection; https://github.com/cockpit-project/cockpit/issues/19672
+        self.machine.execute(f"pkill -f [s]sh.*{address}; while pgrep -f [s]sh.*{address}; do sleep 1; done")
```
Comment (martinpitt) [inline test/verify/check-shell-host-switching:65]: Note: the `pkill`, and with it the test, will fail when we actually fix that bug. That'll be a good reminder to drop the hack then (or restrict it to RHEL 8)

**Comment by martinpitt** [comment]
@mvollmer gentle review ping?

**Review by mvollmer — APPROVED** [review]
Thanks!
