### PR TITLE
base1: Use javascript-style locales for toLocaleString

### LINKED ISSUE #9349: Broken UI - Portuguese
Running Cockpit Project 169 on Fedora Server. I get the following error when it is set to portuguese:

```
cockpit.js:1483 Uncaught RangeError: Invalid language tag: pt_BR
    at new NumberFormat (native)
    at Number.toLocaleString (native)
    at Object.format_number (cockpit.js:1483)
    at format_units (cockpit.js:1532)
    at Object.format_bytes_per_sec (cockpit.js:1589)
    at Object.r.format_bytes_per_sec_tick_no_unit [as tickFormatter] (system.js:3105)
    at Object.N.t.isFunction.e.tickFormatter (system.js:3648)
    at A (system.js:3672)
    at Object.<anonymous> (system.js:3604)
    at Function.each (jquery.js:354)
    at S (system.js:3603)
    at new n (system.js:4275)
    at Function.t.plot (system.js:4371)
    at i (system.js:2792)
    at system.js:2801
```

Result:

image

Reverting to english fixes the problem, as expected

### PR DESCRIPTION
**Pull request by allisonkarlitskaya**
For at least Brazilian Portuguese, we end up with cockpit.language set
to 'pt_BR', with an underscore.  Passing this to toLocaleString causes
an exception, because it wants to see it like 'pt-br'.

Other places in the code assume that cockpit.language is a POSIX style
locale, so we can't change it there.  Instead, do the substitution
inside of format_number().

Fixes #9349
Closes #9413

### CODE REVIEW

File: src/base1/cockpit.js [hunk 1]
```diff
@@ -1468,19 +1468,20 @@ function factory() {
          * non-localised conversions (and in both cases, show no
          * fractional part).
          */
+	var lang = cockpit.language === undefined ? undefined : cockpit.language.replace('_', '-');
```
Comment (martinpitt) [inline src/base1/cockpit.js]: Can it happen that it's `null`? Maybe just check for truthness? `cockpit.language ? …replace() : 'en'`? (Or default to null if the code below is able to handle that).

Comment (allisonkarlitskaya) [reply src/base1/cockpit.js]: The value is initialised to 'undefined', which is the case I'm checking for here.  Any call to locale() will be with a po file, so I don't think we will ever see null here...

I'll change it if you think it would be better.

Comment (martinpitt) [reply src/base1/cockpit.js]: Thanks, that's fine. Just wanted to cover all bases.
