### PR TITLE
lib: Fix ShutdownModal error type on `shutdown` errors

### LINKED ISSUE #20547: TestAD.testUnqualifiedUsers triggered page oops (minified react errror)
The job `fedora-40/daily` failed on commit b3f3cd070f11903e30917ab23a6193a1adc7e3b7.

Log: https://cockpit-logs.us-east-1.linodeobjects.com/pull-0-b3f3cd07-20240605-012920-fedora-40-daily/log.html

### PR DESCRIPTION
**Pull request by martinpitt**
The `error` state is a string, and rendered as such. Don't set it to an
error object when `shutdown` fails with an error, as that crashes the
page with "Objects are not valid as a React child".

Consistently use `.toString()` like we do in most other places.

Fixes #20547

### CODE REVIEW

File: pkg/lib/cockpit-components-shutdown.jsx [hunk 1]
```diff
@@ -143,7 +143,7 @@ export class ShutdownModal extends React.Component {
         this.date_spawn.catch(e => {
             if (e.problem == "cancelled")
                 return;
-            this.setState({ error: e.message });
+            this.setState({ error: e.toString() });
```
Comment (cockpituous) [inline pkg/lib/cockpit-components-shutdown.jsx:146]: This added line is not executed by any test.

Comment (cockpituous) [inline pkg/lib/cockpit-components-shutdown.jsx:146]: This added line is not executed by any test.

File: pkg/lib/cockpit-components-shutdown.jsx [hunk 2]
```diff
@@ -156,7 +156,7 @@
 
         cockpit.spawn(["shutdown", arg, this.state.when, this.state.message], { superuser: "require", err: "message" })
                 .then(this.props.onClose || Dialogs.close)
-                .catch(e => this.setState({ error: e }));
+                .catch(e => this.setState({ error: e.toString() }));
```
Comment (cockpituous) [inline pkg/lib/cockpit-components-shutdown.jsx:159]: This added line is not executed by any test.

File: pkg/lib/cockpit-components-shutdown.jsx (hunk 1 above)
Comment (cockpituous) [inline pkg/lib/cockpit-components-shutdown.jsx:146]: This added line is not executed by any test.

Comment (cockpituous) [inline pkg/lib/cockpit-components-shutdown.jsx:146]: This added line is not executed by any test.

**Comment by martinpitt** [comment]
Nice, works! [TestApps.testL10N](https://cockpit-logs.us-east-1.linodeobjects.com/pull-20556-1d45fdef-20240606-100824-centos-10-network-devel/log.html) is an entirely different issue, so let's fix that one first. I take out the debugging stuff.

**Review by jelly — APPROVED** [review]
Thanks!

File: pkg/lib/cockpit-components-shutdown.jsx (hunk 1 above)
Comment (cockpituous) [inline pkg/lib/cockpit-components-shutdown.jsx:146]: This added line is not executed by any test.

File: pkg/lib/cockpit-components-shutdown.jsx [hunk 3]
```diff
@@ -156,7 +156,7 @@ export class ShutdownModal extends React.Component {
...
```
Comment (cockpituous) [inline pkg/lib/cockpit-components-shutdown.jsx:159]: This added line is not executed by any test.
