### PR TITLE
common: handle non-blocking fd in cockpit_socket_receive_fd()

### LINKED ISSUE #17412: Enabling sudo log_output breaks privilege escalation in Cockpit
### Explain what happens

1. Configure sudo [IO Logging to files](https://www.sudo.ws/docs/man/sudoers.man/#I/O_LOG_FILES) (please see example below),
2. You will likely see "_Cockpit-bridge: recvmsg(stdin) failed: Socket operation on non-socket_" when you attempt to switch to administrative access,
3. Disable IO Logging,
4. Switching to administrative access succeeds.

Example `/etc/sudoers.d/wheel` file:

```sudoers
Defaults log_host
Defaults iolog_dir=/var/log/sudo-io

# Members of the admin group may gain root privileges
%wheel ALL=(ALL) LOG_OUTPUT:LOG_INPUT: ALL

# prevent recursive logging
%wheel ALL=(ALL) NOLOG_OUTPUT:NOLOG_INPUT: /usr/bin/sudoreplay
```

### Version of Cockpit

264.1

### Where is the problem in Cockpit?

_No response_

### Server operating system

other

### Server operating system version

AlmaLinux 8.6

### What browsers are you using?

Firefox, Safari macOS

### System log

```shell
-- Logs begin at Sun 2022-05-15 10:01:34 SAST, end at Tue 2022-05-31 21:55:25 SAST. --
May 31 21:05:57 base.damn.org.za systemd[1]: Starting PackageKit Daemon...
May 31 21:05:57 base.damn.org.za dbus-daemon[902]: [system] Rejected send message, 1 matched rules; type="method_call", sender=":1.8419" (uid=1000 pid=37932 comm="cockpit-bridge " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023") interface="org.freedesktop.DBus.Properties" member="GetAll" error name="(unset)" requested_reply="0" destination="org.fedoraproject.Setroubleshootd" (uid=996 pid=37928 comm="/usr/libexec/platform-python -Es /usr/sbin/setroub" label="system_u:system_r:setroubleshootd_t:s0-s0:c0.c1023")
May 31 21:05:57 base.damn.org.za dbus-daemon[902]: [system] Rejected send message, 1 matched rules; type="method_call", sender=":1.8419" (uid=1000 pid=37932 comm="cockpit-bridge " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023") interface="org.freedesktop.DBus.Properties" member="GetAll" error name="(unset)" requested_reply="0" destination="org.fedoraproject.Setroubleshootd" (uid=996 pid=37928 comm="/usr/libexec/platform-python -Es /usr/sbin/setroub" label="system_u:system_r:setroubleshootd_t:s0-s0:c0.c1023")
May 31 21:05:57 base.damn.org.za PackageKit[37996]: daemon start
May 31 21:05:58 base.damn.org.za dbus-daemon[902]: [system] Successfully activated service 'org.fedoraproject.SetroubleshootFixit'
May 31 21:05:58 base.damn.org.za dbus-daemon[902]: [system] Successfully activated service 'org.freedesktop.PackageKit'
May 31 21:05:58 base.damn.org.za systemd[1]: Started PackageKit Daemon.
May 31 21:05:58 base.damn.org.za dbus-daemon[902]: [system] Rejected send message, 1 matched rules; type="method_call", sender=":1.8419" (uid=1000 pid=37932 comm="cockpit-bridge " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023") interface="org.freedesktop.DBus.Properties" member="GetAll" error name="(unset)" requested_reply="0" destination="org.fedoraproject.SetroubleshootFixit" (uid=0 pid=37997 comm="/usr/libexec/platform-python -Es /usr/share/setrou" label="system_u:system_r:setroubleshoot_fixit_t:s0-s0:c0.c1023")
May 31 21:05:58 base.damn.org.za dbus-daemon[902]: [system] Rejected send message, 1 matched rules; type="method_call", sender=":1.8419" (uid=1000 pid=37932 comm="cockpit-bridge " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023") interface="org.freedesktop.DBus.Properties" member="GetAll" error name="(unset)" requested_reply="0" destination="org.fedoraproject.SetroubleshootFixit" (uid=0 pid=37997 comm="/usr/libexec/platform-python -Es /usr/share/setrou" label="system_u:system_r:setroubleshoot_fixit_t:s0-s0:c0.c1023")
May 31 21:05:59 base.damn.org.za dbus-daemon[902]: [system] Activating via systemd: service name='com.redhat.RHSM1' unit='rhsm.service' requested by ':1.8423' (uid=1000 pid=37932 comm="cockpit-bridge " label="unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023")
May 31 21:05:59 base.damn.org.za systemd[1]: Starting RHSM dbus service...
May 31 21:06:02 base.damn.org.za dbus-daemon[902]: [system] Successfully activated service 'com.redhat.RHSM1'
May 31 21:06:02 base.damn.org.za systemd[1]: Started RHSM dbus service.
May 31 21:06:04 base.damn.org.za PackageKit[37996]: uid 1000 is trying to obtain org.freedesktop.packagekit.system-sources-refresh auth (only_trusted:0)
May 31 21:06:04 base.damn.org.za polkitd[905]: Operator of unix-session:10 FAILED to authenticate to gain authorization for action org.freedesktop.packagekit.system-sources-refresh for system-bus-name::1.8423 [cockpit-bridge] (owned by unix-user:eroux)
May 31 21:06:04 base.damn.org.za PackageKit[37996]: uid 1000 failed to obtain auth
```

### PR DESCRIPTION
**Pull request by martinpitt**
In some setups it happens that the spawned root bridge's stdin is non-blocking. Trying to call recvmsg() on it then often fails with `EAGAIN`, causing the superuser dialog to fail with "Problem becoming administrator: Cockpit-bridge: recvmsg(stdin) failed: Resource temporarily unavailable".

By default all stdio fds should be blocking. But when enabling sudo's `log_output` option, sudo splices the original stdio pipes to the log, and the stdin seen by cockpit-bridge ends up as non-blocking.

Avoid this by polling stdin until data is available. (There is no opposite to the `MSG_DONTWAIT` flag).

Fixes #17412
https://bugzilla.redhat.com/show_bug.cgi?id=2211760

### CODE REVIEW

**Comment by allisonkarlitskaya** [comment]
> The root cause is totally unclear, but I figure the fix would be the same either way..

weird pam module?

is this via ssh or what?

**Comment by martinpitt** [comment]
No, nothing weird AFAICS. It's a RHEL 9.2 cloud instance. I suspected some SELinux oddity, but the customer even has that turned off. I can connect you with the support request ticket if you have some more ideas what to ask.

**Review by allisonkarlitskaya — APPROVED** [review]
I'd prefer not to merge this without understanding the root cause — we'd just be covering up what is probably a bug somewhere else.

**Comment by martinpitt** [comment]
I asked the customer about details how that system was installed, and add you to the case ticket.

It's not a bad hack, and halfway defensive programming, but I agree it would be nice to understand the root cause.
It's not super-urgent to land this, we still have a few months.

**Comment by martinpitt** [comment]
@allisonkarlitskaya : Hmm, I didn't reach the customer who reported the bug any more. Can we write that off as "defensive programming"?

**Comment by martinpitt** [comment]
@SupremeGit gave us the right hint in https://github.com/cockpit-project/cockpit/issues/17412#issuecomment-1630118965 . I can finally reproduce this on RHEL 8, curiously not on Fedora 38 (which might be a race condition or something in sudo got changed). The new test case reliably fails for me in RHEL 8 without this fix:
```
Traceback (most recent call last):
  File "/var/home/martin/upstream/cockpit/main/test/verify/check-superuser", line 93, in testSudoIOLogging
    b.become_superuser()
  File "/var/home/martin/upstream/cockpit/main/test/common/testlib.py", line 880, in become_superuser
    self.check_superuser_indicator("Administrative access")
  File "/var/home/martin/upstream/cockpit/main/test/common/testlib.py", line 862, in check_superuser_indicator
    self.wait_text("#super-user-indicator", expected)
  File "/var/home/martin/upstream/cockpit/main/test/common/testlib.py", line 660, in wait_text
    self.wait_js_cond("ph_text_is(%s,%s)" % (jsquote(selector), jsquote(text)),
  File "/var/home/martin/upstream/cockpit/main/test/common/testlib.py", line 587, in wait_js_cond
    self.raise_cdp_exception("timeout\nwait_js_cond", cond, result["exceptionDetails"], trailer)
  File "/var/home/martin/upstream/cockpit/main/test/common/testlib.py", line 293, in raise_cdp_exception
    raise Error("%s(%s): %s" % (func, arg, msg))
testlib.Error: timeout
wait_js_cond(ph_text_is("#super-user-indicator","Administrative access")): actual text: Limited access
```
and I see the error message in the dialog:

> Problem becoming administrator
> Cockpit-bridge: recvmsg(stdin) failed: Resource temporarily unavailable

Let's see how this holds up with the Python bridge, it may be that we need to apply the same change there.

**Comment by allisonkarlitskaya** [comment]
Can we try to get the sudo fix into RHEL?  Seems like their bug...

File: src/common/cockpitfdpassing.c [hunk 1]
```diff
@@ -119,6 +121,11 @@ cockpit_socket_receive_fd (int  socket_fd,
                         .msg_controllen = CMSG_LEN (sizeof *out_fd) };
   assert (msg.msg_controllen <= sizeof cmsg);
 
+  int cur_flags = fcntl (socket_fd, F_GETFL);
```
Comment (allisonkarlitskaya) [inline src/common/cockpitfdpassing.c:124]: So, "no" to this part, at least, on technical grounds: this is a heavy hammer of an operation to work around a very specific issue.  I'd prefer if we solved that issue by using `poll()` here (and `select.select([0], [], [])` in Python) to block until stdin is readable, instead.

**Review by allisonkarlitskaya — CHANGES_REQUESTED** [review]
"Changes requested" for the technical issue below.

On the higher level discussion of if a workaround here is suitable or not:

 - I'd prefer to get the sudo fix backported into RHEL or anywhere else we see this issue popping up.
 - I'm open to temporarily adding a workaround to Cockpit, to deal with this if this is not possible (quickly enough), with the eye to removing the workaround once the fix is widely deployed or we stop supporting the broken downstream OSes.  We should clearly state the conditions for future removal in a comment beside the changed code.

We also have a small hazard here: masking the introduction of new bugs in other people's software which will then be "unmasked" when we remove the workaround because we think sudo is fixed...

File: src/common/cockpitfdpassing.c (hunk 1 above)
Comment (martinpitt) [reply src/common/cockpitfdpassing.c]: Changed to poll(). But OOI (and since you didn't reply in chat):

> stdin does not belong to us / "heavy hammer":

What does that mean? I thought that each fd has an independent blocking/nonblocking setting, and that was more or less just a local choice which kind of API a program wants to use. It certainly shouldn't affect the "other end" (i.e. sudo's side of what the bridge's stdin is connected to).

Comment (allisonkarlitskaya) [reply src/common/cockpitfdpassing.c]: It's true that we own our own file descriptor 0, and this is local for our process ,but that's not how this works.  The non-blocking setting is a property of the file description, not the file descriptor.  It is shared by everyone who has (or will ever have in the future) our stdin.

This is the source of all of the problems we used to have with various node/webpack-based processes changing the non-blocking settings on the terminal.  This shouldn't be the way it is, but it is... :(

**Comment by allisonkarlitskaya** [comment]
Another reproducer, quite to the point: 

```sh
sudo python -c 'import os; os.read(0, 1)'
```

will throw

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
BlockingIOError: [Errno 11] Resource temporarily unavailable
```

**Comment by allisonkarlitskaya** [comment]
> > sudo python -c 'import os; os.read(0, 1)'
> 
> Interesting! I can't get that, at least not on rhel-8-9 or on my Fedora 38 host. `python` isn't a thing, but I tried with both `python3` and `/usr/libexec/platform-python`. Both with and without `log_output` it just hangs (as expected). On which OS did you run that? And do you get non-zero for the `print(fcntl)` above as well?

I didn't actually run that under sudo, but under a similar wrapper that sets the non-blocking flag on stdin and execs.  That's really interesting!

File: src/common/cockpitfdpassing.c (hunk 1 above)
Comment (martinpitt) [reply src/common/cockpitfdpassing.c]: Right, that's what I thought. So while this locally fixes it for cockpit_socket_receive_fd(), it would remain non-blocking for everything else. Originally I wanted to move this into the main() bridge setup. But you said that most of the bridge gets along with non-blocking stdin (as it's part of the async I/O from the main loop, and thus uses select()/epoll()/friends). Programs run from channels should also be isolated, as cockpit_pipe_spawn() creates new stdin fds for the child. So after that discussion, (1) I agree that the local fix suffices, and (2) I think we share an understanding what the blocking flag does, and I wasn't missing some weird magic that would influence other processes.

File: src/common/cockpitfdpassing.c [hunk 2]
```diff
@@ -119,6 +122,15 @@ cockpit_socket_receive_fd (int  socket_fd,
                         .msg_controllen = CMSG_LEN (sizeof *out_fd) };
   assert (msg.msg_controllen <= sizeof cmsg);
 
+  /* recvmsg() has no MSG_DONTWAIT, and e.g. sudo makes stdin non-blocking with `log_output` option */
+  if (fcntl (socket_fd, F_GETFL) & O_NONBLOCK)
+    {
+      struct pollfd socket_pfd = { .fd = socket_fd, .events = POLLIN };
```
Comment (allisonkarlitskaya) [inline src/common/cockpitfdpassing.c:128]: Any reason to not just do the `poll()` unconditionally?

File: src/common/cockpitfdpassing.c [hunk 3]
```diff
@@ -119,6 +122,15 @@ cockpit_socket_receive_fd (int  socket_fd,
...
+      int ret = poll (&socket_pfd, 1, -1);
+      if (ret <= 0) /* error or timeout; the latter should not happen, but pass it on as "EOF" */
```
Comment (allisonkarlitskaya) [inline src/common/cockpitfdpassing.c:130]: There's a small theoretical possibility that we could get impacted here by something dumb like a `SIGWINCH`, depending on our signal dispositions as we're spawned...  can you give this the typical

```c
do
   ret = poll (&socket_pfd, 1, -1);
while (ret == -1 && errno == EINTR);
```

treatment?

File: src/common/cockpitfdpassing.c (hunk 2 above)
Comment (martinpitt) [reply src/common/cockpitfdpassing.c:128]: Not a strong one. My initial instinct was to add a `g_message()` about it, then noticed that this file doesn't use glib, didn't like a raw printf(), and then just "meh, not important enough" :grin: But if we treat it as a permanent hack for the C bridge (whose days are numbered anyway), I'm fine with dropping the `if`.

File: src/common/cockpitfdpassing.c (hunk 3 above)
Comment (martinpitt) [reply src/common/cockpitfdpassing.c]: Good point, thanks! Done.

File: src/common/cockpitfdpassing.c (hunk 2 above)
Comment (martinpitt) [reply src/common/cockpitfdpassing.c]: Changed.

**Review by allisonkarlitskaya — APPROVED** [review]
Thanks!
