### PR TITLE
systemd: Fix state handling with creating repeating timers

### LINKED ISSUE #19278: Cockpit creating systemd timers with wrong execution times
### 1. Create a systemd timer 

<details>
<summary>Screenshot</summary>

image

</details>

### 2. The timer gets created with the wrong execution time 
<details>
<summary>Screenshot</summary>

image

</details>

**Content of /etc/systemd/system/test.timer**
```
[Unit]
Description=test
[Timer]
OnCalendar=*-*-* 00:00:00
[Install]
WantedBy=timers.target
```

### Version of Cockpit

299-1~bpo12+1 from bookworm-backports

### Where is the problem in Cockpit?

Services

### Server operating system

Debian

### Server operating system version

Debian 12 / Bookworm

### What browsers are you using?

Chrome

### System log

_No response_

### PR DESCRIPTION
**Pull request by martinpitt**
When setting the time of a repeated timer with the mouse, this triggered both `onChange()` and `setOpen()` at the same time, both of which calling `setRepeatPatterns()`. Due to the async/deferred nature of React, these both worked on old data, so that the first callback was effectively ignored, and created timers ended up with the default "00:00" time. Fix that with a functional state update.

Also replace the weird JSON stringify/parse cycle with a spread, like all the other callbacks already did -- the only purpose of that was to copy the list.

This didn't happen when setting the time with the keyboard, because the dropdown wasn't opened then. So change TestTimers() to set the "Friday" repeat time with the mouse (keep the Monday one with the keyboard, to cover both cases). As we only have 30-minute granularity, change the time from 12:45 to 12:30.

The test uses select_PF5(), so drop it from the vulture suppressions. (c-machines also uses that function.)

Fixes #19278

### CODE REVIEW

File: pkg/systemd/timer-dialog.jsx [hunk 1]
```diff
@@ -361,24 +361,24 @@ const CreateTimerDialogBody = ({ owner }) => {
                                                 <Button aria-label={_("Remove")}
                                                         variant="secondary"
                                                         isDisabled={repeatPatterns.length == 1}
-                                                        onClick={() => setRepeatPatterns(repeatPatterns.filter((item, item_idx) => idx != item_idx))}>
+                                                        onClick={() => setRepeatPatterns(old => old.filter((item, item_idx) => idx != item_idx))}>
```
Comment (cockpituous) [inline pkg/systemd/timer-dialog.jsx:364]: This added line is not executed by any test.

**Review by jelly — APPROVED** [review]
Thanks for figuring this out!
