### PR TITLE
Make switching to admin access more visible

### LINKED ISSUE #14305: navigation: permission switcher has low discoverability rate
Cockpit version: 220
OS: RHEL
Page: Navigation

During the usability testing in June with 5 participants, 2 participants failed the task, and 2 needed assistance to complete the task of putting the system in limited access mode.

Screenshot from 2020-06-30 18-02-27

### PR DESCRIPTION
**Pull request by garrett**
Fixes #14305.

Changes to the shell and overview alert.

### CODE REVIEW

**Comment by garrett** [comment]
I goofed up the breakpoint stuff when I dropped some commits and squashed otehrs. I'll fixup, force-push, and mark as ready for review after. Aside from that, it's good enough to look at. I'll post screenshots when I have this fixed too. 

It looks a lot like the mockup, but I decided switching the alert border is probably a little too much. I kept everything else I mocked up, however.

**Comment by garrett** [comment]
Screenshot:

Screenshot 2021-07-28 at 15-27-16 Overview - garrett Bolt

Whoops. I forgot to re-check mobile:

Screenshot 2021-07-28 at 15-28-38 Virtual Machines - garrett Bolt

**Comment by garrett** [comment]
Shell's mobile menu is now fixed, with icons midway in the gutter area:

Screenshot 2021-07-28 at 16-08-26 Virtual Machines - garrett Bolt

File: pkg/systemd/superuser-alert.jsx [hunk 1]
```diff
@@ -50,7 +52,8 @@ export class SuperuserAlert extends React.Component {
             <>
                 <Alert className="ct-limited-access-alert"
                        hidden={this.superuser.Current != "none"}
-                       variant="info" isInline
+                       variant="warning" isInline
```
Comment (KKoukiou) [inline pkg/systemd/superuser-alert.jsx:55]: I did not take a look in the CSS changes yet, but I am not convinced that it's correct to show a 'warning' alert for not privileged logins..

Comment (martinpitt) [reply pkg/systemd/superuser-alert.jsx:55]: I'm a bit torn here. On one hand being not root is the expected mode for SSH/desktop sessions, and some users are not even allowed to become root (there is no way to predict that). OTOH being root is the main use case for cockpit..

But even if we dial this back to info, I find all the other changes really excellent! Thanks @garrett!

Comment (garrett) [reply pkg/systemd/superuser-alert.jsx:55]: It doesn't have a warning icon, but a custom one, however. 

The blue alert with another blue alert (login, which should _not_ be an alert, but currently is) is an excellent way to completely ignore the alert, which is part of the problem.

The "warning" is that Cockpit will not work the way you expect, if you generally use Cockpit as an admin, which most people do. It can be ignored by going to other pages.

Right now, Cockpit is quite broken in several pages when you're not the admin. (Pages don't let you know and may be blank or partially blank without any fallback message.) So it is indeed a warning and important to know to switch (if you can). We should also fix these pages, but it's still important regardless, as it will forever be important to be an admin to perform admin tasks.

**Comment by garrett** [comment]
Note: I did consider a PF banner component (which is relatively new), but it even states:

> For use cases requiring more than a single line of content or requiring important actions for the user to take, the flow should make use of the [inline alert](https://www.patternfly.org/v4/components/alert/design-guidelines#inline-alerts) or [hint pattern](https://www.patternfly.org/v4/components/hint/design-guidelines) instead, as they allow for more flexibility around these use cases.

And then I considered hint:

> A hint is in-app messaging that provides a one-step reminder, explanation, or call to action for a page or modal.

> Use hints to share information about an interaction or prerequisite step that might not be immediately obvious to the user.

A hint sounds about right from the description, but doesn't really fit our overview page modal. It would have to show up where the _system_ alerts and MOTD ([and login info](https://github.com/cockpit-project/cockpit/issues/13882)?!???!) shows up. Everything in that area should be system-related, not session.

Hence, I kept it as an undismissable alert at the top as-is. It lets us change the color to indicate something is important, use an icon to grab attention and reinforce the top-right action in the shell (using the same lock icon and color when it's applicable), and make the action obvious with a button. These are all things that banner and hint components don't let us do in one way or another.

File: pkg/systemd/superuser-alert.jsx (hunk 1 above)
Comment (garrett) [reply pkg/systemd/superuser-alert.jsx:55]: I'd like to point out that we had people in our UX study from a while back who missed not just the top shell area, but also the notification. It wasn't eye-catching enough. Part of that is the understated blue color (including its repetition with the log in "alert").

Comment (KKoukiou) [reply pkg/systemd/superuser-alert.jsx:55]: Thanks for the detailed answer. Since we only borrowed the 'warning' color and not the icon as well, I think indeed we are walking on the middle ground of raising attention but not really marking it as a warning. I like it, thanks for this improvement.

**Review by KKoukiou — APPROVED** [review]

**Comment by martinpitt** [comment]
@garrett : I updated the screenshot for the "Session" icon change, and cropped it. I also updated it to include the "Session" menu as well, as it's the same screenshot, and both affect the shell panel. I also added crediting @Verhoeckx. Do you mind proofreading this?
