### PR TITLE
users: Allow weak passwords

### LINKED ISSUE #14478: Allow weak passwords on user creation
**Problem**

cockpit is blocking the usage of weak passwords. The system (Debian 10) is allowing this usage (checked with running "adduser" and the same weak password). Please add an option to disable your password verification

cockpit version 188
linux version: Debian GNU/Linux 10 (buster)

**Reproduce**

1. in the cockpit UI open "...:9090/users" and click "Add Account" (or whatever the original text is)
2. enter the username and a weak password (f.eg. "ma99" - of course twice)
3. click "create"

**Result**

You'll get the response "Password quality check failed: The password is shorter than 8 characters". 
Wrong: I never decided to have a minimal length for passwords.
For a locally driven (not connected) server it is rediculous to have long and complex passwords.

**System behaviour**

Using the bash on the system directly, there is no problem to create the user with the same password:

1. type "adduser testname"
2. type the weak password twice
3. confirm all other questions simply by pressing the "return" key
4. voila ! the user has been created without problems.

**Expected result**

The user should not be blocked when specifying a weak password. Please remove the password verification altogether ... or add an option in your software to avoid this behaviour.

**Please note**

.. the 1st ticket at https://github.com/osbuild/cockpit-composer/issues/1079 with same description but some comments.

(also requested in ticket https://github.com/osbuild/cockpit-composer/issues/985 in cockpit-composer by jgiardino but closed without a real solution)

### PR DESCRIPTION
**Pull request by marusak**
Modeled after anaconda where you can use a weak password if you click
the button two times.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1652390
Fixes #14478

@andreasn WDYT? Also the wording is not ideal, maybe I should spin up one fedora VM to see what exactly anaconda says.

<hr> 
Release note draft:

**Accounts: Allow setting up weak passwords**

Cockpit now allows users to set up a weak passwords. User is firstly notified that such password is weak but if user wishes to continue then clicking the submit button again will use the selected password anyway.

cretejose

### CODE REVIEW

**Comment by marusak** [comment]
Needs distropkg special case and really a fix for `userdel: user anton is is curently used by process <n>` as it is going to be hard to get this in otherwise

**Comment by marusak** [comment]
> fix for userdel: user anton is is curently used by process <n> as it is going to be hard to get this in otherwise

https://github.com/cockpit-project/cockpit/pull/14517/commits/468a68e64e60d559c706e15b49cf2bc301b6d243 :)

File: test/verify/check-accounts [hunk 1]
```diff
@@ -135,16 +135,30 @@ class TestAccounts(MachineCase):
...
         b.set_input_text('#accounts-create-user-name', "jussi")
         b.set_input_text('#accounts-create-real-name', "Jussi Junior")
-        b.set_input_text('#accounts-create-pw1', good_password)
-        b.set_input_text('#accounts-create-pw2', good_password)
+        b.set_input_text('#accounts-create-pw1', "foo")
+        b.set_input_text('#accounts-create-pw2', "foo")
         b.set_checked('#accounts-create-locked', True)
         b.click('#accounts-create-dialog button.apply')
+
+        # Password is weak, lets change it to another week - this should still not accept
```
Comment (martinpitt) [inline test/verify/check-accounts:149]: week → weak :grin:

File: test/verify/check-accounts [hunk 2]
```diff
@@ -135,16 +135,30 @@ class TestAccounts(MachineCase):
...
 
-        # Create a locked user
+        # Create a locked user with weak password
         m.execute("sed -i 's/^SHELL=.*$/SHELL=/' /etc/default/useradd")
         b.click('#accounts-create')
         b.wait_visible('#accounts-create-dialog')
         b.set_input_text('#accounts-create-user-name', "jussi")
         b.set_input_text('#accounts-create-real-name', "Jussi Junior")
-        b.set_input_text('#accounts-create-pw1', good_password)
-        b.set_input_text('#accounts-create-pw2', good_password)
```
Comment (martinpitt) [inline test/verify/check-accounts:145]: Please keep the test case with the good password as well -- this should not ask twice.

File: pkg/users/account-create-dialog.js [hunk 3]
```diff
@@ -159,7 +159,8 @@ export function account_create_dialog(accounts) {
         password_confirm: "",
         password_strength: "",
         password_message: "",
-        locked: false
+        locked: false,
+        first_click: false,
```
Comment (martinpitt) [inline pkg/users/account-create-dialog.js:163]: That sounds a bit generic -- how about `confirmed_weak`?

File: pkg/users/account-create-dialog.js [hunk 4]
```diff
@@ -209,9 +211,10 @@ export function account_create_dialog(accounts) {
 
         errors.user_name = validate_username(state.user_name, accounts);
 
-        return password_quality(state.password)
+        return password_quality(state.password, force)
                 .catch(ex => {
-                    errors.password = ex.message || ex.toString();
+                    errors.password = (ex.message || ex.toString()).replace("\n", " ");
+                    errors.password += "\n" + _("Press again to confirm this weak password.");
```
Comment (martinpitt) [inline pkg/users/account-create-dialog.js:217]: Can we be sure that "weak password" is the only exception ever being thrown here? What if pwquality isn't installed/set up correctly/some other OS error happened?

File: pkg/users/password-dialogs.js [hunk 5]
```diff
@@ -148,7 +148,10 @@ export function password_quality(password) {
                     }
                 })
                 .fail(function(ex) {
-                    reject(new Error(ex.message || _("Password is not acceptable")));
+                    if (force)
+                        reject(new Error(ex.message || _("Password is not acceptable")));
```
Comment (martinpitt) [inline pkg/users/password-dialogs.js:152]: ... because here it can absolutely fail with a generic OS error.

**Review by martinpitt — CHANGES_REQUESTED** [review]
Thanks! :+1: to the idea of allowing weak passwords that way.

File: test/verify/check-accounts (hunk 2 above)
Comment (marusak) [reply test/verify/check-accounts:145]: We have at least one more place in tests where we set up a good password. But I can keep it here as well

File: pkg/users/account-create-dialog.js (hunk 4 above)
Comment (marusak) [reply pkg/users/account-create-dialog.js:217]: well, won't we then allow user to overrule? When pwquality is not installed for example, we surely want user to be able to create user.

File: pkg/users/password-dialogs.js (hunk 5 above)
Comment (marusak) [reply pkg/users/password-dialogs.js:152]: riight, I can probably check for some strings so it makes sure that the password was rejected, but on the other hand it feels like even if it fails in some buggy way (like `pwscore` fails because it misses some library or what now) we still should allow users to continue.

File: test/verify/check-accounts (hunk 2 above)
Comment (martinpitt) [reply test/verify/check-accounts:145]: That's fine then -- no need to duplicate, it just wasn't clear from the diff.

File: pkg/users/account-create-dialog.js (hunk 4 above)
Comment (marusak) [reply pkg/users/account-create-dialog.js:217]: Yeap.

`sudo mount -o bind /usr/bin/false /usr/bin/pwscore`

and then in the UI `Password is not acceptable` and you cannot proceed.

Comment (andreasn) [inline pkg/users/account-create-dialog.js:217]: Press what again? I think it would be clearer if you say `Press the Apply button again`

**Comment by andreasn** [comment]
There seem to be a case where passwd will completely block weak passwords (and not only warn against them) if some PAM flag is set. Wasn't able to figure out the exact flag though, so couldn't replicate. Are we checking for that?
https://linuxhint.com/secure_password_policies_ubuntu/

File: pkg/users/account-create-dialog.js (hunk 4 above)
Comment (andreasn) [reply pkg/users/account-create-dialog.js:217]: Or, shorter "Press Apply again"

**Comment by marusak** [comment]
> There seem to be a case where passwd will completely block weak passwords...

Ha, fun! So I spent some time playing with users both on commandline and in Cockpit. Creating, setting up and changing passwords. Here are the finds:
1. Indeed, you can enforce password strength with pam. But it seems to be accepted only by `passwd`. We don't use `passwd` to set up user password.
2. `chpasswd` seems to ignore both `/etc/pam.d/system-auth` and `/etc/security/pwquality.conf` (first is used for `passwd`, the other for `pwscore`)
3. We use `pwscore` to help to determine if the password is "good enough", but this is no security measure (thus this PR to be able to overrule)
4. We use `chpasswd` and not `passwd` to set up and change passwords thus we don't enforce anything
5. Even if we used `passwd` we would most likely need to drop the whole `pwscore` check as `/etc/pam.d/system-auth` and `/etc/security/pwquality.conf` are two different configs. (so if you setup in the pam one `minlenght=9` and in the pwquality one `minlenght=8` we would first allow password of length 8 and then it would fail on `passwd` as it is not long enough. Lets not forget that `pwscore` by default has some reasonable defaults, passwd does not (thus we would go back on advising to use a good passwords).

File: pkg/users/account-create-dialog.js (hunk 4 above)
Comment (marusak) [reply pkg/users/account-create-dialog.js:217]: The wording on buttons is `Create` in user create dialog and `Set` in password change dialog.
So should I go with:
- `Press Create again to confirm this weak password.`
- `Press Set again to confirm this weak password.`
?

Comment (marusak) [reply pkg/users/account-create-dialog.js:217]: Anaconda uses:
`Press Done again to use the password anyway.`

Comment (marusak) [reply pkg/users/account-create-dialog.js]: Ok, I went with:
- `Press Create again to use the password anyway.`
- `Press Set again to use the password anyway.`
of course I am happy to change it again.

Comment (martinpitt) [reply pkg/users/account-create-dialog.js]: > of course I am happy to change it again.

But only if you ask twice! :wink:

**Comment by marusak** [comment]
Screenshot:
weakpassword

File: pkg/users/account-create-dialog.js (hunk 4 above)
Comment (martinpitt) [reply pkg/users/account-create-dialog.js]: Showing an exception text plus "press again to do it anyway" if pwscore fails feels a little weird -- but at the same time, we do want to inform the user about that failure somehow. Given how badly broken it is right now in the "pwscore fails" case, I think it's good and robust enough now.

File: pkg/users/password-dialogs.js (hunk 5 above)
Comment (martinpitt) [inline pkg/users/password-dialogs.js:152]: Why does this throw an exception when forcing is *on*? That looks the wrong way around.

File: pkg/users/account-create-dialog.js [hunk 6]
```diff
@@ -209,9 +211,10 @@ export function account_create_dialog(accounts) {
 
         errors.user_name = validate_username(state.user_name, accounts);
 
-        return password_quality(state.password)
+        return password_quality(state.password, force)
                 .catch(ex => {
-                    errors.password = ex.message || ex.toString();
+                    errors.password = (ex.message || ex.toString()).replace("\n", " ");
+                    errors.password += "\n" + _("Press Create again to use the password anyway.");
```
Comment (martinpitt) [inline pkg/users/account-create-dialog.js:217]: Use cockpit.format and `_("Press $0 again...")` with $0 == `_("Create")`. This:

 1. ensures that the button text is always consistent between the button itself and that error message, especially if one is translated and the other is not.
 2. The translation of this sentence is then shared with pkg/users/password-dialogs.js

**Review by martinpitt — CHANGES_REQUESTED** [review]
Dakujem!

File: pkg/users/password-dialogs.js (hunk 5 above)
Comment (marusak) [reply pkg/users/password-dialogs.js]: Yeah, the name was the wrong name around. Fixed

File: pkg/users/account-create-dialog.js (hunk 6 above)
Comment (marusak) [reply pkg/users/account-create-dialog.js]: Good idea. Was thinking how to use one string for translation and this seems like a good approach. Updated.

**Review by martinpitt — APPROVED** [review]
Cheers! I'd like to let @andrasn sign off too, though.

File: test/verify/check-accounts [hunk 7]
```diff
@@ -135,16 +135,36 @@ class TestAccounts(MachineCase):
...
+        b.set_input_text('#accounts-create-pw1', "foo")
+        b.set_input_text('#accounts-create-pw2', "foo")
         b.set_checked('#accounts-create-locked', True)
         b.click('#accounts-create-dialog button.apply')
+
+        # Password is weak, lets change it to another weak - this should still not accept
+        b.wait_in_text("#accounts-create-dialog .dialog-error.help-block", "Password quality check failed:")
+        if m.image != "rhel-8-3-distropkg": # Introduced in #14557
+            b.wait_in_text("#accounts-create-dialog .dialog-error.help-block", "Press Create again to use the password anyway.")
```
Comment (andreasn) [inline test/verify/check-accounts:152]: Reading the RHEL documentation, I realized it uses the word `Click`, rather than `Press`
[See 1.3, item 4](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/managing_systems_using_the_rhel_8_web_console/getting-started-with-the-rhel-8-web-console_system-management-using-the-rhel-8-web-console#logging-in-to-the-web-console_getting-started-with-the-rhel-8-web-console)

File: test/verify/check-accounts [hunk 8]
```diff
@@ -135,16 +135,36 @@ class TestAccounts(MachineCase):
...
+        b.set_input_text('#accounts-create-pw1', "bar")
+        b.set_input_text('#accounts-create-pw2', "bar")
+        b.wait_not_present("#accounts-create-dialog .dialog-error.help-block")
+        b.click('#accounts-create-dialog button.apply')
+
+        # Lets confirm the weak password now
+        b.wait_in_text("#accounts-create-dialog .dialog-error.help-block", "Password quality check failed:")
+        if m.image != "rhel-8-3-distropkg": # Introduced in #14557
+            b.wait_in_text("#accounts-create-dialog .dialog-error.help-block", "Press Create again to use the password anyway.")
```
Comment (andreasn) [inline test/verify/check-accounts:161]: Same as above.

**Review by andreasn — CHANGES_REQUESTED** [review]
Just very tiny wording details. Apart from that, should be good to go!

File: test/verify/check-accounts (hunk 7 above)
Comment (marusak) [reply test/verify/check-accounts]: Updated

**Review by andreasn — APPROVED** [review]
Looks good to me!

**Review by martinpitt — APPROVED** [review]
