### PR TITLE
hwinfo: Never show 'undefined' in HW field

### LINKED ISSUE #12593: System Hardware field shows 'undefined undefined'
Cockpit version: cockpit-200-2.fc30.x86_64
OS: Fedora 30 Server
Page: 
System

Hardware shows 'undefined undefined' see screenshot
Screenshot_2019-08-17 System - fnuc local

Steps to reproduce

1. Point browser to cockpit, happens out of the box on a default Fedora 30 Server installation
2.
3.

$ rpm -qa | grep cockpit
cockpit-system-200-2.fc30.noarch
cockpit-storaged-200-2.fc30.noarch
cockpit-bridge-200-2.fc30.x86_64
cockpit-selinux-200-2.fc30.noarch
cockpit-networkmanager-200-2.fc30.noarch
cockpit-docker-200-2.fc30.x86_64
cockpit-packagekit-200-2.fc30.noarch
cockpit-ws-200-2.fc30.x86_64
cockpit-200-2.fc30.x86_64
cockpit-dashboard-200-2.fc30.noarch
[chris@fnuc ~]$

### PR DESCRIPTION
**Pull request by marusak**
When `sys_vendor` is undefined try `board_vendor`.
When `product_name` is undefined try `board_name`.
When either of vendor or name is not defined by neither of those
options, then just show `Details`.

Fixes #12593

### CODE REVIEW

File: pkg/systemd/hw-detect.js [hunk 1]
```diff
@@ -23,6 +23,8 @@ import * as machine_info from "machine-info.js";
 const InfoDMIKey = {
     version: "product_version",
     name: "product_name",
+    alt_version: "board_vendor",
```
Comment (mvollmer) [inline pkg/systemd/hw-detect.js]: This looks wrong.  THis mixes "version" and "vendor", is that intended?

File: pkg/systemd/host.js [hunk 2]
```diff
@@ -750,7 +750,12 @@ PageServer.prototype = {
         hardware_text.tooltip({ title: _("Click to see system hardware information"), placement: "bottom" });
         machine_info.dmi_info()
                 .done(function(fields) {
-                    hardware_text.text(fields.sys_vendor + " " + fields.product_name);
+                    let vendor = fields.sys_vendor || fields.board_vendor;
+                    let name = fields.product_name || fields.board_name;
```
Comment (mvollmer) [inline pkg/systemd/host.js]: This means we might get "sys_vendor board_name".  Does that make sense?  Or is there some guarantee that if sys_vendor is present, so is product_name.

File: pkg/systemd/host.js [hunk 3]
```diff
@@ -750,7 +750,12 @@ PageServer.prototype = {
         hardware_text.tooltip({ title: _("Click to see system hardware information"), placement: "bottom" });
         machine_info.dmi_info()
                 .done(function(fields) {
-                    hardware_text.text(fields.sys_vendor + " " + fields.product_name);
+                    let vendor = fields.sys_vendor || fields.board_vendor;
```
Comment (Gundersanne) [inline pkg/systemd/host.js]: The fields board_vendor and board_ name are never set

File: pkg/systemd/hw-detect.js (hunk 1 above)
Comment (Gundersanne) [inline pkg/systemd/hw-detect.js]: I would just call the keys `board_vendor` and `board_name` instead of alt_*

Comment (Gundersanne) [reply pkg/systemd/hw-detect.js]: There's also a board_version? But that one seems more likely to be undefined

**Comment by marusak** [comment]
Right @mvollmer, doesn't make sense to combine vendor, product and board all together. I've switched it to use what we use now or use all `board` stuff (board_vendor + board_name).
Does it make more sense? Or should we just check if what we use now is undefined and then show `Details` without trying to show any different info?

**Comment by marusak** [comment]
> But the test still fails

ah, of course, the test I wrote did not make any sense. Fixed
