### PR TITLE
common: Fix test-webserver for environments with only loopback interface

### LINKED ISSUE #11312: Rawhide FTBFS in test-webserver: assertion failed: (inet != NULL)
Recently, Cockpit started to [fail to build in Rawhide](https://koji.fedoraproject.org/koji/taskinfo?taskID=32925549) (F29 and F30 were okay). The [tests](https://kojipkgs.fedoraproject.org//work/tasks/5571/32925571/build.log) fail like this:
```
FAIL: test-webserver 9 /web-server/handle-resource
**
cockpit-protocol:ERROR:src/common/test-webserver.c:57:setup: assertion failed: (inet != NULL)
```
(There's 12 similar failures).

### PR DESCRIPTION
**Pull request by martinpitt**
If there is no non-loopback interface (which is common in e. g. mock
nspawn environments), leave `TestCase.hostport` as `NULL` instead of
crashing with an assertion. Skip the tests (or parts of them) which
require an external address.

Fixes #11312

### CODE REVIEW

**Comment by martinpitt** [comment]
Note: In my personal environment, I additionally need to replace `localhost` with `127.0.0.1` in `setup()`. With that, the test passes, otherwise I get
```
/web-server/query-string: **
cockpit-protocol:ERROR:src/common/test-webserver.c:357:perform_http_request: assertion failed (error == NULL): Error resolving ?localhost?: Name or service not known (g-resolver-error-quark, 0)
```
This is a bit dubious -- in that environment `localhost` does resolve.. mostly:
```
<mock-chroot> sh-5.0$ getent ahosts localhost
::1             STREAM localhost
::1             DGRAM  
::1             RAW    
127.0.0.1       STREAM 
127.0.0.1       DGRAM  
127.0.0.1       RAW   
 
<mock-chroot> sh-5.0$ getent ahostsv4 localhost
<mock-chroot> sh-5.0$ getent ahostsv6 localhost
```
So the latter two are dubious -- this works on the host as expected. This might be what trips up `g_socket_client_connect_to_host_async()`. But if that also happens on the Fedora builders, I'd rather investigate this more closely.

File: src/common/test-webserver.c [hunk 1]
```diff
@@ -803,19 +816,23 @@ test_address (TestCase *tc,
     }
   else
     {
-      assert_cannot_connect (tc->localport);
+      if (tc->hostport)
+        assert_cannot_connect (tc->localport);
```
Comment (martinpitt) [inline src/common/test-webserver.c]: This may look a bit weird. If there is only one interface, then `cockpit_web_server_new` will get a NULL address and thus *do* listen on loopback (as there is no other place to listen). So this is intended.

**Comment by martinpitt** [comment]
We don't run the unit tests in image-prepare, and i386 tests succeeded in semaphore. So I'm not patient enough to retry the fedora-i386 kernel oops, it's unrelated.

**Comment by martinpitt** [comment]
Pushed the addition of the comment. Can you please re-review?
