### PR TITLE
systemd/services: Read CLOCK_BOOTTIME with Python

### LINKED ISSUE #18418: Services: Wrong timer "next run" with machine suspends
I have a custom backup timer, which runs every hour. The "Last trigger" is right, but the "next run" is is utter nonsense, and even in the past:

image

The real value:
```
❱❱❱ systemctl --user list-timers|cat
NEXT                        LEFT       LAST                        PASSED     UNIT                    ACTIVATES
Mon 2023-02-27 22:30:53 CET 31min left Mon 2023-02-27 21:30:53 CET 28min ago  backup.timer            backup.service
```

This is probably some mistake with the Realtime calculation, during the time when my laptop is suspended? I didn't investigate that yet, will do after my other umpteen bugs that I am currently looking at on the Services page :grin:

### PR DESCRIPTION
**Pull request by martinpitt**
Before it was bogus:

image

Now it's correct:

image

```
❱❱❱ systemctl --user list-timers
NEXT                        LEFT       LAST                        PASSED     UNIT                    ACTIVATES                
Wed 2023-03-08 10:34:19 CET 27min left Wed 2023-03-08 09:34:19 CET 32min ago  backup.timer            backup.service
n/a                         n/a        Sat 2023-03-04 07:28:53 CET 4 days ago grub-boot-success.timer grub-boot-success.service

❱❱❱ date
Wed Mar  8 10:06:30 AM CET 2023
```

Fixes #18418

### CODE REVIEW

File: pkg/systemd/services/services.jsx [hunk 1]
```diff
@@ -59,22 +59,26 @@ export const systemd_client = {
...
+            .then(([uptime_contents, date_output]) => {
+                clock_realtime_now = parseInt(date_output, 10) * 1000;
+
+                // first number in /proc/uptime is time since boot (CLOCK_BOOTTIME) in seconds with two fractional digits
+                const uptime = parseFloat(uptime_contents.split(' ')[0]);
+                const clock_boottime_now = parseInt(uptime * 1000000, 10);
+
+                monotonic_timer_base = clock_realtime_now * 1000 - clock_boottime_now;
+            })
+            .catch(ex => console.warn("Failed to read boot time:", ex.toString()));
```
Comment (cockpituous) [inline pkg/systemd/services/services.jsx:81]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18466-20230308-073420-5f113059-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/services/services.jsx [hunk 2]
```diff
@@ -60,22 +61,42 @@ export const systemd_client = {
...
+                /* If Python is not available, fall back to reading CLOCK_BOOTTIME from /proc/uptime. This will
+                 * give incorrect results if the machine was suspended during the current boot, but it's the
+                 * best approximation that we can get. */
+                console.log("Failed to read clocks with Python, using boot time fallback:", ex.toString());
+                Promise.all([
+                    cockpit.file("/proc/uptime").read(),
+                    cockpit.spawn(["date", "+%s"])
+                ])
+                        .then(([uptime_contents, date_output]) => {
+                            clock_realtime_now = parseInt(date_output, 10) * 1000;
```
Comment (cockpituous) [inline pkg/systemd/services/services.jsx:89]: These 11 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18466-20230308-091051-1f44fdef-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/services/services.jsx [hunk 3]
```diff
@@ -60,22 +61,42 @@
...
+
+                            // first number in /proc/uptime is time since boot (CLOCK_BOOTTIME) in seconds with two fractional digits
+                            const uptime = parseFloat(uptime_contents.split(' ')[0]);
+                            const clock_boottime_now = parseInt(uptime * 1000000, 10);
```
Comment (cockpituous) [inline pkg/systemd/services/services.jsx:93]: These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18466-20230308-091051-1f44fdef-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/services/services.jsx [hunk 4]
```diff
@@ -60,22 +61,42 @@
...
+
+                            monotonic_timer_base = clock_realtime_now * 1000 - clock_boottime_now;
+                        })
+                        .catch(ex => console.warn("Failed to read boot time:", ex.toString()));
+            }
```
Comment (cockpituous) [inline pkg/systemd/services/services.jsx:98]: These 4 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18466-20230308-091051-1f44fdef-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/services/services.jsx (hunk 2 above)
Comment (martinpitt) [reply pkg/systemd/services/services.jsx:89]: They actually would be on our fcos image, as that doesn't have Python.

Comment (mvollmer) [reply pkg/systemd/services/services.jsx:89]: What?  That's insanity.

File: pkg/systemd/services/services.jsx [hunk 5]
```diff
@@ -66,20 +67,36 @@ let monotonic_timer_base = null; // µs
...
+            .then(output => {
+                const [realtime, monotonic] = output.split(' ').map(ns => parseInt(ns));
+                clock_realtime_now = realtime / 1000000;
+                monotonic_timer_base = (realtime - monotonic) / 1000;
             })
-            .catch(ex => console.warn("Failed to read boot time:", ex.toString()));
+            .catch(ex => {
+                /* If Python is not available, fall back to reading CLOCK_BOOTTIME from /proc/uptime. This will
+                 * give incorrect results if the machine was suspended during the current boot, but it's the
+                 * best approximation that we can get. */
```
Comment (mvollmer) [inline pkg/systemd/services/services.jsx:82]: Hmm, I would say wrong information is worse than no information. Can we fall back to something horrible that gives the right information, like spawning "systemctl"?

File: pkg/systemd/services/services.jsx (hunk 2 above)
Comment (martinpitt) [reply pkg/systemd/services/services.jsx:89]: @mvollmer : You mean CoreOS not having Python? Consciuous decision on their side as they don't like Ansible. Or in case you didn't mean that: I wasn't suggesting to actually run/expose coverage on fcos (we skip half of the tests there, after all) -- it was just an explanation.

File: pkg/systemd/services/services.jsx (hunk 5 above)
Comment (martinpitt) [reply pkg/systemd/services/services.jsx:82]: It's hard to decide if it's wrong, unfortunately.  I discussed some options in #18418 . 

Most servers don't get suspended, this is mostly a desktop thing -- thus it would be bearable, and at least fix the situation for the 90% case. For the fallback, I could imagine parsing /proc/timer_list with `superuser: require`, and just don't show any timer information at all if you are not root. This would then not even work for the "Users" units, though.

File: pkg/systemd/services/services.jsx (hunk 2 above)
Comment (mvollmer) [reply pkg/systemd/services/services.jsx:89]: > @mvollmer : You mean CoreOS not having Python? Consciuous decision on their side as they don't like Ansible.

That's what I meant. Hmm.

File: pkg/systemd/services/services.jsx (hunk 5 above)
Comment (martinpitt) [reply pkg/systemd/services/services.jsx:82]: A simpler alternative would of course be to just not show any timer information without python. I don't have a stong opinion either way.. Soon, we will require Python anyway :grin:

Comment (mvollmer) [reply pkg/systemd/services/services.jsx:82]: > A simpler alternative would of course be to just not show any timer information without python.

Yeah, personally I think this is the right thing to do.

Comment (mvollmer) [reply pkg/systemd/services/services.jsx:82]: > > A simpler alternative would of course be to just not show any timer information without python.
> 
> Yeah, personally I think this is the right thing to do.

And if people complain, we could somehow export the timers from cockpit-bridge.

Comment (martinpitt) [reply pkg/systemd/services/services.jsx:82]: Ack. Also, it doesn't actually affect *all* timers -- e.g. OnCalendar= is fine. Only monotonic ones. Let's do that then.

File: pkg/systemd/services/services.jsx [hunk 6]
```diff
@@ -70,16 +71,43 @@ function debug() {
...
+                monotonic_timer_base = (realtime - monotonic) / 1000;
+                debug("Read clocks with Python; realtime", clock_realtime_now, "monotonic base", monotonic_timer_base);
+            })
+            .catch(ex => {
+                /* If Python is not available, fall back to reading CLOCK_BOOTTIME from /proc/timer-list.
+                 * This is readable by root only */
+                console.log("Failed to read clocks with Python, using fallback:", ex.toString());
+                Promise.allSettled([
+                    cockpit.spawn(["date", "+%s"]),
+                    cockpit.file("/proc/timer_list", { superuser: "try" }).read(),
```
Comment (cockpituous) [inline pkg/systemd/services/services.jsx:89]: These 7 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18466-20230309-111146-2a80128f-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/services/services.jsx [hunk 7]
```diff
@@ -70,16 +71,43 @@
...
+                ])
+                        .then(([date_result, timer_list_result]) => {
+                            if (date_result.status === "fulfilled") {
+                                clock_realtime_now = parseInt(date_result.value) * 1000;
```
Comment (cockpituous) [inline pkg/systemd/services/services.jsx:93]: These 3 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18466-20230309-111146-2a80128f-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/services/services.jsx [hunk 8]
```diff
@@ -70,16 +71,43 @@
...
+                            } else {
+                                console.warn("Failed to read realtime clock:", date_result.reason.toString());
+                                return;
```
Comment (cockpituous) [inline pkg/systemd/services/services.jsx:96]: These 2 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18466-20230309-111146-2a80128f-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/services/services.jsx [hunk 9]
```diff
@@ -70,16 +71,43 @@
...
+                            }
+
+                            // third line is "now at N nsecs"
+                            if (timer_list_result.status === "fulfilled") {
+                                const match = /now at (\d+) nsecs/.exec(timer_list_result.value);
+                                if (match)
+                                    monotonic_timer_base = clock_realtime_now * 1000 - parseInt(match[1]) / 1000;
```
Comment (cockpituous) [inline pkg/systemd/services/services.jsx:103]: These 5 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18466-20230309-111146-2a80128f-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/services/services.jsx [hunk 10]
```diff
@@ -70,16 +71,43 @@
...
+
+                                debug("Read clocks with fallback; realtime", clock_realtime_now, "monotonic base", monotonic_timer_base);
```
Comment (cockpituous) [inline pkg/systemd/services/services.jsx:105]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18466-20230309-111146-2a80128f-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/systemd/services/services.jsx [hunk 11]
```diff
@@ -70,16 +71,43 @@
...
+                            } else {
+                                console.log("Failed to read /proc/timer_list:", timer_list_result.reason.toString());
```
Comment (cockpituous) [inline pkg/systemd/services/services.jsx:107]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18466-20230309-111146-2a80128f-fedora-37-devel//Coverage/lcov/github-pr.diff.gcov.html)

**Comment by martinpitt** [comment]
[TestLogin.testServer](https://cockpit-logs.us-east-1.linodeobjects.com/pull-18466-20230309-140243-2a80128f-centos-8-stream-pybridge/log.html#185-2) has been failing on c8s/pybridge for a while now.. I guess I'll look at that next.

**Comment by martinpitt** [comment]
@jelly , @KKoukiou : As Marius is AFK for a while now, would you mind having a look?

**Comment by martinpitt** [comment]
Test failures are independent and fixed in PR #18480

**Review by jelly — APPROVED** [review]

**Comment by jelly** [comment]
> > Approved, but shouldn't we add a more strict test now that the time is calculated correctly? Can be a follow up.
> 
> This only happens for suspended machines. I'm not sure if we can suspend our test VMs and wake them up again? With the monitor that doesn't seem completely unreasonable. Of course we'd have to suspend it for at least one minute to be able to tell the difference. Hmm..

Ah right that's tricky and maybe it's also buggy to suspend/resume VM's
