### PR TITLE
bridge: Support internal cgroupsv2 metrics

### LINKED ISSUE #14420: internal CGroup metrics do not work on cgroupv2
Cockpit version: cockpit-223-1.fc32.x86_64
OS: Fedora 32 (Workstation Edition)

CGroup Sampling seems to be not working on Fedora32. The prefix is no longer `/sys/fs/cgroup/memory` or `/sys/fs/cgroup/cpu` 
 as defined here [cockpitcgroupsamples.c](https://github.com/cockpit-project/cockpit/blob/2370dd7852dcbaf6e72617e1a185d010cf688663/src/bridge/cockpitcgroupsamples.c#L29), this is the dir list on my fedora32:
```
eric@localhost:~/coding/starter-kit$ ls -l /sys/fs/cgroup/
总用量 0
-r--r--r--.   1 root root 0  7月 28  2020 cgroup.controllers
-rw-r--r--.   1 root root 0  7月 27 21:33 cgroup.max.depth
-rw-r--r--.   1 root root 0  7月 27 21:33 cgroup.max.descendants
-rw-r--r--.   1 root root 0  7月 28  2020 cgroup.procs
-r--r--r--.   1 root root 0  7月 27 21:33 cgroup.stat
-rw-r--r--.   1 root root 0  7月 27 22:59 cgroup.subtree_control
-rw-r--r--.   1 root root 0  7月 27 21:33 cgroup.threads
-rw-r--r--.   1 root root 0  7月 27 21:33 cpu.pressure
-r--r--r--.   1 root root 0  7月 27 21:33 cpuset.cpus.effective
-r--r--r--.   1 root root 0  7月 27 21:33 cpuset.mems.effective
drwxr-xr-x.   2 root root 0  7月 27 21:59 init.scope
-rw-r--r--.   1 root root 0  7月 27 21:33 io.cost.model
-rw-r--r--.   1 root root 0  7月 27 21:33 io.cost.qos
-rw-r--r--.   1 root root 0  7月 27 21:33 io.pressure
drwxr-xr-x.   5 root root 0  7月 27 22:41 machine.slice
-rw-r--r--.   1 root root 0  7月 27 21:33 memory.pressure
drwxr-xr-x. 133 root root 0  7月 28 01:07 system.slice
drwxr-xr-x.   4 root root 0  7月 27 21:59 user.slice
```

I also tried to use starter-kit to fetch some cgroup message:
```js
testMetric() {
    var usageMetricsChannel = cockpit.metrics(1000, {
        source: "internal",
        metrics: [{ name: "cgroup.memory.usage", units: "bytes" }]
    });
    usageMetricsChannel.follow();
    usageMetricsChannel.onchanged = function () {
        console.log("onchanged, usageMetricsChannel: ", usageMetricsChannel);
    };
}
```
And I got nothing, not only the log, but all message in this channel:
image

Also, it works find on my Ubuntu20, with cockpit215, but it's CGroupV1, having `/sys/fs/cgroup/memory` or `/cpu` dir.

### PR DESCRIPTION
**Pull request by martinpitt**
We don't use this metric in cockpit itself for v2 - the docker page uses v1 (and its integration tests will make sure this does not regress). But I need it for https://github.com/martinpitt/performance-graphs to add the top CPU/memory consumers.

I added a smoke unit test, but the real functional test for now is something like this:

```
{ printf '\n{ "command": "open", "channel": "c", "payload": "metrics1", "source": "internal", "interval": 1000, "metrics": [ {"name": "cgroup.cpu.usage"} ] }\n---\n'; sleep 3; } | ./cockpit-bridge --interact=---
```

Fixes #14420

### CODE REVIEW

**Comment by marusak** [comment]
Would this help with https://github.com/cockpit-project/cockpit-podman/issues/165 (or https://github.com/cockpit-project/cockpit-podman/pull/458) ? :crossed_fingers:

**Comment by martinpitt** [comment]
@marusak: Yes, it would indeed. Of course you'd still need to add some heuristics to filter out which cgroups belong to podman containers, but that should be easy enough -- looks like filtering for "libpod-.*.scope" or "podman-.*.scope" shoud do the trick. (libpod-* looks like the pause container, and podman-* the real ones)

**Review by allisonkarlitskaya — APPROVED** [review]
To be honest, this looks really good.  My only suggestion is more of an opportunistic drive-by cleanup than an actual problem with this patch.

File: src/bridge/test-metrics.c [hunk 1]
```diff
@@ -719,6 +719,65 @@ test_deprecated_net_all (void)
...
+                          "options", options,
+                          NULL);
+
+  cockpit_channel_prepare (channel);
+
+  /* receive meta information */
+  while ((msg = mock_transport_pop_channel (transport, "1234")) == NULL)
+    g_main_context_iteration (NULL, TRUE);
+  res = cockpit_json_parse_bytes (msg, NULL);
+  g_assert (res != NULL);
```
[the remark this answers is not in the document]
Comment (martinpitt) [reply src/bridge/test-metrics.c:752]: Added.

File: src/bridge/cockpitcgroupsamples.c [hunk 2]
```diff
@@ -29,14 +29,14 @@
 const gchar *cockpit_cgroup_memory_root = "/sys/fs/cgroup/memory";
 const gchar *cockpit_cgroup_cpuacct_root = "/sys/fs/cgroup/cpuacct";
 
-static double
-read_double (const gchar *prefix,
-             const gchar *suffix)
+static gint64
+read_int64 (const gchar *prefix,
```
[the remark this answers is not in the document]
Comment (martinpitt) [reply src/bridge/cockpitcgroupsamples.c]: I had that in mind, then first shyed away from the whole rewrite. But it is so much more elegant, I changed the code now. Now the v1 code is much more consistent with the v2 one.

File: src/bridge/cockpitcgroupsamples.c [hunk 3]
```diff
@@ -26,41 +26,65 @@
...
+                     const gchar *value_prefix)
+{
+  g_autofree gchar *file_contents = read_file (path_prefix, path_suffix);
+  const gchar *offset;
 
-  return ret;
+  if (file_contents == NULL)
+      return -1;
+
+  offset = strstr (file_contents, value_prefix);
```
[the remark this answers is not in the document]
Comment (martinpitt) [reply src/bridge/cockpitcgroupsamples.c]: I went with a single read now. With cgroupsv2 the format is specified clearly (three fixed key names and long long values), so IMHO we can get away with a single 256 byte buffer and read.

**Comment by martinpitt** [comment]
Updated for openat(), fixed a few places where values can be legitimately 0, and added the missing swap usage/max. I tested this on my cgroupsv2 fedora 32, and on v1 rhel 8.3.

**Comment by martinpitt** [comment]
[this failure](https://logs.cockpit-project.org/logs/pull-14540-20200902-053946-c63d807b-fedora-33/log.html#246) is unrelated, but worth looking into. Looks like fedora-33 has unlearned memfd creation for restricted users?

File: src/bridge/cockpitcgroupsamples.c [hunk 4]
```diff
@@ -21,119 +21,207 @@
...
+
+static gint64
+read_int64 (int dirfd,
+            const char *cgroup,
+            const char *fname)
+{
+  const char *contents = read_file (dirfd, cgroup, fname);
+  if (contents == NULL)
+      return -1;
+  return atoll (contents);
```
Comment (allisonkarlitskaya) [inline src/bridge/cockpitcgroupsamples.c:88]: We're talking to the kernel, of course, so I'm not sure how much error checking you want, ...

but maybe the file format changes or something?  We have warnings above for missing files...

File: src/bridge/cockpitcgroupsamples.c [hunk 5]
```diff
@@ -21,119 +21,207 @@
...
 {
-  gchar *path = NULL;
-  gchar *file_contents = NULL;
-  GError *error = NULL;
-  double ret;
-  gsize len;
-
-  path = g_build_filename (prefix, suffix, NULL);
-  if (!g_file_get_contents (path, &file_contents, &len, &error))
+  static char buf[256];
```
[the remark this answers is not in the document]
Comment (allisonkarlitskaya) [reply src/bridge/cockpitcgroupsamples.c:41]: ....you could also return a `FILE *` from this function :speak_no_evil:

**Review by allisonkarlitskaya — CHANGES_REQUESTED** [review]

File: src/bridge/cockpitcgroupsamples.c [hunk 6]
```diff
@@ -21,119 +21,207 @@
...
-      ret = g_ascii_strtod (file_contents, NULL);
+      g_message ("error loading file: %s/%s: %m", cgroup, fname);
+      goto out;
     }
+  if (len >= sizeof buf)
+    {
+      g_warning ("cgroupfs value %s/%s is too large", cgroup, fname);
+      goto out;
+    }
+  buf[len] = '\0';
```
[the remark this answers is not in the document]
Comment (martinpitt) [reply src/bridge/cockpitcgroupsamples.c:70]: It's not, as `len == sizeof` is rejected. Not sure how to write that more clearly; would this comment help?
```c
  /* we really expect a much smaller read; if we get a full buffer, there's likely
   * more data, and we are misinterpreting stuff */
  if (len >= sizeof buf)
```

File: src/bridge/cockpitcgroupsamples.c [hunk 7]
```diff
@@ -21,119 +21,207 @@
...
-const gchar *cockpit_cgroup_memory_root = "/sys/fs/cgroup/memory";
-const gchar *cockpit_cgroup_cpuacct_root = "/sys/fs/cgroup/cpuacct";
+const char *cockpit_cgroupv1_memory_root = "/sys/fs/cgroup/memory";
+const char *cockpit_cgroupv1_cpuacct_root = "/sys/fs/cgroup/cpuacct";
+const char *cockpit_cgroupv2_root = "/sys/fs/cgroup";
 
-static double
-read_double (const gchar *prefix,
-             const gchar *suffix)
+static const char*
```
[the remark this answers is not in the document]
Comment (martinpitt) [reply src/bridge/cockpitcgroupsamples.c:36]: Fixed

File: src/bridge/cockpitcgroupsamples.c (hunk 5 above)
[the remark this answers is not in the document]
Comment (martinpitt) [reply src/bridge/cockpitcgroupsamples.c]: Did the first suggestion.

File: src/bridge/cockpitcgroupsamples.c (hunk 4 above)
Comment (martinpitt) [reply src/bridge/cockpitcgroupsamples.c]: I added error checking for read_prefixed_int64(), but reverted it for general read_int64(). There are a lot of attributes whose value is "max" for example, and I don't want to hardcode a list of expected non-numbers, but just treat them as absent. So I went back to atoll() and ignoring a zero result where that is invalid.

File: src/bridge/cockpitcgroupsamples.c [hunk 8]
```diff
@@ -21,119 +21,223 @@
...
+const char *cockpit_cgroupv1_memory_root = "/sys/fs/cgroup/memory";
+const char *cockpit_cgroupv1_cpuacct_root = "/sys/fs/cgroup/cpuacct";
+const char *cockpit_cgroupv2_root = "/sys/fs/cgroup";
 
-static double
-read_double (const gchar *prefix,
-             const gchar *suffix)
+static const char *
+read_file (int dirfd,
+           char* buf,
```
Comment (allisonkarlitskaya) [inline src/bridge/cockpitcgroupsamples.c:38]: hate to nag, but: `char *buf`

File: src/bridge/cockpitcgroupsamples.c [hunk 9]
```diff
@@ -21,119 +21,223 @@
...
+  val = read_int64 (dirfd, cgroup, "cpu.weight");
+  if (val > 0 && val < G_MAXINT64)
+    cockpit_samples_sample (samples, "cgroup.cpu.shares", cgroup, val);
+
+  /* cpu.stat: keyed file:
+     usage_usec 50000
+     user_usec 40000
+     system_usec 10000
+     */
+  val = read_prefixed_int64 (dirfd, cgroup, "cpu.stat", "usage_usec ");
```
Comment (allisonkarlitskaya) [inline src/bridge/cockpitcgroupsamples.c:204]: Your approach here gives me pause.  What if some day they add a field called `max_usage_usec`?  Then this would match on that...

This is why I was leaning toward iterating over the lines...  I guess another thing you could do is to ensure that any match is either at the start of the buffer, or proceeded by a `\n` (and search for other matches, if not).

What do you think about this issue?

File: src/bridge/cockpitcgroupsamples.c [hunk 10]
```diff
@@ -21,119 +21,223 @@
...
-  gsize prefix_len;
+  const char *paths[] = { root_dir, NULL };
+  gsize root_dir_len = strlen (root_dir);
   FTSENT *ent;
   FTS *fs;
 
-  prefix_len = strlen (prefix);
-
-  fs = fts_open ((gchar **)paths, FTS_NOCHDIR | FTS_COMFOLLOW, NULL);
+  fs = fts_open ((char **)paths, FTS_NOCHDIR | FTS_COMFOLLOW, NULL);
```
Comment (allisonkarlitskaya) [inline src/bridge/cockpitcgroupsamples.c:219]: 1. Cool.  I didn't know this class of functions existed!

2. Ugh.  A bit of an impedance mismatch here, now that we're in the `openat()` world.  That could be fixed with a followup, though.

**Review by allisonkarlitskaya — CHANGES_REQUESTED** [review]

File: src/bridge/cockpitcgroupsamples.c (hunk 8 above)
Comment (martinpitt) [reply src/bridge/cockpitcgroupsamples.c:38]: Fixed.

File: src/bridge/cockpitcgroupsamples.c (hunk 9 above)
Comment (martinpitt) [reply src/bridge/cockpitcgroupsamples.c]: Changed to checking the preceding char now, and renamed the function to match what it does.

File: src/bridge/cockpitcgroupsamples.c (hunk 10 above)
Comment (martinpitt) [reply src/bridge/cockpitcgroupsamples.c:228]: Would be nice if there was a walk function that spits out dirfds indeed, but I'm not aware of one.

File: src/bridge/cockpitcgroupsamples.c [hunk 11]
```diff
@@ -21,119 +21,232 @@
...
+      return -1;
+
+  /* search for a word match of key */
+  offset = contents;
+  for (;;) {
+      offset = strstr (offset, key);
+      if (offset == NULL)
+        return -1;
+      /* either matches at start of string, or after a line break */
+      if (offset == contents || offset[-1] == '\n')
```
Comment (allisonkarlitskaya) [inline src/bridge/cockpitcgroupsamples.c:120]: This looks weird because `offset` is a bad name for this variable.  `offset` should be an int, but this is a pointer to a (potentially matching) key.  Might be worth a rename.

File: src/bridge/cockpitcgroupsamples.c [hunk 12]
```diff
@@ -21,119 +21,232 @@
...
+        break;
+      offset += key_len;
+  }
```
Comment (allisonkarlitskaya) [inline src/bridge/cockpitcgroupsamples.c:123]: So, I *think* this loop is going to do the right thing, but wow... I think we might be squarely in "making this complicated in order to optimise the wrong things" territory...

**Review by allisonkarlitskaya — APPROVED** [review]
I don't like the approach, but I won't stand in the way any longer :)

File: src/bridge/cockpitcgroupsamples.c (hunk 12 above)
Comment (martinpitt) [reply src/bridge/cockpitcgroupsamples.c:123]: Well, it was simpler before, but you didn't like it :-)

File: src/bridge/cockpitcgroupsamples.c [hunk 13]
```diff
@@ -21,119 +21,232 @@
...
+  size_t key_len = strlen (key);
+  char *endptr = NULL;
+  gint64 result;
+
+  if (contents == NULL)
+      return -1;
+
+  /* search for a word match of key */
+  offset = contents;
+  for (;;) {
```
[the remark this answers is not in the document]
Comment (martinpitt) [reply src/bridge/cockpitcgroupsamples.c:115]: Argh, fixed.

File: src/bridge/cockpitcgroupsamples.c (hunk 11 above)
Comment (martinpitt) [reply src/bridge/cockpitcgroupsamples.c]: Good point. Renamed to "match".

**Review by allisonkarlitskaya — APPROVED** [review]
