### PR TITLE
shell: Apply host dialogs on form submission

### LINKED ISSUE #18653: After connection loss, submitting password with enter fails
### Explain what happens

1. Open cockpit and switch to a previously added remote server, see "Not connected to host; Login failed" message
2. Click login, type password and press enter key to confirm
3. See login fail.
4. Do the same, but *do not* press enter key but rather press the login button with a mouse and the login works.

### Version of Cockpit

287

### Where is the problem in Cockpit?

None

### Server operating system

Fedora

### Server operating system version

37

### What browsers are you using?

Firefox

### System log

_No response_

### PR DESCRIPTION
**Pull request by mvollmer**
Without handling this explicitly, a form submit event will reload the page.  This is very confusing when hitting enter in the login dialog for a remote host.

Fixes #18653

### CODE REVIEW

**Comment by mvollmer** [comment]
Did we never fix this? All our other dialogs are careful to handle form submission.

**Comment by martinpitt** [comment]
OMG, does this fix #18653? This was driving me nuts, and was responsible for many lost hours during debugging (including that issue itself). Thanks³! :heart:

**Comment by martinpitt** [comment]
Perhaps you can adjust my initial reproducer here https://github.com/cockpit-project/cockpit/issues/18653#issuecomment-1525358667 and make sure that pressing enter does not do anything?

File: pkg/shell/hosts_dialog.jsx [hunk 1]
```diff
@@ -69,6 +69,14 @@ function is_method_supported(methods, method) {
     return result ? result !== "no-server-support" : false;
 }
 
+function handle_submit(callback) {
+    return event => {
+        callback();
+        event.preventDefault();
+        return false;
```
Comment (cockpituous) [inline pkg/shell/hosts_dialog.jsx:76]: These 4 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19018-20230626-125250-b763fa4b-fedora-38-devel-networking//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/shell/hosts_dialog.jsx [hunk 2]
```diff
@@ -357,7 +365,7 @@ class MachinePort extends React.Component {
                 <span>{cockpit.format(_("Unable to contact $0."), this.props.full_address)}</span>
                 <span>{_("Is sshd running on a different port?")}</span>
             </p>
-            <Form isHorizontal>
+            <Form isHorizontal onSubmit={handle_submit(callback)}>
```
Comment (cockpituous) [inline pkg/shell/hosts_dialog.jsx:368]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19018-20230626-125250-b763fa4b-fedora-38-devel-networking//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/shell/hosts_dialog.jsx [hunk 3]
```diff
@@ -823,7 +831,7 @@ class ChangeAuth extends React.Component {
             {statement}
             <br />
             {(offer_login_password || offer_key_password) &&
-                <Form isHorizontal>
+                <Form isHorizontal onSubmit={handle_submit(callback)}>
```
Comment (cockpituous) [inline pkg/shell/hosts_dialog.jsx:834]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19018-20230626-125250-b763fa4b-fedora-38-devel-networking//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/shell/hosts_dialog.jsx (hunk 1 above)
Comment (cockpituous) [inline pkg/shell/hosts_dialog.jsx:76]: These 5 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19018-20230626-125250-b763fa4b-fedora-38-devel-storage//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/shell/hosts_dialog.jsx [hunk 4]
```diff
@@ -247,7 +255,7 @@ class AddMachine extends React.Component {
         const title = this.state.old_machine ? _("Edit host") : _("Add new host");
         const submitText = this.state.old_machine ? _("Set") : _("Add");
 
-        const body = <Form isHorizontal>
+        const body = <Form isHorizontal onSubmit={handle_submit(callback)}>
```
Comment (cockpituous) [inline pkg/shell/hosts_dialog.jsx:258]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19018-20230626-125250-b763fa4b-fedora-38-devel-storage//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/shell/hosts_dialog.jsx (hunk 2 above)
Comment (cockpituous) [inline pkg/shell/hosts_dialog.jsx:368]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19018-20230626-125250-b763fa4b-fedora-38-devel-storage//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/shell/hosts_dialog.jsx (hunk 3 above)
Comment (cockpituous) [inline pkg/shell/hosts_dialog.jsx:834]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19018-20230626-125250-b763fa4b-fedora-38-devel-storage//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/shell/hosts_dialog.jsx (hunk 1 above)
Comment (cockpituous) [inline pkg/shell/hosts_dialog.jsx:76]: These 4 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19018-20230626-125250-b763fa4b-fedora-38-devel-expensive//Coverage/lcov/github-pr.diff.gcov.html)

**Comment by mvollmer** [comment]
> OMG, does this fix #18653?

Yes! I wasn't aware of that open issue, damn...

@martinpitt, just to explain what is happening, since you don't seem to have figured it out: Browsers have the concept of "submitting" a "form", see https://developer.mozilla.org/en-US/docs/Learn/Forms/Sending_and_retrieving_form_data.
Submitting is done with a HTTP request by default, and if it happens to any of our dialogs, it looks like a page reload.

The way to code dialogs with Patternfly uses `<form>` elements, for whatever reason, and thus our dialogs are subject to the default Browser treatment of ´form`s. We don't want the Browser to submit our form with a HTTP request, of course,
so we don't use `<button type="submit">Apply</button>`, obviously. However, browsers also submit some forms (not all!) when pressing ENTER in a text input. We have to catch that event and stop the browser from doing its thing. One could argue that PF should do something more useful by default for its `Form` component, but it doesn't.

See https://github.com/cockpit-project/cockpit/pull/15692 for how we fixed this in other places.

File: pkg/shell/hosts_dialog.jsx [hunk 5]
```diff
@@ -69,6 +69,14 @@ function is_method_supported(methods, method) {
     return result ? result !== "no-server-support" : false;
 }
 
+function handle_submit(callback) {
```
Comment (mvollmer) [inline pkg/shell/hosts_dialog.jsx:72]: I think I call this `prevent_default`.

**Comment by mvollmer** [comment]
> Perhaps you can adjust my initial reproducer here [#18653 (comment)](https://github.com/cockpit-project/cockpit/issues/18653#issuecomment-1525358667) and make sure that pressing enter does not do anything?

Yes, thanks!  Pressing enter should in fact apply the dialog and log you in successfully.

File: pkg/shell/hosts_dialog.jsx [hunk 6]
```diff
@@ -69,6 +69,14 @@ function is_method_supported(methods, method) {
     return result ? result !== "no-server-support" : false;
 }
 
+function prevent_default(callback) {
+    return event => {
+        callback();
+        event.preventDefault();
+        return false;
```
Comment (cockpituous) [inline pkg/shell/hosts_dialog.jsx:76]: These 5 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19018-20230627-115453-74cfaf23-fedora-38-devel-storage//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/shell/hosts_dialog.jsx [hunk 7]
```diff
@@ -247,7 +255,7 @@ class AddMachine extends React.Component {
         const title = this.state.old_machine ? _("Edit host") : _("Add new host");
         const submitText = this.state.old_machine ? _("Set") : _("Add");
 
-        const body = <Form isHorizontal>
+        const body = <Form isHorizontal onSubmit={prevent_default(callback)}>
```
Comment (cockpituous) [inline pkg/shell/hosts_dialog.jsx:258]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19018-20230627-115453-74cfaf23-fedora-38-devel-storage//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/shell/hosts_dialog.jsx [hunk 8]
```diff
@@ -357,7 +365,7 @@ class MachinePort extends React.Component {
                 <span>{cockpit.format(_("Unable to contact $0."), this.props.full_address)}</span>
                 <span>{_("Is sshd running on a different port?")}</span>
             </p>
-            <Form isHorizontal>
+            <Form isHorizontal onSubmit={prevent_default(callback)}>
```
Comment (cockpituous) [inline pkg/shell/hosts_dialog.jsx:368]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19018-20230627-115453-74cfaf23-fedora-38-devel-storage//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/shell/hosts_dialog.jsx [hunk 9]
```diff
@@ -823,7 +831,7 @@ class ChangeAuth extends React.Component {
             {statement}
             <br />
             {(offer_login_password || offer_key_password) &&
-                <Form isHorizontal>
+                <Form isHorizontal onSubmit={prevent_default(callback)}>
```
Comment (cockpituous) [inline pkg/shell/hosts_dialog.jsx:834]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19018-20230627-115453-74cfaf23-fedora-38-devel-storage//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/shell/hosts_dialog.jsx (hunk 8 above)
Comment (cockpituous) [inline pkg/shell/hosts_dialog.jsx:368]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19018-20230627-115453-74cfaf23-fedora-38-devel-networking//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/shell/hosts_dialog.jsx (hunk 9 above)
Comment (cockpituous) [inline pkg/shell/hosts_dialog.jsx:834]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19018-20230627-115453-74cfaf23-fedora-38-devel-networking//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/shell/hosts_dialog.jsx (hunk 6 above)
Comment (cockpituous) [inline pkg/shell/hosts_dialog.jsx:76]: These 4 added lines are not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19018-20230627-115453-74cfaf23-fedora-38-devel-other//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/shell/hosts_dialog.jsx (hunk 8 above)
Comment (cockpituous) [inline pkg/shell/hosts_dialog.jsx:368]: This added line is not executed by any test.  [Details](https://cockpit-logs.us-east-1.linodeobjects.com/pull-19018-20230627-115453-74cfaf23-fedora-38-devel-other//Coverage/lcov/github-pr.diff.gcov.html)

File: pkg/shell/hosts_dialog.jsx (hunk 5 above)
Comment (mvollmer) [reply pkg/shell/hosts_dialog.jsx]: Done

**Review by martinpitt — APPROVED** [review]
Thanks! I love you so much right now! :grin:
